### ISSUE TITLE
Issue in loading the image file

### ISSUE THREAD

**Issue by shiv-u** [madmaze/pytesseract#100]
Whenever I try to use pytesseract.image_to_string(img) where 
img=Image.open("test.png")
.I always get the error [winError 2] the system cannot find the file specified even though "test.png" is in the same directory as of my Python program

**Comment by int3l** [comment]
I guess you are using Windows?
In that case, can you try to use the string ``test.png.png`` and if it works, then you should enable displaying the extensions for all files in your OS settings.

**Comment by shiv-u** [comment]
It gives error no such file or directory.

**Comment by int3l** [comment]
Please post the following information: what is your python and OS version?
Also add the following snippet at the top of your failing script:

```python
import sys, os
print(os.path.abspath(sys.argv[0]))

print([f for f in os.listdir(os.path.abspath(sys.argv[0])) if os.path.isfile(f)])
```

This will tell you the current working directory of the script and the list of files in it.

**Comment by shiv-u** [comment]
Python version is 3.6.2
Os version is windows 10

**Comment by int3l** [comment]
Do you even have the *tesseract* executable installed on windows 10?
What version it is?

Also please read the documentation carefully - there is [Installation](https://github.com/madmaze/pytesseract#installation) section.

**Comment by shiv-u** [comment]
I have downloaded pytesseract module , but haven't downloaded tesseract-ocr.

**Comment by int3l** [comment]
pytesseract is just a python wrapper around the Tesseract-OCR engine, so you can't use it without installing the engine. In order to use it, you should install the version for your OS - check the documentation for more details.

Closing since this issue is not a pytesseract specific issue. Please feel free to reopen if you have any other comments or questions.
