### ISSUE TITLE
error  proc = subprocess.Popen(command, stderr=subprocess.PIPE) ... all variables are set correctly

### ISSUE THREAD

**Issue by LogX7** [madmaze/pytesseract#101]
```
Traceback (most recent call last):
  File "d:\learnPython\exercices\OCR\TextRecognizer.py", line 8, in <module>
    txt = pytesseract.image_to_string(img, lang='eng')
  File "d:\learnPython\exercices\OCR\pytesseract.py", line 192, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "d:\learnPython\exercices\OCR\pytesseract.py", line 139, in run_and_get_output
    run_tesseract(**kwargs)
  File "d:\learnPython\exercices\OCR\pytesseract.py", line 115, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
```

i get this error 

here is my script 
```
from PIL import Image
import pytesseract, os

script_dir = os.path.dirname(os.path.abspath(__file__))
img = Image.open(os.path.join(script_dir,'Untitled.jpg'))
txt = pytesseract.image_to_string(img, lang="eng")

print (txt)
```

i have set this
`tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract''`

and i have added the tesseract variable to windows path variables

**Comment by int3l** [comment]
Please follow the documentation.
There is a fix that error - for example:
```python
tessdata_dir_config = '--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
# Example config: '--tessdata-dir "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata"'
# It's important to add double quotes around the dir path.

pytesseract.image_to_string(image, lang='chi_sim', config=tessdata_dir_config)
```

**Comment by int3l** [comment]
Closing as duplicated of #50 
Also the fix is already known.

**Comment by 1292586222** [comment]
I hava the same promblem like this ,I have already revise tesseract_cmd = 'D:/Tesseract-OCR/tesseract' in pytesseract.py and set environmental variable D:\Tesseract-OCR (already download Tesseract-OCR),but the problem still have ,anyone could help me ?
![2](https://user-images.githubusercontent.com/31563007/39281192-f5ee3e92-4935-11e8-9ae4-100919c9662a.PNG)
![1](https://user-images.githubusercontent.com/31563007/39281194-f98c6006-4935-11e8-8f41-bcf098c06fff.PNG)

**Comment by MKServices1** [comment]
> Please follow the documentation.
> There is a fix for that error - example config:
> 
> ```python
> tessdata_dir_config = '--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
> # Example config: '--tessdata-dir "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata"'
> # It's important to add double quotes around the dir path.
> 
> pytesseract.image_to_string(image, lang='chi_sim', config=tessdata_dir_config)
> ```

i can't find this tessdata folder, kindly help me regarding tessdata path

**Comment by int3l** [comment]
Hi @MKServices1 - it depends where you install your Tesseract bundle itself. And if you don't have it, you need to install it first in order to have access to it. Take a look at the installation section of the README for more details.
