### ISSUE TITLE
Error opening data file (again)

### ISSUE THREAD

**Issue by thinkingparticle** [madmaze/pytesseract#109]
i have seen #50 #64 #65 . but i cant fix my problem.

i use these: 
`
pytesseract.pytesseract.tesseract_cmd = 'D:\\Softwares\\Tesseract-OCR\\tesseract'
tessdata_dir_config = '--tessdata-dir "D:\\Softwares\\Tesseract-OCR\\tesseract\\tessdata"'
pytesseract.image_to_string(Image.open(io.BytesIO(captcha_res.content)),lang="eng",config=tessdata_dir_config)
`
result: 
`TesseractError: (1, 'Error opening data file D:\\Softwares\\Tesseract-OCR\\tesseract\\eng.traineddata Please make sure....`
note that it does not look in "tessdata" folder,

i tried this : 
`pytesseract.pytesseract.tesseract_cmd = 'D:\\Softwares\\Tesseract-OCR\\tesseract'
tessdata_dir_config = '--tessdata-dir "D:\\Softwares\\Tesseract-OCR\\tesseract\\tessdata\\\\"'
pytesseract.image_to_string(Image.open(io.BytesIO(captcha_res.content)),lang="eng",config=tessdata_dir_config)
`
result:
`
Error opening data file D:\\Softwares\\Tesseract-OCR\\tesseract\\tessdata\\eng.traineddata Please make sure ...
`
now it searched in tessdata folder but still does not work. i checked "eng.traineddata" exists in tessdata folder. 

win8
python3.5

**Comment by int3l** [comment]
Hi @thinkingparticle did you have the chance to test the tesseract cli command equivalent in your terminal without using pytesseract?

This issue might be a limitation/problem of the tesseract executable itself.

Also: `pytesseract.pytesseract.tesseract_cmd` should be the **full path** to the tesseract.exe itself.
And the config folder should be just the **full directory path** to the tessdata folder.
So are you sure that the folder `D:\\Softwares\\Tesseract-OCR\\tesseract\\tessdata\\` exist?

You can check if the folder exists with this python code snippet:
```python
from os.path import exists; exists('D:\\Softwares\\Tesseract-OCR\\tesseract\\tessdata\\')
```
