### ISSUE TITLE
why i install pytesseract,show TypeError: integer argument expected, got 'str' error 

### ISSUE THREAD

**Issue by jxua** [madmaze/pytesseract#119]
because our company can not use pip install,so i download it in git,then easy_install.but when install,show below error.From 0.1.6 to 0.2.0 all show this error,
image i will wait on-line for it,please help me quicky,thanks

 @int3l
Collaborator
int3l commented 12 hours ago
You can try to unpack the archive.

uncompress the archive
cd to the unpacked folder
use setup.py directly with either pip or python
cd <dir_with_setup.py>
# AND
pip install .
# OR
python setup.py install
Closing this since this is not a pytesseract specific problem.
It is a deployment issue on Windows + Anaconda platform.
And please read the Installation documentation section (README file) ...

 @int3l int3l closed this 12 hours ago
@jxua
  
jxua commented 4 minutes ago
when i try use python setup.py install, also this error show

 @jxua
  
jxua commented a minute ago
try pip install . also this error

**Comment by int3l** [comment]
The specific error is not from pytesseract itself.
It comes from your Anaconda installation.

When I have free time I will try to install Anaconda in order to test.

**Comment by jxua** [comment]
thanks,but i also try easy_install and python install,

**Comment by jxua** [comment]
by the way, when i re-install anaconda, these packages i installed before, if there can be used or i will install these packages again?
