### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [madmaze/pytesseract#122]
The pypi source archive isn't including the LICENSE file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by int3l** [comment]
Hi @toddrme2178 feel free to test with the 0.2.2 version.

Ping @madmaze - please update the pypi release version to the latest one, thanks in advance!

**Comment by madmaze** [comment]
updated on pypi!
