### ISSUE TITLE
In linux, how to install pytesseract for python 2.7, not for python 3?

### ISSUE THREAD

**Issue by TopNotchGuru** [madmaze/pytesseract#124]
I'd like to install pytesseract in python2.7/dist-packages.
I tried "pip install pytesseract".
But it is installed in python3/dist-packages.
Please help me.

**Comment by int3l** [comment]
What is your Linux distro?
Usually you can install pip2 and execute command like that:
`pip2 install pytesseract`

**Comment by TopNotchGuru** [comment]
Thanks. :)
