### ISSUE TITLE
No options to identify Word Font Attributes

### ISSUE THREAD

**Issue by vinayakkailas** [madmaze/pytesseract#125]
Curreently pytesseract is not providing ability to create PyTessBaseAPI() and use an iterator to get the word font attributes

**Comment by int3l** [comment]
Hi @vinayakkailas ,
pytesseract library doesn't have/support such API.

Maybe you should forward this issue to the [tesserocr](https://github.com/sirfz/tesserocr) project. According to the documentation, there is a PyTessBaseAPI context manager with that name.

Feel free to reopen if you have any other questions/comments.
