### ISSUE TITLE
TIF old style jpeg compression

### ISSUE THREAD

**Issue by psinger** [madmaze/pytesseract#127]
I am trying to pass a tif file to pytesseract. The problem with the file is that it uses old jpeg compression. You can replicate the issue with the one provided at https://github.com/openpreserve/format-corpus/tree/master/tiff-examples/old-style-jpeg-compression.

The problem seems to be a combination of Pillow, pytesseract and libtiff. I have also filed an issue at the Pillow repo: https://github.com/python-pillow/Pillow/issues/3132

Running tesseract directly on the image works, so it has something to do with converting and saving the image beforehand in pytesseract.

**Comment by int3l** [comment]
Hi @psinger , thanks for reporting the issue.

We can fix this in two ways:
1. Add passthrough option in order to skip any conversion - raw image mode.
2. Wait for fix from Pillow/add custom imagemagick workaround.

For now, I guess that you can temporarily use the custom imagemagick workaround to fix your problem.

**Comment by psinger** [comment]
@int3l You mean converting it before with imagemagick? The best solution I have at the moment is to catch the exception and run tesseract directly on it.

What is important to mention though, is that with slightly older tifflib versions, pytesseract gets completely stuck based on Pillow being stuck. Took me a long way to figure out what the issue is there. I guess not much can be done in pytesseract anyways, maybe offering a skip conversion mode would be feasible.

**Comment by int3l** [comment]
TIFF metadata for the old-style-jpeg-compression image:
```
./exiftool.exe -s -ee -g1 -u -n -D a.tif
---- ExifTool ----
    - ExifToolVersion                 : 11.00
---- System ----
    - FileName                        : a.tif
    - Directory                       : .
    - FileSize                        : 213760
    - FileModifyDate                  : 2018:06:07 21:12:04+03:00
    - FileAccessDate                  : 2018:06:07 21:11:53+03:00
    - FileCreateDate                  : 2018:06:07 21:12:03+03:00
    - FilePermissions                 : 666
---- File ----
    - FileType                        : TIFF
    - FileTypeExtension               : TIF
    - MIMEType                        : image/tiff
    - ExifByteOrder                   : II
---- IFD0 ----
  254 SubfileType                     : 0
  256 ImageWidth                      : 4160
  257 ImageHeight                     : 870
  258 BitsPerSample                   : 8 8 8
  259 Compression                     : 6
  262 PhotometricInterpretation       : 6
  273 StripOffsets                    : 768
  274 Orientation                     : 1
  277 SamplesPerPixel                 : 3
  278 RowsPerStrip                    : 870
  279 StripByteCounts                 : 212992
  282 XResolution                     : 300
  283 YResolution                     : 300
  284 PlanarConfiguration             : 1
  296 ResolutionUnit                  : 2
  305 Software                        : Kofax standard Multi-Page TIFF Storage Filter v3.03.000
  306 ModifyDate                      : 2016:10:14 11:40:04
  513 OtherImageStart                 : 768
33000 Exif_0x80e8                     : 0
---- Composite ----
    - ImageSize                       : 4160x870
    - Megapixels                      : 3.6192
```

**Comment by psinger** [comment]
What version of libtiff are you running? I had problems with old ones completely freezing and not returning at all in e.g., Pillow.

**Comment by psinger** [comment]
I am hijacking this thread directly for another TIFF error. I have another tiff file that has  ```image.mode='1'``` meaning it has 1-bit pixels, black and white, stored with one pixel per byte. However, in pytesseract it i converted to RGB.

First of all, why is this done? Second, this unfortunately leads to another error when saving the file: ```Fax3SetupState: Bits/sample must be 1 for Group 3/4 encoding/decoding```

Apparently, you cannot do that according to https://github.com/python-pillow/Pillow/issues/396

**Comment by int3l** [comment]
Fundamentally, the conversion is need because we are doing copy of the image, in order to pass it to the tesseract executable. And even if you use the pillow Image.save method, there is a chance that the image will be converted implicitly before saved to disk by the Pillow library.

But anyway, this means that we need a bypassing option for the wrapper in order to allow users to try the recognition with raw image data.

Changing this to a feature request.
Thank for your time to investigate/test those issues.
