### ISSUE TITLE
License Type

### ISSUE THREAD

**Issue by cyrust** [madmaze/pytesseract#128]
Given that pytesseract is a relatively small package, would it be possible to release it under the Apache License similar to Tesseract?

**Comment by madmaze** [comment]
Please refer to the license already specified: https://github.com/madmaze/pytesseract/blob/master/LICENSE

**Comment by cyrust** [comment]
Thanks for the response. I'm sure most users and myself included will respect whatever you decide on this. 

I do personally think though that for an underlying package like tesseract which doesn't require publication of source code, having a wrapper restrict the licensing to open source can restrict the usage of the wrapper.
