### ISSUE TITLE
Conda repository

### ISSUE THREAD

**Issue by cyrust** [madmaze/pytesseract#129]
Would you be willing to consider a repository on Conda/Anaconda?

For users that use conda to manage their packages, using pip simultaneously creates problems such as needing to reinstall packages that were previously installed in conda.

When I tried installing pytesseract with pip within a conda environment, my python interpreter could no longer find my py-opencv installation.

**Comment by int3l** [comment]
Hi @cyrust I will take a look at the documentation for conda packaging, when I have time.
Meanwhile, if you are familiar with it, you can propose example recipe for the conda-forge repo.

**Comment by int3l** [comment]
This should fix #119

**Comment by int3l** [comment]
One possible option for this is the popular community project for conda packages: [conda-forge](https://conda-forge.org) ([GitHub recipe example and push repo](https://github.com/conda-forge/staged-recipes))

**Comment by int3l** [comment]
Additional information for the testing of the package can be found in #208

**Comment by int3l** [comment]
It seems that there are some unofficial conda-forge repositories that are up to date.
Maybe in the future when Matt or I have some time, we can setup additional official repository.
