### ISSUE TITLE
Coordinates Problem when changing image size 

### ISSUE THREAD

**Issue by engahmed1190** [madmaze/pytesseract#130]
I am facing a problem  when I fill an image with zeros to change image size (H, W)
original image(image) : https://imgur.com/a/6p2rDmS
half image (bottom_image): https://imgur.com/a/nueVevi

```
height, width = image.shape[:2]
#create empty matrix
vis = np.ones((height, width), np.uint8)

# Let's get the starting pixel coordiantes (top left of cropped bottom)
start_row, start_col = int(height * .5), int(0)
# Let's get the ending pixel coordinates (bottom right of cropped bottom)
end_row, end_col = int(height), int(width)
vis[start_row:end_row , start_col:end_col] = bottom_image
```

The results return as if i have the bottom_image only 

when i use 
`boxes = pytesseract.image_to_boxes(vis,config='--psm 6' ,lang='eng')`

result as same as 

`boxes = pytesseract.image_to_boxes(bottom_image,config='--psm 6' ,lang='eng')`

results:

```
{
    "result": [
        {
            "x": "220",
            "y": "152"
        },
        {
            "x": "424",
            "y": "252"
        },
        {
            "x": "224",
            "y": "252"
        }
    ]
}
```

**Comment by int3l** [comment]
Hi @engahmed1190 , did you tested directly with tesseract executable itself to see if the result is different?

**Comment by engahmed1190** [comment]
I found different results . but how i can debug this case it's very strange .

**Comment by int3l** [comment]
Well if the results from pytesseract and tesseract match for every specific case, then the problem is from tesseract itself.

Pytesseract is just a wrapper, which does it a little bit easier for the user to do recognition. But all the OCR functions are done by tesseract, so please feel free to open issue in the [Tesseract-OCR Issue tracker](https://github.com/tesseract-ocr/tesseract/issues)

**Comment by int3l** [comment]
Feel free to reopen if you have any other questions or comments.
