### ISSUE TITLE
Not Extracting coloured text from images

### ISSUE THREAD

**Issue by punit121** [madmaze/pytesseract#131]
![test_1](https://user-images.githubusercontent.com/13787642/41761154-e7fae302-7613-11e8-90c2-88e3829706d9.jpg)

this is not printing anything

**Comment by int3l** [comment]
Hi @punit121 thanks for reporting the issue. Did you check the result from tesseract itself?
If Tesseract itself returns empty string in terminal, then the issue is not related to pytesseract.
