### ISSUE TITLE
image_to_date version check typeerror

### ISSUE THREAD

**Issue by r4ch45** [madmaze/pytesseract#132]
When using the image_to_data function I get a TypeError. Think this is due to the version check using the version that isn't an int.
`pyt.get_tesseract_version()`
LooseVersion ('v4.0.0-beta.1.20180608')

`import pytesseract as pyt

from PIL import Image

image = Image.open(sample_jpg)

image = image.crop(box=((110,1310,2920,1780)))

image.save(small_sample_jpg)

img_bxs = pyt.image_to_boxes(image, lang='eng')

img_str = pyt.image_to_string(image, lang='eng')

img_data = pyt.image_to_data(image, lang='eng')`

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-227-77428bd20269> in <module>()
      1 img_bxs = pyt.image_to_boxes(image, lang='eng')
      2 img_str = pyt.image_to_string(image, lang='eng')
----> 3 img_data = pyt.image_to_data(image, lang='eng')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pytesseract\pytesseract.py in image_to_data(image, lang, config, nice, output_type)
    319 
    320     # TODO: we can use decoration for this check
--> 321     if get_tesseract_version() < '3.05':
    322         raise TSVNotSupported()
    323 

~\AppData\Local\Continuum\anaconda3\lib\distutils\version.py in __lt__(self, other)
     50 
     51     def __lt__(self, other):
---> 52         c = self._cmp(other)
     53         if c is NotImplemented:
     54             return c

~\AppData\Local\Continuum\anaconda3\lib\distutils\version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'`

**Comment by int3l** [comment]
@r4ch45 hi and thank you for reporting the issue.
This is interesting, I guess that you are using python 3?
Can you replace this line in pytesseract.py and test if it work:
```python
if get_tesseract_version() < '3.05':
```
With:
```python
if get_tesseract_version() < LooseVersion('3.05'):
```

**Comment by int3l** [comment]
You can test the latest version from github with the fix.

**Comment by r4ch45** [comment]
Awesome, that's fixed it. Thanks for the super quick help! (and yeah good guess it was Python3) :)

**Comment by mousumisaha** [comment]
Hi r4ch45..can you please get me the link for the updated version. I am also facing the same error. Thanks in advance.

**Comment by mousumisaha** [comment]
Hi @r4ch45 can you please get me the link for the latest .exe file. I am also getting the same error. Thanks in advance.

**Comment by r4ch45** [comment]
Hi @mousumisaha , I just did "pip install pytesseract" to get the latest version? Not sure what you mean..?

**Comment by int3l** [comment]
@mousumisaha You can check the documentation.
If you want the latest version as it is from github:
1. Download the code from github, uncompress it and execute this command:
```bash
cd pytesseract-master && pip install -U .
```

2. Or If you have **git** installed on your system:
```bash
pip install -U git+https://github.com/madmaze/pytesseract.git
```

**Comment by mexuaz** [comment]
I do still have this problem using the master branch.
Python 3.9/ pytesseract 0.3.7

> config, nice, output_type, timeout, pandas_config)
>     508     """
>     509 
> --> 510     if get_tesseract_version() < '3.05':
>     511         raise TSVNotSupported()
>     512 
> 
> /usr/lib/python3.9/distutils/version.py in __lt__(self, other)
>      50 
>      51     def __lt__(self, other):
> ---> 52         c = self._cmp(other)
>      53         if c is NotImplemented:
>      54             return c
> 
> /usr/lib/python3.9/distutils/version.py in _cmp(self, other)
>     337             return NotImplemented
>     338 
> --> 339         if self.version == other.version:
>     340             return 0
>     341         if self.version < other.version:
> 
> AttributeError: 'LooseVersion' object has no attribute 'version'

**Comment by int3l** [comment]
@mexuaz this is very strange, considering that every test pass in the CI.
Maybe you have a problematic `distutils` version or something.

Can you try the following example in your python REPL

```python
from distutils.version import LooseVersion
LooseVersion('4.1.0') < '3.5'
```
