### ISSUE TITLE
Any way to access the confidences?

### ISSUE THREAD

**Issue by LForchini** [madmaze/pytesseract#133]
If possible, I need to access the confidences the program has for each letter. Is there any way of doing this?

**Comment by int3l** [comment]
Hi @LForchini - pytesseract is just a wrapper for the tesseract executable itself.
Please refer to the documentation of tesseract itself for more information.
Almost everything that is returned by the tesseract executable, can be fetched with pytesseract.

Also please read our [USAGE section in the README documentation](https://github.com/madmaze/pytesseract#usage). There is option for returning confidences for the data with the function **image_to_data**.
