### ISSUE TITLE
GIF image can not work

### ISSUE THREAD

**Issue by sheyu** [madmaze/pytesseract#135]
for example:
im_gif = Image.open('GetValidateCode.gif')
im_gif_rgb = im_gif.convert('RGB')
im_gif_rgb.save('test.gif', 'gif')

will rasie :

File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 495, in _write_local_header
    transparency = int(transparency)
TypeError: int() argument must be a string or a number, not 'tuple'

the reason is:
PIL convert 'P' to 'RGB' will change the item 'transparency' of image.info from number to tuple. 

so , useing pytesseract to reslove GIF image will have the upside problem.
how about modify the GIF image save_format from GIF to PNG or JPEG.

pytesseract.py  
func: save_image
  ```
  if image.format not in {'JPEG', 'PNG', 'TIFF', 'BMP', 'GIF'}:
        img_extension = 'PNG'
```
delete the GIF

**Comment by int3l** [comment]
Hi @sheyu. Thank you for reporting the issue.
If I understand you correctly, you have problem with some GIF conversion. 
You can convert the image beforehand in a proper format as a workaround.
The logic in save_image, converts the image only if its format is not one of the supported tesseract inputs.

Can you provide sample GIF image that raises error upon conversion?

**Comment by sheyu** [comment]
thx, i do not find your mail in you page, how about provide you email? i will send the problem pic to you.

**Comment by int3l** [comment]
Sorry, I can't offer you email of mine, but you can upload the image on a public hosting. And you can share the link here.
