### ISSUE TITLE
How to convert an image to string if its not basic format

### ISSUE THREAD

**Issue by GloryToArstotzka** [madmaze/pytesseract#139]
I'm trying to use this package to make my program recognize the amount of mana I have available [in hearthstone] , the problem is : When I use this library on a notepad text it works 100% of the time sometimes with accuracy problems , but it never works on other types of text and usually when the background is different 

I wanna know if I did something wrong and these features exist or if they don't exist , will they ever be included or this library got abandoned?

**Comment by int3l** [comment]
Please ask your question on StackOverflow.
