### ISSUE TITLE
Method for adding config settings

### ISSUE THREAD

**Issue by Jeremiah-England** [madmaze/pytesseract#141]
## Look mama, no config files!

I was wrestling with config files for some of the settings when I ran across [this](https://groups.google.com/forum/#!topic/tesseract-ocr/Hr79AmtApeA) google group discussion about tesseract using **java** and it made my mouth water. Here's a code snippet from their discussion:

    tesseract = new Tesseract();                      
    tesseract.setOcrEngineMode(TessAPI.TessOcrEngineMode.OEM_TESSERACT_ONLY);
    tesseract.setPageSegMode(7);
    tesseract.setTessVariable("load_system_dawg", "0");
    tesseract.setTessVariable("load_freq_dawg", "0");
    tesseract.setTessVariable("load_punc_dawg", "0");
    tesseract.setTessVariable("load_number_dawg", "0");
    
At first you may think, well that's cool I guess but you can really do the same thing by just defining a long string of configs and calling it whenever you need it. For example, `'--psm 10 --oem 3 -c load_system_dawg=0 load_freq_dawg=0 load_punc_dawg=0 . . .'`

In the tesseract documentation, it mentions that [you can't change 'init only' parameters with tesseract executable option `-c`](https://github.com/tesseract-ocr/tesseract/wiki/ControlParams#init-only). And those 'init only' parameters would include some of the ones I've been messing with. I think that most people would say that it would be nice to be able to set your variables for your config file directly in python using a `set_config_variable` method instead of having to go make a config file. Since some of the variables that are being set in the code above are in fact 'init only', the Java guys must be creating a config file (I did not sniff through their code to verify this, however) from java code.

I haven't done it yet because I'm not too familiar with the code inside `pytesseract`, but right now making a temporary config file and letting it be loadable via a `set_config_variable` method doesn't seem very hard from my perspective. Here's the high level logic I'm thinking about:
  - When pytesseract is imported, check the config folder to see if a temp.txt file exists. If so, wipe it clean. If not, create one. 
  - When someone calls the `tsr.set_config_variable` method, just write the variable, a space, and the value on a new line in the temp.txt file. 
  - You could also have a method to delete the variable from the file and thus return tesseract to the default.
  - When any of the OCR functions are called, if the user does not manually supply another config file, use the temp.txt as the config file unless it's empty.
  
Why this would be a good feature:
  - For me and others like me who wrote their first line of code 8 months ago, even little trips to the back-end of config files or source code can be confusing and take lot's of time.
  - There's a lot of super ridiculously lazy people out there just like me who would rather not know anything about how the programs and libraries work which they're using, but just want to use them to make other interesting applications.  
  
But maybe it's actually not very easy to implement. Is this actually possible?

**Comment by Mebus** [comment]
This would be great, I wish I was able to do something like this:

https://stackoverflow.com/questions/4944830/how-to-make-tesseract-to-recognize-only-numbers-when-they-are-mixed-with-letter

Mebus

**Comment by int3l** [comment]
Hi, thank you very much for the proposal.
This can be implemented and in fact - you can implement it with a custom logic for yourself.
At the end of the day - you can make your own logic for handling config files, and then you can pass the resulting config file via the ```config``` method argument.

As far as integrating this into pytesseract - well, I if I have some free time, I will try to implement the logic for this. The only "problematic" part of this is - where to store this temp config.

And btw, we can have this nice python approach:

```python
config = pytesseract.temp_config(path='<custom_filepath>')
config.set_variables({'key': 'value'})
pytesseract.image_to_string('<image_filepath>', config=config)
```

**Comment by Debjoy10** [comment]
@int3l the above method is giving an error AttributeError: module 'pytesseract' has no attribute 'temp_config'. Any solutions?

**Comment by int3l** [comment]
@Debjoy10 it is not implemented yet. This is a feature request.

**Comment by Raghwendra-Dey** [comment]
@int3l do we have any workaround for doing this for the time being?

**Comment by int3l** [comment]
@Raghwendra-Dey please take a look at the README documentation and the example configurations.
You should use the specific **tesseract** command options - but for this you should go to the Tesseract Wiki Documentation.

**Comment by Raghwendra-Dey** [comment]
@int3l we were looking around for modifying the variables like editor_image_word_bb_color , editor_word_height , editor_word_width , etc. but no way to do it in pytesseract, though tesseract has its work around... 
https://guides.gdpicture.com/content/Affecting%20Tesseract%20OCR%20engine%20with%20special%20parameters.html

**Comment by int3l** [comment]
I am not very familiar with the tesseract custom config files, where you can add this options and then pass the custom config file to pytesseract via the config argument.

Maybe you should ask in the [Tesseract Github Issue Tracker](https://github.com/tesseract-ocr/tesseract/issues). Pytesseract is just a tin wrapper around the tesseract executable.

**Comment by Debjoy10** [comment]
Can you tell me more about the config argument? I have made a config file but finding it difficult to use it in pytesseract.
Thanks in advance.

**Comment by Raghwendra-Dey** [comment]
@int3l ??

**Comment by int3l** [comment]
Take a look at the [Tesseract OCR documentation](https://github.com/tesseract-ocr/tesseract/wiki/Documentation) and [example config files](https://github.com/tesseract-ocr/tesseract/tree/master/tessdata/configs).
Closing this  since it is not a pytesseract specific issue. Please ask in the Tesseract Github Issue Tracker.

**Comment by Debjoy10** [comment]
chutiye bsdk madarchod

**Comment by Debjoy10** [comment]
But my doubt is, I want to use the config file in pytesseract, does pytesseract provide a way to do that conveniently(inside the code)?

**Comment by Debjoy10** [comment]
Apologies for the previous comment. It was mistakenly pasted here.

**Comment by int3l** [comment]
@Debjoy10 Sorry, I see what you mean - In that case try to specify the name of the config file as  second argument to `pytesseract.pytesseract.run_and_get_output` instead of using `pytesseract.image_to_string`.

This function allows more user control, but it is not "public", although you can use it.
And you are right - at the moment, this is a bit of limitation for pytesseract itself.

**Comment by int3l** [comment]
Soon it will be possible to import **run_and_get_output** directly from `pytesseract.run_and_get_output`.

**Comment by Debjoy10** [comment]
Thanks for the reply. However, what I was wanting to use was pytesseract.image_to_data. Is there a workaround for that too?
And, with pytesseract.run_and_get_output do we need to provide the path to the config file, or it can retrive that file from the configs directory of tesseract?

**Comment by EricPHamilton** [comment]
I was able to supply my own config file by using the following:
("words" is the name of my config file)
pytesseract.run_and_get_output(im, extension="txt", config="words")

**Comment by naourass** [comment]
Where do you save "words" custom config file ?
