### ISSUE TITLE
Unable to extract text with length 2 or less in image

### ISSUE THREAD

**Issue by parthbkgadoya** [madmaze/pytesseract#143]
Try using tesseract (Linux) on this image:
![te](https://user-images.githubusercontent.com/15686046/43907640-955d53d4-9c13-11e8-8c03-68361004be56.png)

It returns empty string. How to resolve this issue. Please help.

Reference code: 
`from pytesseract import image_to_string
import cv2

im = cv2.imread("teo.png")

print(image_to_string(im))`

**Comment by int3l** [comment]
This is a Tesseract specific problem, please try to upgrade the current version that you have and if this doesn't help - you can create issue on [Tesseract-OCR](https://github.com/tesseract-ocr/tesseract/issues)

**Comment by SumedhaI** [comment]
> Try using tesseract (Linux) on this image:
> ![te](https://user-images.githubusercontent.com/15686046/43907640-955d53d4-9c13-11e8-8c03-68361004be56.png)
> 
> It returns empty string. How to resolve this issue. Please help.
> 
> Reference code:
> `from pytesseract import image_to_string
> import cv2
> 
> im = cv2.imread("teo.png")
> 
> print(image_to_string(im))`

I am facing the same issue!  Is it fixed? If yes how did you resolve it?

**Comment by parthbkgadoya** [comment]
If any one faces same issue, this is what I find on stackoverflow:
https://stackoverflow.com/questions/51767749/tesseract-ocr-is-not-working-on-image-which-have-text-length-of-only-2-or-less/52246027#52246027

More than that I have not tried.
