### ISSUE TITLE
How can use multiple threads when operating?

### ISSUE THREAD

**Issue by jewelcai** [madmaze/pytesseract#144]
Hi, 
When I am processing the scanned document, it was very slow, so I want to use the multiple threads to speed up. 
Is there any solutions now? 
Thanks

**Comment by int3l** [comment]
At the moment, there is nothing built-in within pytesseract,
Basically you should implement.

**Comment by kimberlybammoney** [comment]
It's also pretty slow for me. How slow is it for you? The worst time I've seen so far is 80 seconds for 3 high-res pages of text.

**Comment by int3l** [comment]
Closing this one, feel free to reopen if you need to.
