### ISSUE TITLE
Paragraph Bounding Boxes in pytresseract

### ISSUE THREAD

**Issue by dillu24** [madmaze/pytesseract#145]
Hi , 

I am trying to use Pytesseract by inputting a receipt image such as the one in the link below and create bounding boxes across blocks of text . I am failing because the image_to_boxes function is only creating boxes around each individual letter . I also read about tesseract's page segmentation method and tried all modes and still failed.

This is what I have tried so far : 

import cv2
import pytesseract
import matplotlib.pyplot as plt

filename = 'optimized_scanned_images/test1.jpg'
img = cv2.imread(filename)
h, w, _ = img.shape
boxes = pytesseract.image_to_boxes(img, config='-psm 5')

for b in boxes.splitlines():
    b = b.split(' ')
    img = cv2.rectangle(img, (int(b[1]), h - int(b[2])), (int(b[3]), h - int(b[4])), (0, 255, 0), 1)

fig, ax = plt.subplots(figsize=(10, 6))
ax.imshow(img)
ax.set_axis_off()
plt.tight_layout()
plt.show()

This is the image : 

![hdchk](https://user-images.githubusercontent.com/23262259/44022744-c92c859a-9ee8-11e8-999c-60dbeae00255.jpg)

**Comment by int3l** [comment]
What is the error?
Did you tried to do this with tesseract itself first?
I am not sure if this is pytesseract issue itself.

**Comment by dillu24** [comment]
I am asking whether you could do bounding boxes using pytesseract per block in the receipt . So far the image_to_boxes function only created bouding boxes per letter in the receipt

**Comment by int3l** [comment]
Well, if you can tell me the tesseract cli command for doing per block bounding boxes, then I could tell you if pytesseract supports this scenario or not.
