### ISSUE TITLE
Unicharset error

### ISSUE THREAD

**Issue by letmerecall** [madmaze/pytesseract#146]
Hi,
The error I got is below:
raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (-11, 'Tesseract Open Source OCR Engine v4.0.0-beta.4-26-gfd49 with Leptonica Warning. Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 172 contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509')
Any thoughts why this could have raised, otherwise it was working perfectly!

**Comment by int3l** [comment]
Hi @letmerecall,
I guess that this is a known bug: tesseract-ocr/tesseract#205
