### ISSUE TITLE
Custom Path

### ISSUE THREAD

**Issue by Naotonosato** [madmaze/pytesseract#147]
I will let you know that My English isn't so good and I am a beginner at GitHub so please point out to me if something is inapproiate.

I think this function should be added to use tesseract-ocr in the app.
example:
def setting_path(tesseract_path,tessdata_path):
    os.environ['path'] += ';' + tesseract_path
    os.environ['TESSDATA_PREFIX'] = tessdata_path

**Comment by int3l** [comment]
Hi @Naotonosato , 
You can do this for your app without a problem.
I am not sure that a separate method will give any additional benefit over doing this yourself.

**Comment by Naotonosato** [comment]
@int3l
Yes.
