### ISSUE TITLE
Importing pytesseract module invoking wrong system calls

### ISSUE THREAD

**Issue by abhiTronix** [madmaze/pytesseract#149]
## System Info:
**pytesseract:** 0.2.4(Latest)
**Machine:** Raspberry pi with Stretch (Latest)
**Tesseract :** 4.0.0-beta.1-318-gee2a
**Pillow:** 5.2.0

## Issue:
`import pytesseract` invoking wrong calls to multiple python modules.

## Root Cause:
`import Image` in **pytesseract.py** file of the **pytesseract module**. It is causing system compiler to search for **Image module** which in turns making multiple calls to different python modules with name **Image.py**.

## Solution:
**Correct Module: PIL (Pillow)**
so, `from PIL import Image` is the right (and must be default) import instead of `import Image` , therefore,
```
try:
    import Image
except ImportError:
    from PIL import Image

```
### must change to:

```
try:
    from PIL import Image
except ImportError:
    import Image
```
in the source (**pytesseract.py**) file.

**Comment by int3l** [comment]
Hi @abhiTronix Thank you for the suggestion - it makes sense, since we already have the Pillow dependency.
