### ISSUE TITLE
inaccurate values from pytesseract.image_to_boxes(Image.open("tab_sm.PNG"))

### ISSUE THREAD

**Issue by scratchnooob** [madmaze/pytesseract#150]
I am trying to get the coordinates of text boxes of an image, from which I want to get the color of the text. but the coordinates are not really accurate. even though the image is of fair good quality. 
I assume the output of image_to_boxes is x y w h?
Is there a way to improve the accuracy of this method?

**Comment by int3l** [comment]
Did you tested directly with tesseract itself?
If the results are the same, then this is a tesseract issue.
