### ISSUE TITLE
image_to_boxes throw invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by malnakli** [madmaze/pytesseract#153]
If `run_and_get_output(*args)` function return empty `''` string
then the following function will fail and throw `invalid literal for int() with base 10: ''`
https://github.com/madmaze/pytesseract/blob/f76914eff07552c478ee67a9204d589b32e36c01/src/pytesseract.py#L310

workaround
```
result = pytesseract.image_to_boxes(img)
if len(tsv_body) > 0:
  tsv_header = 'char left bottom right top page\n'
  result = pytesseract.pytesseract.file_to_dict(tsv_header + result, ' ', 0)
```

**Comment by int3l** [comment]
Hi, @malnakli ,
Thank you for reporting the issue.
