### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by crazzle** [madmaze/pytesseract#155]
Hi,
we are really looking forward to use the new hOCR capabilities of pytesseract in a prod-ready environment.

Could you create a new release with the new features?

Thanks!
Mark

**Comment by int3l** [comment]
@crazzle Hi, thank you for the reminded. I created the github [v0.2.5](https://github.com/madmaze/pytesseract/releases/tag/v0.2.5) release.
Assigning to @madmaze for publishing to pypi.

**Comment by madmaze** [comment]
done.
