### ISSUE TITLE
'numpy.ndarray' object has no attribute 'split'

### ISSUE THREAD

**Issue by TarzanWonder** [madmaze/pytesseract#158]
hi,

I have the latest version of tesseract 4 but still getting the error 

    if len(image.split()) == 4:
AttributeError: 'numpy.ndarray' object has no attribute 'split'
![capture](https://user-images.githubusercontent.com/41734073/47784956-4672de00-dd2d-11e8-9ac9-2e90115f4de1.PNG)

can you please help on this?

**Comment by int3l** [comment]
Hi @TarzanWonder, please update your pytesseract version too, because there is a fix for that.

**Comment by TarzanWonder** [comment]
Thank you so much it is working. How to improve it's accuracy?

**Comment by int3l** [comment]
You can ask on StackOverflow for all questions related to the tesseract itself.
