### ISSUE TITLE
Recognition of Single characters

### ISSUE THREAD

**Issue by UpcominTerminator** [madmaze/pytesseract#162]
I wanted to know does tesseract not work for recognition of single characters.
BTW How do I make it work for single characters?
Thank You

**Comment by int3l** [comment]
@UpcominTerminator hi!
This issue tracker is for pytesseract and not for tesseract itself.
I can imagine that the OCR can work for single characters.
For additional information, please use the [tesseract issue tracker](https://github.com/tesseract-ocr/tesseract) if you have problems or ask on [StackOverflow](https://stackoverflow.com/) with the appropriate tags.
