### ISSUE TITLE
ParserError when Tesseract output contains quotes

### ISSUE THREAD

**Issue by YutaoLiCN** [madmaze/pytesseract#163]
`image_to_data(..., output_type-'data.frame')` might not function well when Tesseract engine returns 'text' that contains `"`.

It is better to use 
```python
return pd.read_csv(BytesIO(run_and_get_output(*args)), sep="\t", quoting=3)
 ```
in pytesseract.py

**Comment by int3l** [comment]
Thanks for catching that one 👍
