### ISSUE TITLE
Error occured during adopting pytesseract to OCR sth

### ISSUE THREAD

**Issue by SheAQ** [madmaze/pytesseract#164]
**I use Jupyterlab to write a little program:**
"""
import os
os.chdir("F:\\Python\\OCR")
import pytesseract
tesseract_cmd = 'C:/Program Files (x86)/Tesseract-OCR/tesseract.exe'
from PIL import Image
image=Image.open('a.png')
text=pytesseract.image_to_string(image)
"""
**Tesseract part:**
Environmental variable added 
1. Tesseract: C:\Program Files (x86)\Tesseract-OCR
2. Tesseract-Prefix: C:\Program Files (x86)\Tesseract-OCR\tessdata

**Pytesseract part**:
In ~anaconda3\Lib\site-packages\pytesseract\pytesseract.py I changed as following:
'tesseract_cmd = 'C:/Program Files (x86)/Tesseract-OCR/tesseract.exe'

**While error still occurs**:
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pytesseract\pytesseract.py in run_tesseract(input_filename, output_filename_base, extension, lang, config, nice)
    177 
    178     if status_code:
--> 179         raise TesseractError(status_code, get_errors(error_string))
    180 
    181     return True

TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

**Comment by int3l** [comment]
Hi @SheAQ , the tesseract error clearly states that you should set TESSDATA_PREFIX to the parent dir of 'tessdata' :)

Tesseract-Prefix: C:\Program Files (x86)\Tesseract-OCR
