### ISSUE TITLE
ResourceWarning

### ISSUE THREAD

**Issue by flavie-lancereau** [madmaze/pytesseract#165]
Hello,

I have 2 ResourceWarning message when using image_to_data. 
> .local/lib/python3.6/site-packages/pytesseract/pytesseract.py:202: ResourceWarning: unclosed file <_io.BufferedWriter name=4>
  run_tesseract(**kwargs)
.local/lib/python3.6/site-packages/pytesseract/pytesseract.py:202: ResourceWarning: unclosed file <_io.BufferedReader name=5>
  run_tesseract(**kwargs)

code to reproduce:
```
from pytesseract import image_to_data
import warnings

if __name__ == '__main__':
    warnings.filterwarnings('default', category=ResourceWarning)
    img = test.jpg'
    datas = image_to_data(img)
```

pytesseract version: 0.2.5
pillow version: 5.3.0

**Comment by int3l** [comment]
Hi @flavie-lancereau ,
thanks for reporting the issue.
Did you tested this with the latest (master) pytesseract version from github?

**Comment by flavie-lancereau** [comment]
Hello,
sorry haven't try it. Yes it is ok now. 
Regards

**Comment by flavie-lancereau** [comment]
when the new release will be out ?

**Comment by int3l** [comment]
@flavie-lancereau usually it takes one or two weeks after we have the published release in github. This gives us time to test and fix potential problems. I will publish the 0.2.6 today.
