### ISSUE TITLE
Kubuntu shuts down unexpected

### ISSUE THREAD

**Issue by parayamelo** [madmaze/pytesseract#166]
I started working with pytesseract a few days ago. I noticed that all of the sudden, my Kubuntu 18.10 would shut down out of the blue. Today, I saw that this happens when I run pytesseract inside python3. It happened already 4 times. Do you know if this is an issue? 

I am running pytesseract as:

text = pytesseract.image_to_string(img, lang='spa',config='--psm 6')

Thank you.

**Comment by int3l** [comment]
Hi @parayamelo  - can you please test without pytesseract?
Everything that you can run with pytesseract, can be done without it.
So execute the **tesseract** command directly and if you have the same issues, you should ensure that the problems is related to the tesseract code base itself and that it's not a hardware issue on your end.
If that's the case, then please report this to the Tesseract-OCR project issue tracker.
