### ISSUE TITLE
image_to_pdf_or_hocr error: can't find file in /tmp

### ISSUE THREAD

**Issue by rohitbhio** [madmaze/pytesseract#168]
I am using image_to_pdf_or_hocr method to obtain results in HOCR format. When I use this method in macOS or ubuntu 16.04, the method gives hocr output. This method doesn't seem to work when used in RHEL 6.9 or Centos 6.10 and throws below message. 

`Traceback (most recent call last):
  File "test_pytesseract.py", line 25, in <module>
    hocr = pytesseract.image_to_pdf_or_hocr(Image.open(filename), config=config, extension='hocr')
  File "/home/rohit/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 326, in image_to_pdf_or_hocr
    return run_and_get_output(*args)
  File "/home/rohit/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 221, in run_and_get_output
    with open(filename, 'rb') as output_file:
IOError: [Errno 2] No such file or directory: '/tmp/tess_aOwHBL_out.hocr'`

Can we untangle this OS based dependency?

P.S.: I am using tesseract 4.0.0 and pytesseract 0.2.6

**Comment by rohitbhio** [comment]
Closing the issue..

Figured that I didn't have right configs present here - https://github.com/tesseract-ocr/tesseract/tree/master/tessdata

**Comment by int3l** [comment]
Just out of curiosity - which version is used for python and Pillow under this older CentOS/RHEL?

**Comment by rohitbhio** [comment]
I am using latest anaconda distribution of python 2. 

`[rohit@(1320EDGE) /home/rohit] $ python
Python 2.7.15 | packaged by conda-forge | (default, Nov 29 2018, 06:43:57) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'5.3.0'
>>> 
`

**Comment by int3l** [comment]
Cool, I tried with the default python installation 2.6.6 + Pillow 3.4.2 (latest supported version for python 2.6.6), which is ancient and it has the following dependencies:

```bash
yum install -y epel-release python-pip python-devel gcc zlib-devel libjpeg-devel libpng-devel freetype-devel
pip install Pillow==3.4.2
pip install pytesseract
```

**Comment by susuusus** [comment]
Hi I am using tesseract 3.0.2 and it also happening same issue as the thread which image_to_pdf_or_hocr error: can't find file in /tmp. For image_to_string, it is working fine. Anyone has clues on fixing this issue? Thanks

**Comment by PyroSama07** [comment]
> Hi I am using tesseract 3.0.2 and it also happening same issue as the thread which image_to_pdf_or_hocr error: can't find file in /tmp. For image_to_string, it is working fine. Anyone has clues on fixing this issue? Thanks
I am also facing same issue, did you find the solution?
