### ISSUE TITLE
Openmp usage

### ISSUE THREAD

**Issue by mooncrater31** [madmaze/pytesseract#169]
I want `tesseract` to use only a single processor, as I am trying to run parallel `tesseract` calls. By default, `tesseract` will use 4 threads, which I don't want in this case. So, the only option is to do `OPENMP_THREAD_LIMIT=1 tesseract <input-image> <output>` on the command line. But how do I specify this constraint in the case of `pytesseract`?

**Comment by mooncrater31** [comment]
So you're saying that I should run the python program as `OPENMP_THREAD_LIMIT=1 python myprog.py`? Or if I am running the interpreter, then `OPENMP_THREAD_LIMIT=1 python` and then calling `pytesseract`?

**Comment by int3l** [comment]
Yes,
