### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by madmaze** [madmaze/pytesseract#17]
We need some basic unit tests to ensure when changes are made that we still support the same functionality.

**Comment by madmaze** [comment]
starting some changes on the dev branch

**Comment by int3l** [comment]
Details for initial unit tests in PR #42.

**Comment by johnthagen** [comment]
Having some unit tests would also help maintain which Python versions are actually supported (by ensuring they at least import and run on those versions).

**Comment by johnthagen** [comment]
#42 was closed, but it doesn't seem like it was ever resurrected?

**Comment by int3l** [comment]
Hi @johnthagen which part of it :D
I remember fixing the Resource Warning and the leaking descriptors.
If you mean the utf-8 thing, we can do this in separate PR/issue.

**Comment by johnthagen** [comment]
I guess I meant having unit tests in general.

**Comment by nok** [comment]
JFYI, I also added a PR https://github.com/madmaze/pytesseract/pull/215 with a bunch of unit tests.
