### ISSUE TITLE
The tessdata trained using Tesseract 4.0alpha's LSTM engine reports an error.

### ISSUE THREAD

**Issue by Myth2018** [madmaze/pytesseract#170]
Details as follows：
    run_tesseract(**kwargs)
    return run_and_get_output(*args)
    raise TesseractError(status_code, get_errors(error_string))
   pytesseract.pytesseract.TesseractError: (3221225477, '')
The training set is from tessdata_best.
It name is chi_sim.traineddata.
Who knows why?

**Comment by int3l** [comment]
Hi @Myth2018 , this is Tesseract specific error and is not pytesseract issue. You should forward this question to the tesseract issue tracker. Most probably Tesseract process itself crashed with reason ACCESS_VIOLATION.

**Comment by int3l** [comment]
Possible solution: You can try to install the 32 bit version of Tesseract if you have the 64 bit at the moment or vice versa.
