### ISSUE TITLE
The purpose of discard and replace the alpha channel

### ISSUE THREAD

**Issue by makcedward** [madmaze/pytesseract#173]
During identify speed bottleneck, I found that text result is inconsistent when passing file and Image.Image format. 

If file path is passed, it will pass to tesseract directly. Otherwise, image preparation will be done. Found that text result is better if passing file path rather than image. Text results are same if comment out the following code.

```
if 'A' in image.getbands():
        # discard and replace the alpha channel with white background
        background = Image.new(RGB_MODE, image.size, (255, 255, 255))
        background.paste(image, (0, 0), image)
        image = background
```

Would you mind advising the purpose of this code snippet? 

Thanks.
Edward

**Comment by int3l** [comment]
Hi @makcedward, my guess is that this is legacy related code.
I suppose that the older tesseract versions doesn't support the alpha channel.
You can check the closed issues or git blame if you want to track the particular reasons for adding this block of code. We can make it optional if the performance impact is noticeable (which is the case, I believe).
Btw what is your version of tesseract?

**Comment by makcedward** [comment]
@int3l 
I am using v4.x version.

**Comment by int3l** [comment]
I see, we still can make the discarding optional.

**Comment by makcedward** [comment]
@int3l 
Thanks.

**Comment by int3l** [comment]
We actually have a way to skip the alpha channel discarding, by just passing the image file path as string and not using the Pillow Image object.
