### ISSUE TITLE
Stuck on image_to_string with greyscale image

### ISSUE THREAD

**Issue by SyedMuhammadAli** [madmaze/pytesseract#175]
I have an image which unfortunately I can not share. image_to_string gets stuck indefinitely (hours) when on that image.

Upon debugging, I noted that the problem happens in pytesseract/pytesseract.py line: 174 where proc.wait() is in a deadlock state. Passing a timeout parameter did the tick during debugging.

Some background of the image:
====================

> Image specs:
> Format: JPG
> Contents: 3d model screenshot
> Dim: 1003 x 904
> H/V DPI: 96dpi
> Bit depth: 24

Converted to greyscale with cv2 module

Output when replicated on command line:
===========================

> C:\Users\foo\Desktop>tesseract messigray.jpg test.txt -l eng --oem 0 --psm 12
> Tesseract Open Source OCR Engine v4.0.0.20181030 with Leptonica
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 111
> OSD: Weak margin (0.82) for 3618 blob text block, but using orientation anyway: 0
> Warning:guessing pitch as xheight on row 1, block 4
> Warning:guessing pitch as xheight on row 1, block 54
> Warning:guessing pitch as xheight on row 1, block 62
> Warning:guessing pitch as xheight on row 1, block 88
> Warning:guessing pitch as xheight on row 1, block 114
> Warning:guessing pitch as xheight on row 1, block 144
> Warning:guessing pitch as xheight on row 1, block 148
> Warning:guessing pitch as xheight on row 1, block 152
> Warning:guessing pitch as xheight on row 1, block 157
> Warning:guessing pitch as xheight on row 1, block 171
> Warning:guessing pitch as xheight on row 1, block 185
> Warning:guessing pitch as xheight on row 1, block 188
> Warning:guessing pitch as xheight on row 1, block 196
> Warning:guessing pitch as xheight on row 1, block 197
> Warning:guessing pitch as xheight on row 1, block 199
> Warning:guessing pitch as xheight on row 1, block 202
> Warning:guessing pitch as xheight on row 1, block 206
> Warning:guessing pitch as xheight on row 1, block 208
> Warning:guessing pitch as xheight on row 1, block 212
> Warning:guessing pitch as xheight on row 1, block 215
> Warning:guessing pitch as xheight on row 1, block 216
> Warning:guessing pitch as xheight on row 1, block 223
> Warning:guessing pitch as xheight on row 1, block 234
> Warning:guessing pitch as xheight on row 1, block 236
> Warning:guessing pitch as xheight on row 1, block 238
> Warning:guessing pitch as xheight on row 1, block 243
> Warning:guessing pitch as xheight on row 1, block 244
> Warning:guessing pitch as xheight on row 1, block 249
> Warning:guessing pitch as xheight on row 1, block 252
> Warning:guessing pitch as xheight on row 1, block 260
> Warning:guessing pitch as xheight on row 1, block 261
> Warning:guessing pitch as xheight on row 1, block 266
> Warning:guessing pitch as xheight on row 1, block 269
> Warning:guessing pitch as xheight on row 1, block 270
> Warning:guessing pitch as xheight on row 1, block 277
> Warning:guessing pitch as xheight on row 1, block 282
> Warning:guessing pitch as xheight on row 1, block 283
> Warning:guessing pitch as xheight on row 1, block 287
> Warning:guessing pitch as xheight on row 1, block 292
> Warning:guessing pitch as xheight on row 1, block 295
> Warning:guessing pitch as xheight on row 1, block 302
> Warning:guessing pitch as xheight on row 1, block 303
> Warning:guessing pitch as xheight on row 1, block 309
> Warning:guessing pitch as xheight on row 1, block 312
> Warning:guessing pitch as xheight on row 1, block 314
> Warning:guessing pitch as xheight on row 1, block 317
> Warning:guessing pitch as xheight on row 1, block 320
> Warning:guessing pitch as xheight on row 1, block 325
> Warning:guessing pitch as xheight on row 1, block 327
> Warning:guessing pitch as xheight on row 1, block 328
> Warning:guessing pitch as xheight on row 1, block 330
> Warning:guessing pitch as xheight on row 1, block 341
> Warning:guessing pitch as xheight on row 1, block 348
> Warning:guessing pitch as xheight on row 1, block 351
> Warning:guessing pitch as xheight on row 1, block 357
> Warning:guessing pitch as xheight on row 1, block 367
> Warning:guessing pitch as xheight on row 1, block 378
> Warning:guessing pitch as xheight on row 1, block 382
> Warning:guessing pitch as xheight on row 1, block 383
> Warning:guessing pitch as xheight on row 1, block 399
> Warning:guessing pitch as xheight on row 1, block 418
> Warning:guessing pitch as xheight on row 1, block 419
> Warning:guessing pitch as xheight on row 1, block 441
> Warning:guessing pitch as xheight on row 1, block 448
> Warning:guessing pitch as xheight on row 1, block 462
> Warning:guessing pitch as xheight on row 1, block 477
> Warning:guessing pitch as xheight on row 1, block 495
> Warning:guessing pitch as xheight on row 1, block 496
> Warning:guessing pitch as xheight on row 1, block 498
> Warning:guessing pitch as xheight on row 1, block 499
> Warning:guessing pitch as xheight on row 1, block 508
> Warning:guessing pitch as xheight on row 1, block 511
> Warning:guessing pitch as xheight on row 1, block 513
> Warning:guessing pitch as xheight on row 1, block 520
> Warning:guessing pitch as xheight on row 1, block 536
> Warning:guessing pitch as xheight on row 1, block 538
> Warning:guessing pitch as xheight on row 1, block 563
> Warning:guessing pitch as xheight on row 1, block 568
> Warning:guessing pitch as xheight on row 1, block 569
> Warning:guessing pitch as xheight on row 1, block 586
> Warning:guessing pitch as xheight on row 1, block 589
> Warning:guessing pitch as xheight on row 1, block 591
> Warning:guessing pitch as xheight on row 1, block 592
> Warning:guessing pitch as xheight on row 1, block 599
> Warning:guessing pitch as xheight on row 1, block 605
> Warning:guessing pitch as xheight on row 1, block 606
> Warning:guessing pitch as xheight on row 1, block 607
> Warning:guessing pitch as xheight on row 1, block 611
> Warning:guessing pitch as xheight on row 1, block 630
> Warning:guessing pitch as xheight on row 1, block 633
> Warning:guessing pitch as xheight on row 1, block 656
> Warning:guessing pitch as xheight on row 1, block 657
> Warning:guessing pitch as xheight on row 1, block 658
> Warning:guessing pitch as xheight on row 1, block 665
> Warning:guessing pitch as xheight on row 1, block 674
> Warning:guessing pitch as xheight on row 1, block 675
> Warning:guessing pitch as xheight on row 1, block 678
> Warning:guessing pitch as xheight on row 1, block 685
> Warning:guessing pitch as xheight on row 1, block 693
> Warning:guessing pitch as xheight on row 1, block 694
> Warning:guessing pitch as xheight on row 1, block 695
> Warning:guessing pitch as xheight on row 1, block 697
> Warning:guessing pitch as xheight on row 1, block 699
> Warning:guessing pitch as xheight on row 1, block 718

(Small lag but dos returns to prompt w/o problems)

Summary:
=======
Pytesseract never returns from the proc.wait() command. Command line for same options works fine with warnings.

Link to [Popen.wait](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait) notes reference:
=======================

> Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

> Note The function is implemented using a busy loop (non-blocking call and short sleeps). Use the asyncio module for an asynchronous wait: see asyncio.create_subprocess_exec.

**Comment by int3l** [comment]
Hello @SyedMuhammadAli and thanks for reporting the issue.
