### ISSUE TITLE
FileNotFoundError while use image_to_pdf_or_hocr

### ISSUE THREAD

**Issue by nathan30** [madmaze/pytesseract#180]
The img I give as input of pytesseract.image_to_pdf_or_hocr is something like : /home/edissyum/opencapture/data/tmp/tmp-0.jpg
But here is the error :

Traceback (most recent call last):
File "src/main.py", line 80, in
process(args, path, Log, Separator, Config, Image, Ocr, Locale, WebService)
File "/home/edissyum/opencapture/src/process/OCForMaarch.py", line 61, in process
Ocr.generate_searchable_pdf(file, Image, Config)
File "/home/edissyum/opencapture/src/classes/PyTesseract.py", line 43, in generate_searchable_pdf
extension='pdf'
File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 325, in image_to_pdf_or_hocr
return run_and_get_output(*args)
File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 220, in run_and_get_output
with open(filename, 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_yy447kdg_out.pdf'

I'm currently using a compiled version of Tesseract v4.0.0

Thanks in advance

**Comment by int3l** [comment]
Did you tested directly with tesseract and this particular image + pdf config?
Most probably tesseract didn't create output file.

**Comment by nathan30** [comment]
> Did you tested directly with tesseract and this particular image + pdf config?
> Most probably tesseract didn't create output file.

I finally found the issue, I forget to install :
sudo apt install libtesseract-dev

**Comment by susuusus** [comment]
Hi I am using tesseract 3.0.2 and it also happening same issue as the thread which image_to_pdf_or_hocr error: can't find file in /tmp. For image_to_string, it is working fine. Btw, I am using windows. Anyone has clues on fixing this issue? Thanks

**Comment by int3l** [comment]
@susuusus try a newer version of tesseract - 3.5 or 4.0+

**Comment by susuusus** [comment]
> @susuusus try a newer version of tesseract - 3.5 or 4.0+

@int3l Thanks for swift reply. I am only allowed to use 3.0.2 so far. Is there any way I can use image_to_pdf_or_hocr under this version.

**Comment by int3l** [comment]
Unfortunately Tesseract 3.0.x is very old version, which is not supported by pytesseract.
