### ISSUE TITLE
Pulling images from urls

### ISSUE THREAD

**Issue by hughhhh** [madmaze/pytesseract#182]
It would be dope if would pull images str8 from a url vs. having to have a local download.

```
Image.open_url('https://s3bucket.com/example.jpg')
```

**Comment by tjtanjin** [comment]
@hughhhh **Image.open** is actually from the Python Imaging Library. For pulling images directly from a URL, there's a quick way to do so like this:

```
from urllib.request import urlopen
Image.open(urlopen('https://s3bucket.com/example.jpg'))
```
