### ISSUE TITLE
TESSDATA_PREFIX

### ISSUE THREAD

**Issue by nathan30** [madmaze/pytesseract#183]
Hi, 

I have the following error while running my python program in a Debian 9.8 : 

pytesseract.pytesseract.TesseractError: (1, 'Error opening data file ./fra.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language 'fra' Tesseract couln't load any languages! Could not initialize tesseract.')

I did this : 

> export TESSDATA_PREFIX=/usr/share/tesseract-ocr/

but It's not working at all. I tried to add it to PATH, into ~/.profile file but not working :/

Any ideas ?

Thanks in advance

NOTICE : Tesseract was compile from source to have the v4.0.0 version using : 

> git clone -b4.0.0 https://github.com/tesseract-ocr/tesseract
> cd tesseract
> mkdir build && cd build
> cmake .. && make
> make install

**Comment by int3l** [comment]
Try this:
```python
# Example config: r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata"'
# It's important to add double quotes around the dir path.
tessdata_dir_config = r'--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
pytesseract.image_to_string(image, lang='chi_sim', config=tessdata_dir_config)
```

Also check the README for additional info.

**Comment by Linkding** [comment]
> Try this:
> 
> ```python
> # Example config: r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata"'
> # It's important to add double quotes around the dir path.
> tessdata_dir_config = r'--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
> pytesseract.image_to_string(image, lang='chi_sim', config=tessdata_dir_config)
> ```
> 
> Also check the README for additional info.

env :mac 10.13.6
It isn't work
```
# -*- coding: utf-8 -*-
import pytesseract
from PIL import Image

img = Image.open('img/peihao.png')
tessdata_dir_config = r'--tessdata-dir "/usr/local/Cellar/tesseract/4.0.0_1/share/tessdata/"'
content = pytesseract.image_to_string(img,lang='chi_sim',config=tessdata_dir_config)
print (content)
```
the error 
```
raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file /usr/local/Cellar/tesseract/4.0.0_1/share/tessdata/chi_sim.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'chi_sim\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
```
so, i check the file Privilege ,/usr/local/Cellar/tesseract/4.0.0_1/share/tessdata/chi_sim.traineddata  is 644

**Comment by int3l** [comment]
So it was a permission issue or?
Do you get the same error, when you use tesseract itself?
If so, then maybe it is something related to MacOS and tesseract.

**Comment by nathan30** [comment]
I finally to manage to find my error. I'll try to explain clearly : 
I create a system service using a bash script to launch. The script launch a worker to retrieve the jobs when my Python script is launched. When I export the TESSDATA_PREFIX in my shell, it was not working. But put it into my bash script makes it work

**Comment by int3l** [comment]
I see :) So it was a namespace/scope problem. Thanks for sharing the information!
