### ISSUE TITLE
pytesseract reduced image quality

### ISSUE THREAD

**Issue by che220** [madmaze/pytesseract#184]
It looks like pytesseract by saving the images into a temporary file reduces image quality, therefore tesseract OCR does not work well. This can be demonstrated by the following experiment:

1. Run an image full of text thru pytesseract
2. Run the same image thru tesseract on the command line directly

The later usually yields more text.

**Comment by int3l** [comment]
Did you tried to pass the file image path as string?
This way you will bypass some of the internal routines/conversions of pytesseract.
