### ISSUE TITLE
Converting to tsv does not give same result as command line output

### ISSUE THREAD

**Issue by RAJAT--PALIWAL** [madmaze/pytesseract#185]
`pytesseract.image_to_data(img, output_type=pyt.Output.DATAFRAME)`
does not provides same output as
`tesseract imgname output tsv`

How to fix this?

**Comment by int3l** [comment]
Hi @RAJAT--PALIWAL,
Did you tried to pass the file image path as string?
This way you will bypass some of the internal routines/conversions of pytesseract.
