### ISSUE TITLE
Fix README to not claim tesseract-ocr only supports tiff and bmp

### ISSUE THREAD

**Issue by jxu** [madmaze/pytesseract#188]
The README has the claim 

> tesseract-ocr by default only supports tiff and bmp

This is not true since tesseract uses Leptonica, which supports "JPEG, PNG, TIFF, BMP, PNM GIF, and WEBP formats" http://tpgit.github.io/UnOfficialLeptDocs/leptonica/README.html#image-i-o

**Comment by int3l** [comment]
Thanks for reporting.
