### ISSUE TITLE
Enable Travis CI for project

### ISSUE THREAD

**Issue by johnthagen** [madmaze/pytesseract#190]
@int3l @madmaze Could you enable Travis CI build for this project at https://travis-ci.org/madmaze/pytesseract

This will allow us to automate newly added testing (like #189) for commits and pull requests.

Subtask of #17.

**Comment by int3l** [comment]
I am not sure if Travis support tesseract-ocr package with newer versions like 4.0, but I guess that we can try.

**Comment by johnthagen** [comment]
Good point. I was hoping we could get at least some version new enough to do some kind of smoke testing.

Worst case we could try to build tesseract? That would probably not be fun.

In any case, at least `flake8` does syntax checking as well, which is a lot better than nothing.

**Comment by johnthagen** [comment]
Xenial has `tesseract` 3.04: https://packages.ubuntu.com/xenial/tesseract-ocr

Hopefully that is new enough to at least test basic interop with it.

Travis has yet to add support for Bionic (18.04): https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270

**Comment by madmaze** [comment]
done, let me know if I need to tweak any settings
