### ISSUE TITLE
Remove images from being included in the bundled package

### ISSUE THREAD

**Issue by johnthagen** [madmaze/pytesseract#193]
In [`MANIFEST.in`](https://github.com/madmaze/pytesseract/blob/master/MANIFEST.in#L1-2):

```
recursive-include src *.jpg
recursive-include src *.png
```

These images aren't needed for the actual operation of the package, but are included so they take up extra disk space for users. It seems like if anything, we'd want to move these to a `tests` folder and not include them in the distributed package.

Any reason not to remove these from the package?

**Comment by int3l** [comment]
We can definitively move them into a separate folder and outside of the package.
