### ISSUE TITLE
cannot find tesseract file when using pytesseract

### ISSUE THREAD

**Issue by lordpeter003** [madmaze/pytesseract#196]
I've installed tesseract and pytesseract, and I keep getting error messages
<redacted_image_to_hide_username>
even after I changed the path of "tesseract_cmd" in pytesseract.py, reinstalled tesseract using homebrew, and added the line "pytesseract.pytesseract.tesseract_cmd = '/usr/local/bin/tesseract'" in my python file. I can get the version of my pytesseract using line "print(pytesseract.get_tesseract_version())". Since I can acquire the version of pytesseract, I don't know why the path issue still exists. Thanks in advance for anyone who can help!

**Comment by lordpeter003** [comment]
btw I am using a Mac

**Comment by int3l** [comment]
Hi @lordpeter003 ,
can you get the tesseract path via this command:  `which tesseract` ?

**Comment by lordpeter003** [comment]
I can, and this is the exact path I am using for "tesseract_cmd="
<img width="321" alt="Screen Shot 2019-05-30 at 10 20 56 AM" src="https://user-images.githubusercontent.com/43424602/58603796-ab42e680-82c4-11e9-9cf7-af9534fc7a99.png">

**Comment by int3l** [comment]
For some reason, [Line 184](https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L184) raises OSError exception.
Can you remove the try/except block around line 184, so you can get better trace back.

**Comment by lordpeter003** [comment]
I tried to remove the entire block, but apparently there's variable in there needed for the later statements, so it just throwed a "'proc' not defined", 
<img width="847" alt="Screen Shot 2019-05-31 at 8 47 01 AM" src="https://user-images.githubusercontent.com/43424602/58674192-426d7400-8381-11e9-8987-c4f3982abd59.png">
and when I tried to keep that particular line that defines the variable, the error message was pretty much the same
<img width="581" alt="Screen Shot 2019-05-31 at 8 49 17 AM" src="https://user-images.githubusercontent.com/43424602/58674239-7183e580-8381-11e9-86a6-45979f092a6a.png">
Here's the function that contains line 183-186 try/except statement
<img width="562" alt="Screen Shot 2019-05-31 at 8 56 19 AM" src="https://user-images.githubusercontent.com/43424602/58674348-fcfd7680-8381-11e9-8bf7-fe823bcd2fa1.png">

**Comment by int3l** [comment]
Oh, sorry :) you need to updated to the latest pytesseract version.
Read the instructions in the README for how to do this.

**Comment by int3l** [comment]
If you still have the same problem, feel free to reopen.

**Comment by lordpeter003** [comment]
I installed the latest version of pytesseract now(version 0.2.7), and the problem still exists. 
<img width="617" alt="Screen Shot 2019-06-03 at 8 42 18 AM" src="https://user-images.githubusercontent.com/43424602/58769714-29acca80-85dc-11e9-92f0-391aebcb66cd.png">
Is there anything I'm missing right now? The error messages are still the same.

**Comment by int3l** [comment]
Hm, then for sure, somehow you don't have tesseract in your PATH.
You should try to debug this. For example, check what is your current PATH from within the python env.
```python
import sys
print(sys.path)
```
and compare both paths with the output of the `which tesseract` command.

**Comment by lordpeter003** [comment]
Ok I got these paths, I'm sorry I'm just throwing screenshots left and right, I'm pretty new to all these :(
<img width="1010" alt="Screen Shot 2019-06-03 at 9 47 55 AM" src="https://user-images.githubusercontent.com/43424602/58771076-eacf4280-85e4-11e9-802e-75b1c36391e5.png">
<img width="1023" alt="Screen Shot 2019-06-03 at 9 48 09 AM" src="https://user-images.githubusercontent.com/43424602/58771077-eacf4280-85e4-11e9-9b3e-875b8690296d.png">
<img width="938" alt="Screen Shot 2019-06-03 at 9 48 21 AM" src="https://user-images.githubusercontent.com/43424602/58771078-eb67d900-85e4-11e9-8bec-f50e3f0abeda.png">
Btw I got tesseract working by writing my own image_to_string function, here's the code
import os
import subporcess
def image_to_string(img, cleanup=True, plus=''):
    subprocess.check_output('tesseract ' + img + ' ' + img + ' ' + plus, shell=True)
    text = ''
    with open(img + '.txt', 'r') as f:
        text = f.read().strip()
    if cleanup:
        os.remove(img + '.txt')
    return text
But this does not fix the problem of pytesseract though...so I guess we should still continue debugging?

**Comment by int3l** [comment]
Check if you have the `/usr/local/bin` in your system PATH.
```python
import os
print(os.environ['PATH'])
```

**Comment by lordpeter003** [comment]
I think I do
`/Users/peterhuang/venv/bin:/usr/local/bin:/usr/local/bin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`

**Comment by int3l** [comment]
I am not sure what is going on then.
Can you try to print `cmd_args` on line 184?

**Comment by lordpeter003** [comment]
Here's the result
`['/usr/local/bin/tesseract', '/var/folders/qx/9zsk3gh52n15grc4k362kp080000gn/T/tess_5au84ejz.PNG', '/var/folders/qx/9zsk3gh52n15grc4k362kp080000gn/T/tess_5au84ejz_out', 'txt']`

**Comment by int3l** [comment]
It looks perfectly fine to me.
Can you change /usr/local/bin/tesseract back to tesseract?
Since you have it in your system PATH, it should work, just like in your example script from above.

**Comment by lordpeter003** [comment]
Nah I changed it back to 'tesseract' and it still does not work :(

**Comment by int3l** [comment]
Hm maybe it is the subprocess_args setup?
Try to remove the `, **subprocess_args()` part from line 184.

**Comment by lordpeter003** [comment]
OK now there's only one error message left
<img width="848" alt="Screen Shot 2019-06-03 at 11 40 23 AM" src="https://user-images.githubusercontent.com/43424602/58774536-80260300-85f4-11e9-979b-aa06ca994a0e.png">

**Comment by int3l** [comment]
Hmmm, let me research something.
The last error is not relevant. That subprocess_args setup is messing up something with the system PATH on MacOS.

**Comment by int3l** [comment]
Can you try to revert the last change with the subprocess_args?
But after that, search for the `'env': os.environ` line and remove it from the `kwargs` dictionary.

**Comment by lordpeter003** [comment]
When I reverted the change and removed the 'env', the original two error messages 'cannot find tesseract' appeared again, and when I keep and the change and removed 'env', the last error message of "'NoneType object' has no attribute 'read'"appeared.

**Comment by int3l** [comment]
I don't have Mac OS development VM at the moment, so I can't really debug this.
Is it possible for you to test your script in the terminal instead from PyCharm.

**Comment by lordpeter003** [comment]
When I tried to run on terminal, basically all of my imports does not work.
<img width="754" alt="Screen Shot 2019-06-03 at 12 30 08 PM" src="https://user-images.githubusercontent.com/43424602/58776087-60460d80-85fb-11e9-9040-d8e99a0aefda.png">

**Comment by int3l** [comment]
Yes, you should activate your virtual environment first.
Anyway, maybe something in your PyCharm setup affects the PATH manipulations.

**Comment by lordpeter003** [comment]
This is the configuration I'm using right now for PyCharm
<img width="737" alt="Screen Shot 2019-06-03 at 12 38 30 PM" src="https://user-images.githubusercontent.com/43424602/58776304-9c2da280-85fc-11e9-9c13-5d2b3232400f.png">
I'll try to explore my PyCharm setup further to see if anything's off

**Comment by int3l** [comment]
You can try the option `Emulate terminal in output console`.

**Comment by int3l** [comment]
The other possibility is to make alias of `/usr/local/bin/tesseract` to your system PATH `/usr/bin/tesseract`.
Because what I can see from the research - you don't have access to the current user PATH (the IDE is restricted to the system PATH only - for some strange reason).

**Comment by int3l** [comment]
Closing this one as not pytesseract specific issue. Feel free to reopen/comment if this is not the case.
