### ISSUE TITLE
ResourceWarning

### ISSUE THREAD

**Issue by Kedrigern** [madmaze/pytesseract#20]
I am using pytesseract in Python3 code:
```python
#!/usr/bin/env python3

from PIL import Image
import pytesseract

file = "file.txt"
text = tess(Image.open(file), lang=eng)
```
Everythink work fine, but when I wrote first unittest I get following warning:

```
/usr/lib/python3.4/site-packages/pytesseract/pytesseract.py:161: ResourceWarning: unclosed file <_io.BufferedReader name=4>  config=config)
```

Version: 0.1.6, unittesting via std `unittest` module.

**Comment by madmaze** [comment]
This warning should be fixed by the aforementioned commit, but PIL still throws a warning, but I think that is documented here: https://github.com/python-pillow/Pillow/issues/835
