### ISSUE TITLE
image_to_string hangs if config=None

### ISSUE THREAD

**Issue by jxu** [madmaze/pytesseract#201]
pytesseract.image_to_string(img, config=None)

Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Tesseract LooseVersion ('4.0.0.20190314')
Pytesseract v0.2.7

**Comment by int3l** [comment]
As per the documentation:
`config String, Any additional configurations as a string, ex: config='--psm 6'`
So please use empty string or omit the config flag if you don't want to specify additional configuration.

**Comment by jxu** [comment]
Empty string is exactly what I tried next which works. Just this is unexpected behavior.

**Comment by int3l** [comment]
Yep: https://bugs.python.org/issue27775
If you want, we can add check about it in the code, but it seems that this is intended behavior.
