### ISSUE TITLE
Unexpected behavior (bug?) while using `pytesseract.image_to_string`

### ISSUE THREAD

**Issue by rsomani95** [madmaze/pytesseract#203]
I'm cropping an image and then passing it into `pytesseract.image_to_string`

This is `img_original`
![frame667](https://user-images.githubusercontent.com/17111474/59097660-c1dbe400-893b-11e9-874a-9788b92a1047.jpg)

```python
from PIL import Image
(x1, y1, x2, y2) = (125, 38, 322, 105)
img_scoreboard = img_original.crop(x1, y1, x2, y2)
```

`img_scoreboard`:
![test](https://user-images.githubusercontent.com/17111474/59097995-ac1aee80-893c-11e9-9770-e5b4e5d3098a.jpg)

When I pass the cropped image directly into `pytesseract`, it gives me an incorrect output:
```python
config = ("-l eng --oem 1 --psm 6")
pytesseract.image_to_string(img_scoreboard, config=config)

# Output --> 'MURRAY |0 4\ni2)3,11 a'
```

Whereas if I use either one of the following 3 options, they all give me the correct output:
```python
temp_img = "img_scoreboard.jpg"
pytesseract.image_to_string(temp_img, config=config)
pytesseract.image_to_string("img_scoreboard.jpg", config=config)
pytesseract.image_to_string(Image.open"img_scoreboard.jpg", config=config)

# Outputs:
# 'MURRAY | 0 4\nFEDERER 1 5'
# 'MURRAY | 0 4\nFEDERER 1 5'
# 'MURRAY | 0 4\nFEDERER 1 5'
```

Is this normal?
This means that if you're cropping an image, it needs to be saved to disk and reread while being passed to `pytesseract.image_to_string` ?

Thanks.

**Comment by int3l** [comment]
If you pass the name of the image as string, pytesseract doesn't do any additional processing of the image and uses it as is, while invoking tesseract.

But if you pass python image object, there is some additional processing - check the [save_image source code](https://github.com/madmaze/pytesseract/blob/0e8a21b125b206b0eaf20f15e88401ff9af5a812/src/pytesseract.py#L156) for more info. Most of the additional processing is done, so tesseract can accept the input image without returning errors.

**Comment by int3l** [comment]
Interesting, I found that when you call the **Image.crop** method on the test image, then the **Image.format** property gets unset...

**Comment by int3l** [comment]
@rsomani95 please try to set the [Image.format](https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.format) to the same format as the one of img_original object and try again to see if you get consistent result.

**Comment by rsomani95** [comment]
> Interesting, I found out that when you call the Image.crop method on the test image, then the Image.format property gets unset...

Good catch. 

I tried resetting it three different ways...
```python
img_scoreboard.format = img_original.format   # 1
img_scoreboard.format = img_original.format() # 2
img_scoreboard.format = '.jpg'                # 3
```
... but both gave me a scrambled output.

**Comment by int3l** [comment]
What is your version of tesseract?
I will try to debug locally.

**Comment by rsomani95** [comment]
```
tesseract 4.0.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```

**Comment by int3l** [comment]
Yep, so if you set the Image.format properly to the source image, it seems to work correctly.
In that case I will change the logic of pytesseract to require the Image.format and raise error if it's not set.
