### ISSUE TITLE
Cant make user-words work

### ISSUE THREAD

**Issue by alejandrofm** [madmaze/pytesseract#206]
Hi I'm using pytesseract without problems, using Latin best.
This works great:
text=pytesseract.image_to_string(imagen, lang='Latin')

Now I want to improve some important words that sometimes get wrongly recognised, I added along the Latin.traineddata a Latin.user-words file with only this words:
Monotributista,
monotributista,
Monotributista
monotributista

The word currently detected is:
Nfonotributista,

And executed it with this config, throws no error:
text=pytesseract.image_to_string(image, lang='Latin', config='--user-words Latin.user-words')

But the word doesn't get corrected, am I doing something wrong? is 2 letter difference a lot to this algorithm? I couldn't find much documentation or similar cases.

Thank you!

**Comment by int3l** [comment]
Did you tried to run tesseract itself with this options?
If there is an issue with pytesseract itself, it will be with the usage order of the options arguments.

```
Usage:
  tesseract --help | --help-extra | --version
  tesseract --list-langs
  tesseract imagename outputbase [options...] [configfile...]
```

I found the following related issues: tesseract-ocr/tesseract#1538 and tesseract-ocr/tesseract#403

**Comment by int3l** [comment]
No feedback from user. Feel free to reopen.

**Comment by jtlz2** [comment]
@alejandrofm Any luck on this?

**Comment by alejandrofm** [comment]
Apparently it doesnt work with the last version of Tesseract using LSTM, so I gave up on this until it's reimplemented by tesseract

**Comment by choogiesaur** [comment]
@alejandrofm - have you found a resolution yet using recent (lstm) tesseract versions?

**Comment by alejandrofm** [comment]
Sorry @choogiesaur I'm no longer working in the project that uses tesseract, so no new tests since that time.
