### ISSUE TITLE
bug importing tesseract

### ISSUE THREAD

**Issue by ggdhines** [madmaze/pytesseract#21]
when I do import tesseract I get
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/tesseract.py", line 28, in <module>
    _tesseract = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/tesseract.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tesseract', fp, pathname, description)
ImportError: /usr/lib/python2.7/dist-packages/_tesseract.x86_64-linux-gnu.so: undefined symbol: gplotSimpleXY1

**Comment by ggdhines** [comment]
Came across this:
https://code.google.com/p/tesseract-ocr/issues/detail?id=547
which suggests setting:
export LD_LIBRARY_PATH=$LD_LIBRARAY_PATH:{path_to_your_tesseract_install}/lib
but I don't have a lib directory in my tesseract installation:
~/tesseract-ocr$ find . -type d -name 'lib' returns nothing

**Comment by madmaze** [comment]
I think you may be using a different library, perhaps python_tesseract?
