### ISSUE TITLE
specify the characters tesserect outputs

### ISSUE THREAD

**Issue by kylefoley76** [madmaze/pytesseract#212]
I'm trying to figure out how to build this config file that is talked about here:
https://stackoverflow.com/questions/44619077/pytesseract-ocr-multiple-config-options

In addition to the characters a-z, A-Z and 0-9 and the other usual characters I want to add: ḥ ṯ and a few others.  I can't figure out where to put the config file.

**Comment by kylefoley76** [comment]
Ok, I tried this syntax
str4 = pytesseract.image_to_string(Image.open(str3),
    config='-c tessedit_char_whitelist=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.,;-(){}[]ḥ')

Although I didn't get an error message my output did not change.  It didn't recognize the ḥ character and it also outputted characters such as ? and #

**Comment by kylefoley76** [comment]
Never mind, looks like they removed the feature in version 4.0
https://github.com/tesseract-ocr/tesseract/issues/751

Can't imagine why they did that. Horrible decision

**Comment by grumd** [comment]
@kylefoley76 this feature works for me in Tesseract 5.0.0 (windows binaries here https://github.com/UB-Mannheim/tesseract/wiki)
