### ISSUE TITLE
Bbox position of image_to_string lines

### ISSUE THREAD

**Issue by amundv** [madmaze/pytesseract#213]
Is there a simple way to get the bounding box of the lines found by ```image_to_string``` method?

**Comment by int3l** [comment]
There is a community contributed function `image_to_boxes` - please take a look at the README documentation for more details. It might be enough for your case or at least you can check the code and make your own custom implementation.

**Comment by int3l** [comment]
Closing this one, feel free to reopen if you have any problems or open a new one.
