### ISSUE TITLE
SetRectangle function

### ISSUE THREAD

**Issue by bolatk** [madmaze/pytesseract#219]
How to restrict recognition to a sub-rectangle of the image or pdf? E.g. in native C++ API:
`api->SetRectangle(30, 86, 590, 100);`

**Comment by nok** [comment]
Hello @bolatk ,

one possibility is to [crop](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop) the image:

```python
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

im = Image.open(image_path)
# width, height = im.size

left = 30
top = 86
right = left + 590
bottom = top + 100

cropped_im = im.crop((left, top, right, bottom))

print(pytesseract.image_to_string(cropped_im ))
```

**Comment by int3l** [comment]
Feel free to reopen if you have additional issues.
