### ISSUE TITLE
Install pytesseract with conda

### ISSUE THREAD

**Issue by adbeda** [madmaze/pytesseract#222]
I recently brought pytesseract to the Anaconda community through the conda-forge channel. The tool can now be installed with:
 
    conda install -c conda-forge pytesseract

cheers!

**Comment by int3l** [comment]
Hi @adbeda and thank you for your contribution and community support!
As far as I understand, conda-forge provides automated way of publishing the package, as soon as it is available on GitHub, right? If that's case and if you want, we can add the relevant information about the conda support in the README?

And please let me know if you don't mind to add you in the CONTRIBUTORS section.

**Comment by adbeda** [comment]
@int3l thanks for getting in touch. Yes, Conda-forge updates its end of the package as soon as its available on GitHub. Earlier today, the bot create a PR for v0.2.9, which I merged to update, accordingly. 

I'm glad I was able to help on this and I don't mind being added as a contributor. I love collaborating in the Open Source community. 

Also, if you're interested, you can add yourself as the maintainer of the package on conda-forge by simply adding [your github user](https://github.com/conda-forge/pytesseract-feedstock/blob/master/recipe/meta.yaml#L55) and creating a PR. It would give also access to merge any update you release

**Comment by int3l** [comment]
I will need to ask @madmaze about the last one and will let you know.
And once again, thanks for your time!
