### ISSUE TITLE
Process batch files from momery

### ISSUE THREAD

**Issue by itumeleng-mabote** [madmaze/pytesseract#224]
Is there a way I could batch feed tesserect memory files to speed it up?

**Comment by int3l** [comment]
You can use the tesseract option for list of files. Just pass string with the path to the text file that contains the list of images. Check the pytesseract docs for more info and example.

**Comment by itumeleng-mabote** [comment]
Was hoping to do everything in memory. Is that possible?

**Comment by int3l** [comment]
pytesseract is just a wrapper to the C++ tesseract standalone program, so if you have the files in the python memory, pyteeseract doesn't support direct processing (via pipe/ipc), it will save it as a file on disk.

**Comment by int3l** [comment]
Referencing and closing as duplicate in favor of #172
