### ISSUE TITLE
TesseractNotFoundError() but with only certain files

### ISSUE THREAD

**Issue by cecypollo** [madmaze/pytesseract#228]
Hi!
I'm using pytesseract to read some pdf files, and it works perfectly *almost* all the time but with certain pdfs and in certain random pages the script breaks and gives me this error: 

**raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path**

Any ideas? 

Thanks!!!

**Comment by int3l** [comment]
Can you share the version of tesseract and pytesseract?
Also, can you provide sample pdf that triggers that behavior?

**Comment by int3l** [comment]
I can't reproduce - under Debian with tesseract 4.0.0 - I got TesseractError about unsupported PDF.
I can't make pytesseract to raise TesseractNotFoundError. What is your version of python and OS?

**Comment by int3l** [comment]
Can you change your local pytesseract code on [Line 224-225](https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L224-L225) to:

```python
except OSError as e:
    print(str(e))
    raise e
```

**Comment by cecypollo** [comment]
Hi, did that and now the error is: 
File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 224, in run_tesseract
    raise e
OSError: [Errno 12] Cannot allocate memory

D:

**Comment by int3l** [comment]
Yep, that one is nasty, I guess that the tesseract subprocess reaches the memory limit for your system.

I will make changes, so that all non-related to pytesseract OS errors bubble up. This way, the user will be able to get proper information about the issues.
