### ISSUE TITLE
Cube language model error

### ISSUE THREAD

**Issue by AlfredoCubitos** [madmaze/pytesseract#229]
Hi,

I'm trying to pytesseract with the German language option -l deu.
But every time I get this error

> pytesseract.pytesseract.TesseractError: (-11, 'Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /usr/share/tessdata/deu.cube.lm Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object init_cube_objects(false, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 210')

/usr/share/tessdata/deu.cube.lm doesn't exist, because it is not part of the official tesseract distribution.

when I run tesseract directly with -l deu it works

**Comment by int3l** [comment]
You should pass the --tessdata-dir option via the **config** parameter. Please check the README for more details. For some reason, tesseract can't find this path, when pytesseract calls it.

**Comment by int3l** [comment]
@AlfredoCubitos keep in mind that this is not a pytesseract specific issue but rather tesseract configuration issue. Check/ask on StackOverflow - for example, similar issue: [unable to open Cube language model params for hindi Language in tesseract](https://stackoverflow.com/questions/35403070/unable-to-open-cube-language-model-params-for-hindi-language-in-tesseract)

**Comment by AlfredoCubitos** [comment]
@int3l I have red this article before.
The path is correct. The problem is, that the file `deu.cube.lm` for German language is not part of  tesseract.
- by the way, for `-l eng` the `eng.cube.lm` exists, so itis part of tesseract

When I run tesseract on the command line with the same parameters `-l deu` everythng works fine.

I also tried to run tesseract with `subprozess` 
`subprocess.run(["tesseract",imPath,"test_opencv","-l deu","--oem 1", "--psm 3"])`
This also works fine.

Have you ever tried to run pytesseract with the option `-l deu`?

**Comment by int3l** [comment]
Which pytesseract function is used in your code, because `image_to_string` uses the **txt** config template and not the **test_opencv**?
If you want to make a custom function different than image_to_string, you can use `run_and_get_output`.
Also, where is the location of your deu.cube.lm file and where is the location of your traindata folder, because if your tesseract setup can't find the traindata folder, it doesn't matter that your path is correct.

**Comment by AlfredoCubitos** [comment]
I'm trying to use `image_to_string`
**test_opencv** is the output file
What do you mean with **txt** config? Is there a different configuration?

The file `deu.cube.lm` was never provided by tesseract, so I'm extremely confused why  this error message occurs. 

I'm trying to run this small program:

```

import cv2
import sys
import pytesseract

if len(sys.argv) < 2:
    print('Usage: python ocr_simple.py image.jpg')
    sys.exit(1)
imPath = sys.argv[1]
config = ('-l deu --oem 1 --psm 3')
im = cv2.imread(imPath)
text = pytesseract.image_to_string(im, config=config)
print(text)
```

This little program throws the error we are talking about

But, I currently found out that when I'm using
`text = pytesseract.image_to_string(im, lang='deu')`
Everything works!

So, it seems that my config definition `-l deu` is wrong. I thought that I could place the language option also into the config definition

**Comment by int3l** [comment]
Yeah, about that :D I see what is going on. So the config is only for the **additional custom** flags and options of tesseract. So the above snippet effectively executes something like that `-l eng ... -l deu`, which might be the confusing bit for tesseract.
Basically you should use the existing pytesseract parameters, whenever you can and if there is no default option for some flag, than you should add it to the **config** parameter.
And for example - if you want to use multiple languages, you should use `lang='deu+eng'` parameter.

But yeah - the documentation doesn't point that explicitly, so maybe I should elaborate more in the examples.

Thank you for reporting this. Closing this as resolved now.
Please feel free to reopen if you have any additional problems with this issue.
