### ISSUE TITLE
add html mode

### ISSUE THREAD

**Issue by aws623** [madmaze/pytesseract#23]
I can use your config interface to add config=+hocr.txt, and include in that file a command to output hocr, but then the file cleanup process gets buggy because it looks for either .box or .txt, not .html's. the most logical way to fix this would probably be to directly switch "box=true' to something like "output" where output permits either box or hocr/html...

**Comment by int3l** [comment]
Thank you for your feedback.
Will be addressed with pull request #40 (referencing for the additional info).

If you have any pull requests, please let me know.
