### ISSUE TITLE
TESSDATA_PREFIX environment variable

### ISSUE THREAD

**Issue by AlertColby** [madmaze/pytesseract#231]
my code:
```
from PIL import Image
import pytesseract
pytesseract.pytesseract.tesseract_cmd = 'C:/Program Files (x86)/Tesseract-OCR/tesseract.exe'
text=pytesseract.image_to_string(Image.open('C:/Users/Administrator/Desktop/validity.jpg') )
print(text)
```

get an error:

`pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')`

I don't know how to solve it.
please give me a hand.

**Comment by int3l** [comment]
Take a look a the documentation for "Error opening data file"
You will find example how to fix your problem.
