### ISSUE TITLE
PyTesseract gives empty output on psm 6 and 7

### ISSUE THREAD

**Issue by AyushP123** [madmaze/pytesseract#232]
pytesseract version: 0.3.0
Example:
![04_11_2019_18_44_04_11_2019_18_44_frame0208_1](https://user-images.githubusercontent.com/9451641/64478873-bc0ccd80-d1cc-11e9-9a53-5da299b76417.png)
![04_18_2019_11_19_04_18_2019_11_19_frame0398_1](https://user-images.githubusercontent.com/9451641/64478875-c29b4500-d1cc-11e9-8c53-5e37ed90c19e.png)

pytesseract gives an empty output when using the command.

> text = pytesseract.image_to_string(cropped, config='--psm 7')

or if I use config="--psm 6"

However it gives a correct output at "--psm 13"
I get the correct output while using the tesseract command with psm 6 and 7.

**Comment by AyushP123** [comment]
Here is the link to the images 
https://drive.google.com/drive/folders/1VDBPB_k-oOXbWUI3zIlB3ljuyIlOkoMK?usp=sharing

**Comment by int3l** [comment]
Hi @AyushP123 try to pass the image name as string to pytesseract, like that:
```python
pytesseract.image_to_string('example_image_name.jpg', config='--psm 7')
```
This way pytesseract will not modify the input image.
