### ISSUE TITLE
pytesseract alto

### ISSUE THREAD

**Issue by renarios** [madmaze/pytesseract#234]
I use Tesseract from bash script to create Alto XML, but I would like to use Python for bulk processing.
What command do I have to use to create Alto XML with pytesseract?

**Comment by int3l** [comment]
The ALTO (XML) output support is experimental, a.k.a very new - "The master branch also has experimental support for ALTO (XML) output" from [tesseract README](https://github.com/tesseract-ocr/tesseract/blob/master/README.md).

You can try to use the **pytesseract.run_and_get_output** function/method to build your own custom _image_to_alto_xml_ method.

**Comment by renarios** [comment]
Okay, thanks.
Would you like me to share the code?

**Comment by int3l** [comment]
If you want, you can share it here for future reference. It is your call.
