### ISSUE TITLE
Already changed the "tesseract_cmd" but it still asks me to include the sentence to change it

### ISSUE THREAD

**Issue by Obuil4evr** [madmaze/pytesseract#235]
Hello, I am using pytesseract on macOS, and my python code is:
```
from PIL import Image

import pytesseract

pytesseract.pytesseract.tesseract_cmd = r'/usr/local/Cellar/tesseract/4.1.0/bin/tesseract'


print(pytesseract.image_to_string(Image.open('test.png')))
```

You can see I've already added the sentence wanted, but the running result is still:

```
"# If you don't have tesseract executable in your PATH, include the following:
pytesseract.pytesseract.tesseract_cmd = r'<full_path_to_your_tesseract_executable>'
# Example tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract'
[Finished in 1.0s]"

btw, if I use a wrong path in r'...', for example:

```
from PIL import Image
import pytesseract

pytesseract.pytesseract.tesseract_cmd = r'/usr/local/Cellar/tesseract'

print(pytesseract.image_to_string(Image.open('test.png')))

```
then the result would include:
"pytesseract.pytesseract.TesseractNotFoundError: /usr/local/Cellar/tesseract is not installed or it's not in your path"

I am puzzled, could you please by any chance give me some advice? Thanks!

**Comment by int3l** [comment]
Hi @Obuil4evr - check if you have tesseract in your PATH env variable with the command: `which tesseract`
Also test if you can run the tesseract by executing the custom path, that you are using for pytesseract, in your terminal.
