### ISSUE TITLE
letters are merged into one bouding box. Content shifted, though correct

### ISSUE THREAD

**Issue by jansindl3r** [madmaze/pytesseract#236]
I am writing a little script that finds each letter on a page and saves that as individual image. It works nice, though I discovered some weird behaviour. I attached one of the program's output - please see word _ordered_ in the image.
If we have a look at the note in corner of letter's bounding box, we can see that the content is preserved, though the contours shifted.

using:
`image_to_boxes`

![log_small_bug](https://user-images.githubusercontent.com/44162266/66718158-004d4800-ede1-11e9-901a-8cb06e6b9f1f.jpg)

**Comment by int3l** [comment]
This might be a tesseract problem itself? Did you tested without pytesseract?

**Comment by jansindl3r** [comment]
@int3l  sorry, I don't understand your question. Can you explain it to me, please?
Here is interesting example:

**hand cropped picture -> buggy**
![log_2](https://user-images.githubusercontent.com/44162266/66719815-ce45e100-edf4-11e9-982e-722144d17ffb.jpeg)
**First search for words, crop with PIL and then search for letters -> works**
![log](https://user-images.githubusercontent.com/44162266/66719816-cede7780-edf4-11e9-9c36-9e4581a0211e.jpeg)

**Comment by int3l** [comment]
Interesting - it seems that the cropping matters.

The command that pytesseract executes is:
`tesseract test.jpeg output.file batch.nochop makebox`
You can try to get the result directly and apply them with python in order to check.

**Comment by jansindl3r** [comment]
@int3l you are right, those output are similar, buggy as well but slightly different result. Can you pin it to their Issues, please? Or shall I fill new one there? 
`
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.3 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
`
*hand cropped*
![handCut](https://user-images.githubusercontent.com/44162266/66751304-0699fd80-ee8f-11e9-82a9-d8a9da71d440.jpg)
*cropped with PIL base on data from tesseract*
![pilCut](https://user-images.githubusercontent.com/44162266/66751303-0699fd80-ee8f-11e9-9979-c06691d99af8.jpg)

**Comment by int3l** [comment]
I am not sure if this is the interned behavior or not and yes, you should file a new issue in the tesseract issue tracker since this is not a pytesseract specific one and you are the one that can test it anyways (for your particular use case). Pytesseract is just a wrapper that allows easy access/execution of tesseract itself from within python.
