### ISSUE TITLE
Is there a way to avoid I/O?

### ISSUE THREAD

**Issue by thoughtobj** [madmaze/pytesseract#24]
The usage section says the way to use pytesseract is 

``` python
print(pytesseract.image_to_string(Image.open('test.png')))
```

I'm wondering if there is a way to avoid I/O. I am using OpenCV to do some image pre-processing prior to sending images to tesseract. Is there a way I can send the image from OpenCV directly to pytesseract instead of first saving it to a file? Here is what I have to do now

``` python
#save image from OpenCV to disk
cv2.imwrite(path_to_image, my_image)
print(pytesseract.image_to_string(Image.open(path_to_image)))
```

This way I _have_ to first write the image to the disk. I believe this will not be scalable in a distributed architecture because of the I/O involved. Any way to avoid this?

**Comment by JonnoFTW** [comment]
Use a `StringIO` as a buffer.

```
import StringIO
import pil

sBuffer = StringIO.StringIO()
...
cv_img = cv2.imencode('png', my_image)[1]
sBuffer.write(sBuffer, cv_img.tobytes())
img = Image.open(sBuffer)

```

This is completely untested by the way.
