### ISSUE TITLE
Imaga_to_data()

### ISSUE THREAD

**Issue by cjpr008** [madmaze/pytesseract#240]
Hi everyone!

I am converting a multipage pdf to images. Using image_to_data it gives me the reading information (text, line_num, page_num, etc). But page_num is always 1. Can anyone help me understand how you can identify pages?
Anyone can help me?

Thanks!

**Comment by int3l** [comment]
Hi @cjpr008  You should test directly with tesseract itself and check if the result is the same.
pytesseract just extracts data from tesseract ocr process. So maybe you should ask in the tesseract issue tracker if there is a problem with the extracted information. Or maybe you should use different option - but for that it is better to ask on StackOverflow.
