### ISSUE TITLE
Should input image be RGB or BGR?

### ISSUE THREAD

**Issue by gathierry** [madmaze/pytesseract#241]
On this page https://pypi.org/project/pytesseract/, you gave examples taking images from both PIL and OpenCV as input. But for PIL, the input is RGB, while it's BGR for cv2.
I would like to know which is the correct color format for tesseract? Or maybe both are ok?

**Comment by int3l** [comment]
At the moment, if pytesseract get image object that is not RGB, it will try to convert it to RGB - regardless of PIL or cv2.
For the prefer/correct mode for tesseract - we need to consult the [Leptonica documentation](https://tpgit.github.io/UnOfficialLeptDocs/leptonica/README.html) itself, because as far as I know, this is the underlying image library for tesseract.

**Comment by gathierry** [comment]
Hi @int3l, thanks for your reply. But I am still not very clear with this part

> if pytesseract get image object that is not RGB, it will try to convert it to RGB - regardless of PIL or cv2.

if we use
`print(pytesseract.image_to_string(Image.open('test.png')))`
the input is an PIL Image object and I suppose there's color information stored in the object.

However, if we do this
```
img = cv2.imread(r'/<path_to_image>/digits.png')
print(pytesseract.image_to_string(img))
```
the input is a numpy array whose color is in fact bgr.
How can you convert it to RGB if the input is a numpy array without any other information?

**Comment by int3l** [comment]
With this two methods: [PIL.Image.fromarray](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray) (from numpy to PIL image object) and/or [PIL.Image.convert](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert) (to RGB mode).

**Comment by gathierry** [comment]
Maybe I didn't express my idea well.
Say we have a 1x1x3 image which has three channels and only one pixel.
```python
>>> img_cv2 = cv2.imread(imgpath)  # read from opencv
>>> img_pil = Image.open(imgpath). # read from PIL
>>> np.asarray(img_pil)
array([[[127,   0, 255]]], dtype=uint8)
>>> img_pil_from_cv2 = Image.fromarray(img_cv2)
>>> np.asarray(img_pil_from_cv2)
array([[[255,   0, 127]]], dtype=uint8)
```
As you can see above, the channel order is reversed, because opencv use BGR while PIL use RGB. That's why I doubt that 
```python
pytesseract.image_to_string(Image.open('test.png'))
```
and 
```python
img = cv2.imread('test.png')
pytesseract.image_to_string(Image.fromarray(img))
```
could have the same result.

**Comment by int3l** [comment]
Yea, I see what you mean - **Image.fromarray** sets wrong image mode to RGB and this means that consecutive check of the mode will falsely say "RGB".

```python
from PIL import Image
import numpy as np
import cv2

imgpath = 'test.jpg'

img_pil = Image.open(imgpath)
print(np.asarray(img_pil))

img_cv2 = cv2.imread(imgpath)
print(np.asarray(img_cv2))

img_pil_from_cv2 = Image.fromarray(img_cv2)
print(np.asarray(img_pil_from_cv2))
print(img_pil_from_cv2.mode)
```

So we might need to do additional work. But it is really strange that Image.fromarray sets wrong mode.
This looks like a bug, because the method can get the type of the object and it can get the current mode before the conversion.

**Comment by int3l** [comment]
Even more strange - neither `cv2.imread(imgpath, cv2.IMREAD_ANYCOLOR)` nor `cv2.imread(imgpath, cv2.IMREAD_UNCHANGED)` work. So I guess that OpenCV always use BGR, but why the fromarray method doesn't set the proper BGR mode then...

**Comment by int3l** [comment]
Ok, so a quick test shows that Pillow doesn't support arrays with BGR mode 👎 (`Image.fromarray(arr, mode='BGR')`). So the only other option is beforehand conversion to RGB or one of the other supported modes.

**Comment by gathierry** [comment]
Okay, many thanks for the explanation.
