### ISSUE TITLE
'image_to_data' output type 'DataFrame' : config options needed for "N/A" in input image 

### ISSUE THREAD

**Issue by Laetij** [madmaze/pytesseract#242]
hello,

We got some problems with image_to_data function. 

When we put some images containing "N/A" text  in pytesseract.image_to_data function with output type 'Data.Frame', pandas automatically converts these "N/A" as nan to create the dataframe. 

The problem is that when we need to remove real nan, we also remove "N/A" text that are important in our output text. To fix it, we have to modify the pytesseract.py file and add in line 386 the option "keep_default_na =False, na_values = ["nan"].

That's a problem because we need to do this every time we install pytesseract in a new environment...

**Comment by int3l** [comment]
Now you can use:
```python
pytesseract.image_to_data(
    img,
    pandas_config={'keep_default_na': False, 'na_values': ["nan"]}
)
```
Done, check the documentation for additional info :)

**Comment by Laetij** [comment]
Thank you ! :)
