### ISSUE TITLE
how to extract text and confidence at the same time(keeping in mind spaces are preserved) without calling two times as image_to_string and image_to_data

### ISSUE THREAD

**Issue by vanam-vishal** [madmaze/pytesseract#243]
https://stackoverflow.com/questions/59249752/how-to-extract-confidence-and-text-simultaneously-using-pytesseract

**Comment by int3l** [comment]
There is no such functionality in pytesseract at the moment. And I am not sure if tesseract itself supports something like that.

But you can try to use the more generic function **run_and_get_output** in order to implement such custom behavior (of course, if tesseract supports it).
