### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by its-gazza** [madmaze/pytesseract#246]
In README.rst, USAGE -> Library Usage, the print statement in the try statement is missing closing bracket

Should be:
```python
try:
    print(pytesseract.image_to_string('test.jpg', timeout=2)) # Timeout after 2 seconds
    print(pytesseract.image_to_string('test.jpg', timeout=0.5)) # Timeout after half a second
```

**Comment by int3l** [comment]
Hi @its-gazza,
thank you very much for mentioning this.
Pretty silly mistake of mine to not test the code block.
