### ISSUE TITLE
Batch process bounding boxes in a single image

### ISSUE THREAD

**Issue by CarlosUvaSilva** [madmaze/pytesseract#250]
Is there a way to provide an image and a list of boxes and batch process the image with all the boxes in one go?

```
results = []
if template:
    config = ("-l eng --oem 1 --psm 7")
    for square in template:
      className = square['class_name']
      startX = square['start_x']
      endX = square['end_x']
      startY = square['start_y']
      endY = square['end_y']
      roi = bw_image[startY:endY, startX:endX]
      text = pytesseract.image_to_string(roi, config=config)
      results.append(((startX, startY, endX, endY), className, text))
```

I need to do something like this code I show above. Is there a way to make it faster?

**Comment by int3l** [comment]
From the documentation (README):
```python
# Batch processing with a single file containing the list of multiple image file paths
print(pytesseract.image_to_string('list_of_images.txt'), config=config)
```
This is the closes that you can get in order to do batch processing while utilizing pytesseract.
But this requires pre-processing - creating the custom images and adding their file names to the metadata file list_of_images.txt. Not sure which approach is faster.
