### ISSUE TITLE
Data type of output data frame is not always string

### ISSUE THREAD

**Issue by gathierry** [madmaze/pytesseract#251]
Hi, when I called
```python
pytesseract.image_to_data(image, config=config_str, output_type='data.frame')
```
I got a data frame with the last column named "text" containing words recognized. 
However, if the text is a number, the data type for this column could be *float* instead of *object* and the number might be different from the text.
For example, I have an image of a number *2*, `image_to_data` gives me *2.0*.

There's no such concern if `output_type='dict'`. So I guess this is bug for data frame output?

**Comment by int3l** [comment]
This is because the default behavior of pandas read_csv. The latest version of pytesseract have support for **pandas_config**, so you can fine tune the pandas.read_csv parameters. In your case, I think that you can use the **dtype** option of read_csv?

**Comment by gathierry** [comment]
Ok, thank you for the update.

**Comment by thulard** [comment]
For those wondering, the read_cvs parameters can be passed to pytesseract like this:
df = pytesseract.image_to_data(image, output_type='data.frame', config=config_str, pandas_config={'dtype': object})
