### ISSUE TITLE
Help installing via anaconda

### ISSUE THREAD

**Issue by Pasgru** [madmaze/pytesseract#253]
I removed the original pytesseract.

conda install pip

git clone https://github.com/madmaze/pytesseract.git

cd pytessseract

pip install .

But the function: `output_type=Output.DICT` still gives me the Error: "Undefined name Output"
All other functions are working just like if I install it from the anaconda cloud. But i need the Output format DICT. Hope somebody can help

**Comment by int3l** [comment]
You can just use the **[official pytessract conda-forge repo](https://anaconda.org/conda-forge/pytesseract)**.

**Comment by Pasgru** [comment]
I still get the same error: "Undefined name Output"

**Comment by int3l** [comment]
@Pasgru thank you for reporting this, interesting.
What is your OS and python version that you are testing with?

**Comment by Pasgru** [comment]
OS is Windows 10

with "conda list" python shows as 3.7.6 but in the control center it shows as 3.8.1

**Comment by int3l** [comment]
I just tested the conda-forge repo and it works without problems.
Did you imported the `Output` class before using it?
If not you need `from pytesseract import Output`

**Comment by Pasgru** [comment]
OMG, thanks I just forgot that. Thanks a lot.
