### ISSUE TITLE
Pass multiple images at once 

### ISSUE THREAD

**Issue by ShroukMansour** [madmaze/pytesseract#254]
Hi, I know that I can pass multiple images to tesseract using the command line like this `tesseract list.txt list.out.txt` where list.txt is a file containing images paths. How can I do that in pytesseract without using a loop?

**Comment by int3l** [comment]
You can pass the path for this list.txt as string to pytesseract and it should do the same.

**Comment by ShroukMansour** [comment]
It worked thank you, also can I pass to it an array of images? @int3l

**Comment by int3l** [comment]
If you mean Python lists - unfortunately, there is not built-in support for that at the moment.

**Comment by sysescool** [comment]
> You can pass the path for this list.txt as string to pytesseract and it should do the same.

I want to OCR multi images in one pdf. So I write it as follow, but not worked:
```
 pdf = pytesseract.image_to_pdf_or_hocr("C:/list.txt", lang='eng', extension='pdf')
 with open(pdfoutputfolder+"result.pdf", 'w+b') as f:
     f.write(pdf) # pdf type is bytes by default
```
I searched and got it: https://github.com/tesseract-ocr/tesseract/issues/1268
but I hope write it in python by pytesseract, instead of CLI.
