### ISSUE TITLE
WinError5 Permission error when pytesseract trying to clean up the temp file in Windows 10/Pythono3.7

### ISSUE THREAD

**Issue by raynus** [madmaze/pytesseract#255]
I'm using pytesseract with 5.0.0-alpha.20200223 tesseract Win64 installer on Windows 10 with Python 3.7 in pipenv.

When running the  "image_to_data", it fails with PermissionError: [WinError 5] Access is denied: 
I have all the PATH and pytesseract.tesseract_cmd (point to tesseract.exe) set-up and running the cmd as admin does not solve the issue.

The problem seems to occur in cleanup function when pytesseract tries to clean-up the tempfile.
See my full post in google group here.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/IyPpisQ1E4U/nLpnHt83AQAJ

After diving in pytesseract.py and googling for a couple of days, I added the "deleted=False" argument to NamedTemporaryFile accroding to the stackoverflow thread. 

https://stackoverflow.com/questions/55081022/python-tempfile-with-a-context-manager-on-windows-10-leads-to-permissionerror

The problem disappear so far.

**Comment by int3l** [comment]
Which version of pytesseract do you have?

**Comment by raynus** [comment]
I'm using pytesseract 0.3.2

Thanks for fixing it. :)
