### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by roxanadangerm** [madmaze/pytesseract#259]
Hello,
I have the following code that basically take a list of PIL images and generate a pdf from it:

       def to_pdf(images, remove=True):
             images[0].save(fname_out, format='tiff', append_images=images[1:], save_all=True, duration=500, loop=0)
             pdf = pytesseract.image_to_pdf_or_hocr(fname_out[:-4] + '.tiff')
             if remove:
                   os.remove(fname_out)
             with open(fname_out[:-4] + '.pdf', 'w+b') as f:
                     f.write(bytearray(pdf))

I called multiple times for  batch of files. I noticed the memory is continuously increasing over the time. Are you aware of this behavior? Is there any method that need to be called to remove unused memory?

Many thanks and best regards,
Roxana

**Comment by int3l** [comment]
What is your version of pytesseract?
Also did you tried to comment out or replace the line with `pytesseract.image_to_pdf_or_hocr` in order to check if the memory leak comes from pytesseract?

**Comment by Gornoka** [comment]
There appears to be a Memory leak in your code somewhere at least it is rising at the same rate regardless of the pytesseract function being called or not.

> current memory usage before image 1 : 
(802014, 910971)
current memory usage before image 2 : 
(818084, 927041)
current memory usage before image 3 : 
(833178, 942135)
current memory usage before image 4 : 
(848776, 957733)
current memory usage after all images written : 
(863142, 972131)


This function without pytesseract leaves almost the same memory increase per iteration.
```
def to_pdf2(images, remove=True, fname_out="1"):
    images[0].save(fname_out, format='tiff', append_images=images[1:], save_all=True, duration=500, loop=0)
    if remove:
        os.remove(fname_out)
```

> current memory usage before image 1 : 
(753778, 790574)
current memory usage before image 2 : 
(767906, 799904)
current memory usage before image 3 : 
(782034, 814032)
current memory usage before image 4 : 
(796162, 828160)
current memory usage after all images written : 
(809466, 841928)

**Comment by roxanadangerm** [comment]
Hello,
sorry the delay of my reply. I have reviewed my code and I don't see memory leak in any other place. Besides, the memory usage you printed out confirm each call of the method maintains some memory that is not freed.
After the processing of many images it become a problem.
Many thanks,
Roxana

**Comment by int3l** [comment]
@roxanadangerm Can you share the OS platform and version?

**Comment by roxanadangerm** [comment]
Sure, sorry, I should given these details before.
OS: Ubuntu 18.04
pytesseract version: 4.0.0-beta.1

**Comment by int3l** [comment]
I am testing for memory leak with this snippet:

```python
from PIL import Image
import pytesseract


for _ in range(10_000_000):
    pdf = pytesseract.pytesseract.image_to_pdf_or_hocr(Image.open('test.jpg'))
```

OS: Ubuntu 18.04 Bionic latest
python: 3.6.9
tesseract: 4.0.0-beta.1
pytesseract: 0.3.3

After an hour of testing, the memory usage of the python process barely increases.
I can't reproduce the leak.

**Comment by roxanadangerm** [comment]
Sure, sorry, I should given these details before.
OS: Ubuntu 18.04
pytesseract version: 4.0.0-beta.1

**Comment by roxanadangerm** [comment]
Yes, that's right. Thank you very much.
I will find where the leaks occurs, but definitely not there.
