### ISSUE TITLE
A bug of get_tesseract_version() function in Windows system

### ISSUE THREAD

**Issue by BruceLee569** [madmaze/pytesseract#263]
System version:  Windows 10 Enterprise LTSC x64 (version 17763)
Python version:  3.7.4
Pytesseract version:  0.3.3

When I call pytesseract.image_to_data(Image.open('test.png')), an error occurred as follows:

```python
Traceback (most recent call last):
  File "C:/Users/bruce/Desktop/SimpleReq/MyOCR.py", line 29, in <module>
    print(pytesseract.image_to_data(Image.open('test.png')))
  File "C:\apps\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 414, in image_to_data
    if get_tesseract_version() < '3.05':
  File "C:\apps\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 114, in wrapper
    wrapper._result = func(*args, **kwargs)
  File "C:\apps\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 328, in get_tesseract_version
    [tesseract_cmd, '--version'], stderr=subprocess.STDOUT,
AttributeError: 'str' object has no attribute 'decode'
```

So after I commented `.decode('utf-8')` in line 328, in get_tesseract_version ......, the error disappeared, is this a bug? Please check out.

**Comment by int3l** [comment]
Hi @BruceLee569 - very strange behavior.
The official python documentation says that the output of `subprocess.check_output` should be bytes and not str. Can you try to update your python version to the latest supported one?
I can see that there is python 3.7.7

We can add conditional check, but this seems like a python bug that causes this behavior, rather than application bug.

**Comment by BruceLee569** [comment]
Yes, it's very strange, after checking source code of `subprocess.check_output` which invoking  `subprocess.run` which invoking  `subprocess.Popen` which one of default param is `enconding='utf-8'` of function `__init__` in my computer, that's the reason why I get a string from Popen instance.

So I download official python source code of version 3.7.4 and version 3.7.7, both of them default value is `enconding=None` which is same as python documentation, now I guess if anaconda in windows changed it, but that's too much trouble and high probability won't be because of it.

Maybe I accidentally modified the source code of the `subprocess.Popen` function, who konws, now I think I can modify encoding to None and close this issue, anyway, thanks a lot.
