### ISSUE TITLE
Training?

### ISSUE THREAD

**Issue by markwbrown** [madmaze/pytesseract#27]
I've OCRed some text and I'm not getting great results. Is there a way to train pytesseract?

**Comment by mlissner** [comment]
I could be wrong here, but I believe if you train Tesseract, that'll affect pytesseract. So, put another way, pytesseract isn't a factor in Tesseract training.

**Comment by dcguim** [comment]
I have the same question, it`s not clear if it`s possible to train pytesseract. Once I have box files and image files enough, is there anyway i can train the algorithm to improve my results?

**Comment by int3l** [comment]
@markwbrown, @dcguim yes, there is a way to train the Tesseract.
Please take a look at the official [Tesseract training documentation](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract).
