### ISSUE TITLE
 Library not loaded: /usr/local/opt/tesseract/lib/libtesseract.4.dylib

### ISSUE THREAD

**Issue by Jamxscape** [madmaze/pytesseract#270]
`ImportError: dlopen(/Users//Desktop/Yep/venv/lib/python3.7/site-packages/tesserocr.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/tesseract/lib/libtesseract.4.dylib
  Referenced from: /Users//Desktop/Yep/venv/lib/python3.7/site-packages/tesserocr.cpython-37m-darwin.so
  Reason: image not found`
MAC OS 10.15.4
when i used the lower version tesseract 3.05.01,i changed the enveriment of tessdata ,and it can work in the terminal when `tesseract test.png test.txt`, but in pytesseract `import tesseract` cant work ,i dont know why.

**Comment by int3l** [comment]
Hi @Jamxscape - I believe that this issue is related to the **[tesserocr](https://github.com/sirfz/tesserocr)** issue tracker :) This is the **pytesseract** issue tracker.

Closing this one since it is not pytesseract related.
