### ISSUE TITLE
Get confidence for alternative symbol choices per character

### ISSUE THREAD

**Issue by Shaunlipy** [madmaze/pytesseract#271]
Hi, I'm wondering if it is possible to use pytesseract for alternative predictions per character (say top 3 predictions for each character)?

Thanks

**Comment by int3l** [comment]
Hi @Shaunlipy ,
Pytesseract is just a wrapper for the tesseract-ocr tool. If tesseract-ocr can do this, then pytesseract most probably supports it. But I don't think that tesseract-ocr supports alternative predictions (I might be wrong) - you need to check the tesseract-ocr documentation for that.
Also feel free to ask about this on StackOverflow.

**Comment by int3l** [comment]
Closing this, because it's not a pytesseract specific issue.
