### ISSUE TITLE
Pytesseract seems to be ignoring custom configurations

### ISSUE THREAD

**Issue by lauraadalmolin** [madmaze/pytesseract#274]
Hello, there! 
I am developing a script to measure Tesseract's accuracy for some files. Therefore, I need to run Tesseract on the same page of a pdf with different psm and oem options. Right now I am using the tesseract 4.0.0-beta.1 and pytesseract 0.3.4. The custom config is being sent to Tesseract via the following function:
~~~
pytesseract.image_to_pdf_or_hocr(img, lang='por', extension='hocr', config=config)
~~~
I have tripple checked and everything seems to be ok with the config string. This is how I create it:
~~~
config = '--psm ' + PSM[int(id_config)-1] + ' --oem 1'
~~~
The weirdest thing is that even if I set custom configs like that, I get the same hocr result. It's not the proper response, since if I run the same configs directy on Tesseract there are different outcomes.

Aditional info: the exact same script works perfectly on my coworkers' computers (both of them run Windows), meaning that they get the proper (different) results for each config. I am currently trying to run the script on my recently formatted computer (Ubuntu 18.04).

**Comment by int3l** [comment]
@lauraadalmolin Hi and thank you for reporting the issue.
Can you provide the working CLI tesseract command for reference - I will check what is the difference with the pytesseract generated one.

**Comment by lauraadalmolin** [comment]
Sure, I'm using the following CLI command:
~~~
$ tesseract page.png out2 --psm 11 -c tessedit_create_hocr=1
Tesseract version: tesseract 4.0.0-beta.1
~~~
It generates different results for each psm, as expected. I checked the run_and_get_output function, but I didn't find any documentation related to the parameters to be set. I would be really glad if you could clear this out for me.


Thank you very much for your time and attention.

**Comment by lauraadalmolin** [comment]
Actually, I checked, as you suggested, if the tesseract config files were taking precedence and apparently that was the case. I deleted the line related to psm from the hocr file and it worked.

Anyways I guess the issue is still relevant because maybe pytesseract isn't getting enough privileges to overwrite tesseract default configs. That is just a guess, and the only reason that I am writing it down is because it worked perfectly on both of my coworkers' computers (even though they didn't change the tesseract config files at all). Since they use Windows, maybe the issue is somehow related to Ubuntu. One more time, that is just a guess. 

Thanks again for everything.

**Comment by int3l** [comment]
You can check the content of the tesseract config files here: [Tesseract config files](https://github.com/tesseract-ocr/tessconfigs/tree/master/configs)

The content of the hocr file is:
```
tessedit_create_hocr 1
hocr_font_info 0
```

**Comment by lauraadalmolin** [comment]
Funniest thing is that I installed tesseract literally yesterday using apt install and the hocr config file did not have the same content as recommended. There was an additional line setting the psm mode to 1. Really weird.

**Comment by int3l** [comment]
pytesseract produces the following CLI command:

```bash
$ tesseract test.jpg output_file -l por --psm 1 --oem 1 hocr
```
And the problem with the precedence of the arguments is a Tesseract specific issue - you can take a look at the documentation: [Tesseract CLI arguments documentation](https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#inout-arguments)
