### ISSUE TITLE
have a trouble to use pytesseract.image_to_boxes. plz help me

### ISSUE THREAD

**Issue by Tailsman** [madmaze/pytesseract#276]
executed following codes but characters seems weird
texts in file 'test.png' is KAEDEX00
but result of pytesseract.image_to_boxes says HAHHHHHH
I dont know whats wrong I did

>>> import cv2
>>> import pytesseract
>>> filename = 'test.png'
>>> img = cv2.imread(filename)
>>> h, w, _ = img.shape # assumes color image
>>> boxes = pytesseract.image_to_boxes(img)
>>> print(pytesseract.image_to_boxes(img))
H 12 7 24 23 0
A 25 7 41 23 0
H 42 7 51 23 0
H 53 7 66 23 0
H 69 7 77 23 0
H 79 7 94 23 0
H 95 7 107 23 0
H 109 7 121 23 0

added link shows pytesseract.image_to_boxes seem to work fine
https://github.com/madmaze/pytesseract/issues/89

pytesseract.image_to_boxes look like works fine in the picture below from the link
https://user-images.githubusercontent.com/40732483/72029165-0f8e4580-32ab-11ea-9777-d8ba69f5c015.png

and I'm using window version of pytesseract

**Comment by int3l** [comment]
Hi @Tailsman - the OCR accuracy is not a pytesseract issue, because underneath, pytesseract uses Tesseract-OCR. Pytesseract just executes the command. It depends what configuration pass to tesseract itself. You can find help about [Tesseract on StackOverflow](https://stackoverflow.com/questions/tagged/tesseract)

**Comment by Tailsman** [comment]
> Hi @Tailsman - the OCR accuracy is not a pytesseract issue, because underneath, pytesseract uses Tesseract-OCR. Pytesseract just executes the command. It depends what configuration pass to tesseract itself. You can find help about Tesseract on StackOverflow

its not a accuracy thing. cuz I got right result from using pytesseract.image_to_string
Im talking about pytesseract.image_to_boxes doesnt work properly

**Comment by int3l** [comment]
Yes, but still - all that pytesseract does is to get the result from Tesseract itself.
You can test this by directly running tesseract:
```console
tesseract test_img_file output_file batch.nochop makebox
```

**Comment by Gornoka** [comment]
> > Hi @Tailsman - the OCR accuracy is not a pytesseract issue, because underneath, pytesseract uses Tesseract-OCR. Pytesseract just executes the command. It depends what configuration pass to tesseract itself. You can find help about Tesseract on StackOverflow
> 
> its not a accuracy thing. cuz I got right result from using pytesseract.image_to_string
> Im talking about pytesseract.image_to_boxes doesnt work properly

Maybe you can work around that issue by using image_to_data(), and create your own boxes with that data.

**Comment by int3l** [comment]
Yes, the only difference is that image_to_data returns info for words instead of characters, if I am not mistaken.
