### ISSUE TITLE
Method image_to_osd

### ISSUE THREAD

**Issue by Prabh95** [madmaze/pytesseract#277]
I have been using the the method **pytesseract.image_to_osd(img)** for detecting **orientation angles** of my images. It works fine for images rotated at angles 90,180, 270 and for upright(0deg) images. But if I pass an image lets say rotated at 45deg then I get this following **error**:

TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 166 Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.') 

**Note:** The image has enough characters/text for it to detect the orientation angle. The function is able to correctly detect the angle when the same image is rotated at 90.

**Can I use this function for angles other than 0, 90, 270, 180?**

**Comment by int3l** [comment]
Hi @Prabh95 ,
`TesseractError` means that `tesseract-ocr` itself has a problem with the image/configuration. 
Can you try to pass some **lang** parameter too, just to see if this will change the behavior?
Although it looks counter intuitive that it works for 0-90-180-270 and not for 45...
Or maybe you need to resize the image. Unfortunately this is not a pytesseract specific issue and I can't help much with resolving it.
