### ISSUE TITLE
pytesseract image_to_string is giving a complete different output  

### ISSUE THREAD

**Issue by DiaaAj** [madmaze/pytesseract#281]
I'm trying to extract text from an image but pytesseract is giving a totally different output, the image attached below output is "Werle" (complete different word and characters), I tried many different processing methods like image enhancement, rgb2gray, rgb2binary, resizing, still didn't work. What confuses me that the text in the image is very clear and straightforward. I also tried to change the notebook from google colab to my local notebook and made sure that I have the latest version, but same incorrect result.

![mvbu7](https://user-images.githubusercontent.com/34287923/86543572-95bcd900-bf28-11ea-94e6-8480a0d6fd7a.png)
output >> "Werle" << (why!?)
here's my code:-

```
ret,frame = cap.read()
crop_img = frame[320:400,430:840]
text = pt.image_to_string(crop_img)
```

note: this problem happens with other images with the same style but different word

**Comment by int3l** [comment]
Hi @DiaaAj,
did you tried to use tesseract directly?
I guess that tesseract is trained with white background and black font.
Maybe you need a custom trained tessdata for your case.

**Comment by DiaaAj** [comment]
Hi @int3l 
Thank you for the reply, I'm not sure how to use tesseract directly for that task, however, I want to point out that I'm using win10 OS but I also tested that on google colab.

**Comment by DiaaAj** [comment]
Is there any blog/resource that could help me implement this directly using tessract ? I looked it up and it seems everybody uses image_to_string 🤔

**Comment by DiaaAj** [comment]
@int3l  
I preprocessed the image, changed white pixels to black and black pixels to white, and it worked.

**Comment by int3l** [comment]
Hi, glad to hear that you found a solution! Closing this one since it is not a pytesseract specific issue.
