### ISSUE TITLE
Add API to retrieve installed languages

### ISSUE THREAD

**Issue by GokulNC** [madmaze/pytesseract#283]
It'd be great if you could add a function like `get_installed_languages()` to retrieve the list of all supported languages by the Tesseract Installation.

It's basically nothing but running: `tesseract --list-langs`

**Comment by int3l** [comment]
@GokulNC thank you for your suggestion.

Note for devs:
Keep in mind that `tesseract --list-langs` had some issues in the past - tesseract-ocr/tesseract#1679

Docs:
https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#single-options
