### ISSUE TITLE
image_to_data generates arrays with different lengths.

### ISSUE THREAD

**Issue by chipro** [madmaze/pytesseract#290]
Version: 0.3.5

Test Image:
![error_image](https://user-images.githubusercontent.com/19927833/89862898-76763300-dbdb-11ea-9649-28aa49e521aa.jpg)

Results:
Note the '' at the end of 'level' and 'page_num'. Version 0.3.4 works however.
{
	'level': [1, 2, 3, 4, 5, 5, 5, 5, 2, 3, 4, 5, 5, 5, 2, 3, 4, 5, 5, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 5, 5, 2, 3, 4, 5, 5, 5, 5, 5, 2, 3, 4, 5, ''],  <----- extra ''
	'page_num': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ''], <----- extra ''
	'block_num': [0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7],
	'par_num': [0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
	'line_num': [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
	'word_num': [0, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 1, 2, 3, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 3, 0, 0, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1],
	'left': [0, 197, 197, 197, 197, 224, 273, 318, 200, 200, 200, 200, 287, 366, 273, 273, 274, 274, 326, 273, 273, 198, 198, 198, 198, 198, 198, 198, 198, 232, 261, 198, 198, 198, 198, 226, 254, 264, 314, 0, 0, 0, 0],
	'top': [0, 115, 115, 115, 115, 118, 118, 118, 155, 155, 155, 157, 163, 155, 232, 232, 232, 232, 232, 250, 250, 314, 314, 314, 314, 584, 584, 584, 584, 587, 584, 629, 629, 629, 629, 630, 632, 629, 630, 0, 0, 0, 0],
	'width': [809, 176, 176, 176, 19, 44, 40, 55, 306, 306, 306, 78, 68, 140, 174, 174, 98, 49, 46, 174, 174, 45, 45, 45, 45, 116, 116, 116, 30, 25, 53, 160, 160, 160, 23, 24, 5, 46, 44, 809, 809, 809, 809],
	'height': [757, 18, 18, 18, 18, 12, 12, 12, 33, 33, 33, 24, 25, 33, 30, 30, 8, 8, 8, 12, 12, 9, 9, 9, 9, 13, 13, 13, 10, 10, 13, 13, 13, 13, 13, 9, 7, 10, 9, 757, 757, 757, 757],
	'conf': ['-1', '-1', '-1', '-1', 36, 96, 96, 96, '-1', '-1', '-1', 96, 96, 96, '-1', '-1', '-1', 0, 14, '-1', 35, '-1', '-1', '-1', 14, '-1', '-1', '-1', 34, 34, 94, '-1', '-1', '-1', 87, 76, 85, 77, 83, '-1', '-1', '-1', 95],
	'text': ['', '', '', '', '(IB', 'Adobe', 'Media', 'Encoder', '', '', '', 'Enter', 'your', 'password', '', '', '', 'reson', 'account', '', 'AdbeQAMccount@nvidiacom', '', '', '', 'Pasword', '', '', '', 'Reset', 'your', 'password', '', '', '', 'Sign', 'into', 'a', 'diferent', 'account', '', '', '', ' ']
}

**Comment by int3l** [comment]
Hi @chipro and thank you for reporting this.
This behavior could be because of several changes.
Can you provide the exact way that you invoke the **image_to_data** function, so I can reproduce it exactly?

**Comment by int3l** [comment]
This change will  be available in 0.3.6.
