### ISSUE TITLE
how to get text location from the image

### ISSUE THREAD

**Issue by nanshihui** [madmaze/pytesseract#296]
how to get text location from the image

**Comment by int3l** [comment]
Hi @nanshihui - this is the issue tracker for pytesseract.
If you have any questions about the usage of pytesseract, please take a look at [StackOverflow - pytesseract](https://stackoverflow.com/questions/tagged/python-tesseract)

One way to extract the text location is to use **pytesseract.image_to_boxes** method.
Take a look at the documentation for examples: [pytesseract usage](https://github.com/madmaze/pytesseract#usage).
