### ISSUE TITLE
image_to_string adds \n\f whitespace at the end since 0.3.5

### ISSUE THREAD

**Issue by TSeverinDSE** [madmaze/pytesseract#297]
I just updated my packages for my OCR script, and after the update top 0.3.5 the `image_to_string` method adds '\n\f' to all my outputs. 

I used the following code from your readme and your test image and could reproduce the error there.

    import pytesseract
    pytesseract.pytesseract.tesseract_cmd = 'bin\\tesseract-win64\\tesseract.exe'  # local portable install
    from PIL import Image
    print(pytesseract.image_to_string(Image.open('test.png')))  # <long text about a dog and a fox>\n\f

I switched between packages by running either

    pip install --force pytesseract==0.3.4
    pip install --upgrade -r requirements.txt   # which includes the line pytesseract, no version specified

My system information:

- Python 3.7.4, win32
- Run in PyCharm terminal
- Local (portable) installation of 5.0.0-alpha.20200328 (which should not be relevant, since with 0.3.4 and the same tesseract binary everything this does not occur)

I checked the commits for 0.3.6 and searched the issues but could not find a fix yet, so I assume it has not changed. Since 0.3.6 is not in PyPi I refrained from updating manually.

**Comment by TSeverinDSE** [comment]
I did some searching, and it is directly related to #269, where the `.strip()` was removed from run_and_get_ouput (commit  6d5a35213d7e8dcf836e7107fa86ac62265cfa05).

I understand that in that issue it was necessary to remove the `strip()`, I'm just not sure if this _always_ is the desired option.

I think now this should be up for discussion. As for now I added a `strip()` to my code, which is no big deal. In the long run this could however be a compatibility-issue (maybe leave as is and document?).

**Comment by int3l** [comment]
@TSeverinDSE hi,
the idea was that pytesseract should provide the tesseract output as-is without modifications if possible.
This is why we also removed the implicit conversions. This decision was breaking change, but was necessary, because users can easily do the modifications themselves afterwards. But if pytesseract does the modifications implicitly - it will be hard for the users to undo them afterwards.

**Comment by int3l** [comment]
Feel free to send PR with additional documentation if you want.
