### ISSUE TITLE
Difference in the Extracted text when run on GPU vs CPU

### ISSUE THREAD

**Issue by yashkan27** [madmaze/pytesseract#307]
I have a pdf image. And I am using wand library to convert each page(resolution parameter = 300) into image and than extracted text from these images. But when I run these code on GPU the text extracted is not accurate compared to the CPU extracted text. Is there any difference in running pytesseract in GPU and in CPU?

**Comment by int3l** [comment]
Hi @yashkan27 - pytesseract itself runs only on CPU - it is a basic python wrapper around the **tesseract** tool itself.
Do you mean [TesseractOpenCL](https://github.com/tesseract-ocr/tessdoc/blob/master/TesseractOpenCL.md) by "pytesseract in GPU"?
If so, this most probably means that it uses different Tesseract Engine (and settings), and this is why you get different results.
But this is tesseract related question and not a specific pytesseract issue. Pytesseract just makes it a bit easier to invoke tesseract itself from inside the python interpreter.

**Comment by yashkan27** [comment]
Hi @int3l thanks for quick response. I have checked tesseract version on both of my machine.
On Cpu:

`tesseract 3.04.01
leptonica-1.73
libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2`

On Gpu:
`tesseract 3.04.01
leptonica-1.73
libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2`

As you can see both the version is exactly same. If there any suggestion from your side it will be great. By the time I will look into **TesseractOpenCL**.

**Comment by yashkan27** [comment]
Also there is changes in extraction while running in terminal and running in jupyter notebook, although the version of pytesseract is same.

**Comment by int3l** [comment]
I see. So you should try to test by using `tesseract` directly and if there is a difference in the output, that means either that tesseract uses different engine for the recognition (it has multiple of them) or the **tessdata** trained files are different.
