### ISSUE TITLE
Accuracy in line detection

### ISSUE THREAD

**Issue by BartheG** [madmaze/pytesseract#308]
Hi,

I’m currently trying to find blocks of texts using pytesseract BOXDATA, « line_num » and « block_num ». In some cases, lines detected are not accurate (it detects two sentences on the same line but there are actually separated by another line).

I attached a screenshot representing the issue. In this screenshot, I draw boxes around lines detected (based on « line_num » and « block_num »).

![LinesTesseract](https://user-images.githubusercontent.com/32907944/97423116-0ee49f80-190f-11eb-8774-1510e62da50a.png)

Thanks 🙂

**Comment by int3l** [comment]
Did you try to pass the image filename path to pytesseract as string?
Example: `pytesseract.image_to_data("image_filename_path", ...)` - this will bypass pytesseract processing entirely and will let **tesseract** processing only.
Accuracy depends on many factors - image pre-processing, Tesseract engine type, trained tessdata files, language and config settings.

**Comment by BartheG** [comment]
I just tried to pass the path directly to pytesseract, but it outputs the same result... I'm going to check all the config. Thanks for your answer !

**Comment by int3l** [comment]
In that case, this is a **tesseract** related issue - maybe you need better trained data or a more specific one.
Pytesseract just presents the results from tesseract and doesn't modify them, so there is no much that pytesseract can do in this case to improve the accuracy.
