### ISSUE TITLE
Too bad output of OCR

### ISSUE THREAD

**Issue by XtremeGood** [madmaze/pytesseract#310]
![image](https://user-images.githubusercontent.com/40588378/98450967-7ef0f200-2167-11eb-8fc8-2e9d0c42f010.png)

That's the table and I want to extract out the dataframe so that I can perform linear regression on it.

But in the output I only get garbage.

    Code:
    ​
    img = ImageGrab.grabclipboard()
    img = Image.fromarray((np.array(img) * 255).astype(np.uint8))
    df = pytesseract.image_to_string(np.array(img),lang='eng')
    ​
    ​
    ​
    Output:
    ​
    'time 0 3 35 4 45 § rn TS)\nny\nCo 0 0 0.002 0.03 0.155 0.396 0.658 0.903 0.933 09/5 0.993\n\x0c'
    ​
    ​
    ​
    Code:
    img = ImageGrab.grabclipboard()
    img = Image.fromarray((np.array(img) * 255).astype(np.uint8))
    df = pytesseract.image_to_data(np.array(img),lang='eng', output_type='data.frame')
    ​
    Output:
    ​
    	level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text
    0	1	1	0	0	0	0	0	0	572	70	-1	
    1	2	1	1	0	0	0	12	12	541	47	-1	
    2	3	1	1	1	0	0	12	12	541	47	-1	
    3	4	1	1	1	1	0	14	12	525	11	-1	
    4	5	1	1	1	1	1	14	13	29	10	59	time
    5	5	1	1	1	1	2	66	12	3	9	83	0
    6	5	1	1	1	1	3	96	12	6	9	83	3
    7	5	1	1	1	1	4	129	12	17	9	89	35
    8	5	1	1	1	1	5	175	12	7	9	93	4
    9	5	1	1	1	1	6	221	12	17	9	54	45
    10	5	1	1	1	1	7	272	12	6	9	27	§
    11	5	1	1	1	1	8	322	12	17	9	14	rn
    12	5	1	1	1	1	9	384	12	155	9	5	TS)
    13	4	1	1	1	2	0	12	29	32	10	-1	
    14	5	1	1	1	2	1	12	29	32	10	31	ny
    15	4	1	1	1	3	0	12	47	541	12	-1	
    16	5	1	1	1	3	1	12	47	25	12	65	Co
    17	5	1	1	1	3	2	63	48	6	9	83	0
    18	5	1	1	1	3	3	96	48	6	9	84	0
    19	5	1	1	1	3	4	128	48	32	9	87	0.002
    20	5	1	1	1	3	5	175	48	25	9	95	0.03
    21	5	1	1	1	3	6	221	48	32	9	60	0.155
    22	5	1	1	1	3	7	272	48	32	9	93	0.396
    23	5	1	1	1	3	8	322	48	32	9	93	0.658
    24	5	1	1	1	3	9	373	48	32	9	85	0.903
    25	5	1	1	1	3	10	423	48	32	9	92	0.933
    26	5	1	1	1	3	11	474	48	32	9	66	09/5
    27	5	1	1	1	3	12	521	48	32	9	90	0.993

**Comment by XtremeGood** [comment]
https://extracttable.com/    . This site does it very well.

**Comment by int3l** [comment]
Accuracy is not something that pytesseract itself solve for you. Pytesseract is just a wrapper for the tesseract tool.
Please don't spam issue trackers with obvious marketing comments. Thank you.

**Comment by XtremeGood** [comment]
I 'm not marketing anything. I 'm a user and was just asking why is that site giving me good results but not tesseract. But anyways a you said accuracy is not your part.

**Comment by int3l** [comment]
OCR accuracy depends on many factors - image quality (dpi), pre-processing and additional image manipulation, detection/extraction algorithm and engine type, pre-trained data/models, configuration settings and etc.
Pytesseract just forwards data and additional settings to tesseract in a convenient way and gets the result back.

**Comment by XtremeGood** [comment]
> 
> 
> OCR accuracy depends on many factors - image quality (dpi), pre-processing and additional image manipulation, detection/extraction algorithm and engine type, pre-trained data/models, configuration settings and etc.
> Pytesseract just forwards data and additional settings to tesseract in a convenient way and gets the result back.

Thanks for the info @int3l

**Comment by XtremeGood** [comment]
![image](https://user-images.githubusercontent.com/40588378/100848885-c4bf8280-34a7-11eb-97f7-f474afcbdba9.png)

I tried to use the gui version of tesseract. On the top there is a selection OCR model where I selected **hOCR, PDF**  and I got much better results. How can I achieve the following with pytesseract?  I want to load the table into a pandas dataframe.

**Comment by int3l** [comment]
I am not familiar with this software. I guess that they use their own custom version of tesseract or tesseract trained data files.
