### ISSUE TITLE
image_to_string output_type=Output.DATAFRAME returns key error

### ISSUE THREAD

**Issue by becZzZhao** [madmaze/pytesseract#319]
I am trying to return tesseract output as a pandas df, however, I received an error message as copied bellow.

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    output = pytesseract.image_to_string(page, lang='eng',config='--psm 6', output_type= Output.DATAFRAME )
  File "\venv\lib\site-packages\pytesseract\pytesseract.py", line 413, in image_to_string
    }[output_type]()
KeyError: 'data.frame'

The code that I used: 

> output = pytesseract.image_to_string(page, lang='eng',config='--psm 6', output_type= Output.DATAFRAME )

**Comment by int3l** [comment]
You need to use `image_to_data` for `Output.DATAFRAME`

**Comment by becZzZhao** [comment]
> You need to use `image_to_data` for `Output.DATAFRAME`

Hi, thanks for the reply, that solved the issue. From the command line I can use tesseract image_name stdout >filename to directly export output data to .txt file. I was looking for a one-liner in pytesseract that would do the same. Output.DATAFRAME returns box information for each recognized word, which is not quite what I was looking for.
