### ISSUE TITLE
tesseract cli output and pytesseract output diference

### ISSUE THREAD

**Issue by Faith-des** [madmaze/pytesseract#327]
Hello!
I am struggling with understanding why command 
`tesseract table-digit.png output` gives me correct output with all text and digits from the image, but when I try to run it through pytesseract like `python main.py` I am getting good text, but digits as some crazy text.

I will be very grateful if somebody can explain me why this happens and maybe how to fix it.
Because pytesseract is just wrapper for tesseract, then I thought the output must me the same.
Should I set some configurations? I'v tried some like 

OS: Mac OS

TRIED:
```
text = pytesseract.image_to_string(
    image=image,
    config='--oem 1 --psm 3'
    #image, lang='eng',
    # config='digits'
    # config='--psm 13 --oem 3 -c tessedit_char_whitelist=0123456789',
    # config='--psm 11 --oem 3 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    # config= '--psm 3 digits',
    # config= '--oem 3 --psm 6',
    # output_type=Output.DICT
    # config= "--psm 6 digits",
)
```

MAIN.PY
```
image = Image.open("image/table-en2.png")

text = pytesseract.image_to_string(image=image)
print(text)
```

CMD: python main.py
OUTPUT: 
```
Table 1: Salt Concentration and Light Transmittance

Salt Transmittance (%T)

(%) Trial #1 Trial #2 Trial #3 Trial #5

Se
Se
ec
| a |e | nor | soon | eos
sass | vassao | ese | ees | sa

```

CMD: tesseract table-en2.png output
OUTPUT: output.txt
```
Table 1: Salt Concentration and Light Transmittance

 

 

 

 

 

 

 

 

 

 

Salt Transmittance (%T)
Concentration

(%) Trial #1 Trial #2 Trial #3 Trial #4 Trial #5
0 77.23 74.50 64.88 75.27 54.66
3 85.23 92.82 78.91 60.71 57.96
6 88.39 100.05 73.66 66.51 64.54
9 80.71 100.05 68.29 64.91 52.96
12 82.66 117.18 71.01 56.91 46.95
15 72.55 115.40 65.72 66.03 55.38
```

PICTURE:
<img width="797" alt="table-en2" src="https://user-images.githubusercontent.com/45262391/107855722-0e780200-6e35-11eb-84aa-985b616055a2.png">

**Comment by int3l** [comment]
You can try to pass the image path from disk as string instead the PIL Image object, This way you can prevent any implicit conversions of the image that might change the result:

```python
pytesseract.image_to_string('image_path_on_disk', config='...', ...)
```

**Comment by Faith-des** [comment]
It works. Thank you!

But sometimes I need to process some pieces from images.
First get some part of the image (using PIL or OpenCV) where the table and then process it.

PIL images and also OpenCV gives me quite not good result in comparison.

**Comment by Faith-des** [comment]
> Hi @Faith-des
> You can try to pass the image path from disk as string instead the PIL Image object, This way you can prevent any implicit conversions of the image that might change the result:
> 
> ```python
> pytesseract.image_to_string('image_path_on_disk', config='...', ...)
> ```

It works. Thank you!

But sometimes I need to process some pieces from images.
First get some part of the image (using PIL or OpenCV) where the table and then process it.

PIL images and also OpenCV gives me quite not good result in comparison.

**Comment by int3l** [comment]
Well, this is something that pytesseract doesn't provide - you have to pre-process/convert the image in such way that it doesn't alter the end result. Image manipulation including conversion to python objects is tricky, because you can lose/change image information in the process. And you have to do this via custom code on your side.

Closing this one, since it's not a pytesseract specific issue. Feel free to report any other issues.
