### ISSUE TITLE
Path instructions are not very well written

### ISSUE THREAD

**Issue by ramadawn** [madmaze/pytesseract#329]
I found the windows path instructions didn't really work

Better to simply use for an example :  C:\Program Files\Tesseract-OCR

Basically if you just add the above to your path everything works just fine

This is especially true give that this is where the installer places the library by default.

**Comment by int3l** [comment]
Hi @ramadawn !

You can install `tesseract` anywhere you want.
This is why by default `pytesseract` has the `pytesseract.pytessract.tesseract_cmd` set to just `tesseract` and allows you to change that value to whatever you want. So you have two options - either add `tesseract` executable to your PATH or set the `tesseract_cmd` variable explicitly.
