### ISSUE TITLE
Tesseract OCR doesn't work when Python script is converted to exe by pyinstaller without console

### ISSUE THREAD

**Issue by ugurcanakyuz** [madmaze/pytesseract#332]
Hello,

I faced a problem while I have been developing a machine learning solution. When I convert the python solution to the executable via pyinstaller with non-console mode pytesseract was not working. I supposed the problem was related to the pyinstaller but we figured it out actually the problem was in Pytesseract. So I changed the pytesseract code with the feedback that I got.

[This method](https://github.com/madmaze/pytesseract/blob/a7036f8c089250f3fe6f8184ee5cca8b5e89620e/pytesseract/pytesseract.py#L207-L226) was changed to the:
```
def subprocess_args(include_stdout=True):
    # See https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess
    # for reference and comments.

    kwargs = {
        'stdin': subprocess.PIPE,
        'stderr': subprocess.PIPE,
        'startupinfo': None,
        'env': environ,
    }

    if hasattr(subprocess, 'STARTUPINFO'):
        kwargs['startupinfo'] = subprocess.STARTUPINFO()
        kwargs['startupinfo'].dwFlags |= subprocess.STARTF_USESHOWWINDOW
        kwargs['startupinfo'].wShowWindow = subprocess.SW_HIDE

    if include_stdout:
        kwargs['stdout'] = subprocess.PIPE
    else:
        kwargs['stdout'] = subprocess.DEVNULL

    return kwargs
```

So I added `    else:
        kwargs['stdout'] = subprocess.DEVNULL` code.

Then I changed the [method](https://github.com/madmaze/pytesseract/blob/a7036f8c089250f3fe6f8184ee5cca8b5e89620e/pytesseract/pytesseract.py#L377) to the following one:

```
@run_once
def get_tesseract_version():
    """
    Returns LooseVersion object of the Tesseract version
    """
    try:
        return LooseVersion(
            subprocess.check_output(
                [tesseract_cmd, '--version'],
                stderr=subprocess.STDOUT,
                env=environ,
		stdin=subprocess.DEVNULL,
            )
            .decode('utf-8')
            .split()[1]
            .lstrip(string.printable[10:]),
        )
    except OSError:
        raise TesseractNotFoundError()
```

So I added `stdin=subprocess.DEVNULL,` line. I solved the problem. I wonder if these changes will improve pytesseract. I just want to let you know.

More info: https://github.com/pyinstaller/pyinstaller/issues/5601

**Comment by int3l** [comment]
Hi @ugurcanakyuz and thank you for your suggestion/investigation on this issue.
If you want, you can make a pull-request in a feature branch and we will merge the suggested changes if there is no regression after running the tests.
