### ISSUE TITLE
always f"{tesseract_cmd} is not installed or it's not in your PATH."

### ISSUE THREAD

**Issue by qcq** [madmaze/pytesseract#335]
already install the tesseract, always show this, although I added 
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'

I tried in linux, which also can not work,

THE PATH also there C:\Program Files (x86)\Tesseract-OCR\

finally, I know where is wrong, 

for pip install pyte.. which installed the version which should be work for python 3.x,
that means pytesseract not adapt for python27

**Comment by int3l** [comment]
Correct, pytesseract doesn't support Python 2 anymore.
Python 2 is dead - [Sunsetting Python 2](https://www.python.org/doc/sunset-python-2/#:~:text=The%20sunset%20date%20has%20now,when%20we%20released%20Python%202.7.), so you should use Python 3 instead.

**Comment by qcq** [comment]
Thanks for your quick response, but the result is not very glad for me, seems tesseract is not accurate for chinese.
