### ISSUE TITLE
Please Consider to Replace Command-line calling with Library API Level Wrapper

### ISSUE THREAD

**Issue by mo-han** [madmaze/pytesseract#339]
- for performance: much faster
- no tempfile anymore

**Comment by int3l** [comment]
@mo-han hi, and thanks for your suggestion. There is such project already - [tesserocr](https://github.com/sirfz/tesserocr).
Both projects solve different problems, so you can use either of them or both as a user :)
Closing this one since it's not a pytesseract specific issue.
