### ISSUE TITLE
Getting Error TesseractNotFoundError: tesseract is not installed or it's not in your PATH.

### ISSUE THREAD

**Issue by Anubhav1107** [madmaze/pytesseract#342]
I am working in ubuntu 20.4.2, Jupyter notebook.
Python Version is 3.8.5
I tried solving it by following  https://stackoverflow.com/a/52231794, but It doesn't work.

**Comment by int3l** [comment]
Hi @Anubhav1107 
This seems more like a jupyter notebook issue itself or a setup issue with `tesseract-ocr`.

First of all, this error means that `pytesseract` doesn't have access to your `tesseract` executable.
Do you have Tesseract installed on the same system that you have the jupyter notebook setup?
Also what is your operating system?

You can check if you have the `tesseract` directory in your path with:
```python
import sys
for item in sys.path:
    print(item)
```

Keep in mind that this is just a bug tracker for `pytesseract`.
Your question about installation/setup issues belongs to StackOverflow :)

**Comment by Anubhav1107** [comment]
Hey, these are the files by that syntax
/home/stark

```
/opt/ros/foxy/lib/python3.8/site-packages
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/stark/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/IPython/extensions
/home/stark/.ipython

```
I understand but what I can I do to make it accessible.  I am using Ubuntu 20.04

**Comment by int3l** [comment]
Do you have the `tesseract` cli tool/executable available in your terminal?
For example, can you run this command successfully:
```bash
tesseract --version
```

**Comment by Anubhav1107** [comment]
Wow, I used the command and restarted the Pc and it works. Thanks again !
