### ISSUE TITLE
[BUG] Pytesseract doesn't properly support multiframe images (e.g. TIFF)

### ISSUE THREAD

**Issue by mnechita** [madmaze/pytesseract#343]
**Reproduce**:

1. Grab a multiframe TIFF
2. Call `pytesseract.image_to_osd`
3. Output will be only for the first frame (page)

Whereas calling the tesseract process on the image will generate the correct output containing each page.

**Source of the bug:**
When calling `save` on the in-memory data, pillow requires the `save_all=True` parameter  [(pillow docs)](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving-tiff-images) to save multiframe images on the disk. The parameter is not specified, thus the image gets truncated to the first frame.
https://github.com/madmaze/pytesseract/blob/45fe79800b0966c11ac437ab5f6eb355cdc4202f/pytesseract/pytesseract.py#L201

**Possible solution**
Check `Image.n_frames` before saving and set the `save_all` parameter accordingly

I can create a PR with the changes if solution sounds good enough

**Comment by int3l** [comment]
Hi @mnechita and thank you for reporting this bug.
You are welcome to make a PR.

Possible workaround if you don't need the `Image` object -- `pytesseract` also support passing the image as path (`str`).
For example:

```python
pytesseract.image_to_osd('example/image/path.jpeg')
```

I believe that this should still work, because `tesseract` itself can handle multiframe images (or?)

**Comment by mnechita** [comment]
Hey,

Thanks for the reply. Nice suggestion, that actually helps me get around this in the meantime.

Using the path to the image, while `image_to_osd` returns the proper string, when changing the `output_type` to dict, the information will only contain the last frame. This made me realise the `osd_to_dict` function needs to be changed as well. Either with a bigger dict with `page_number` as primary key, or a list of current dicts. However, both these approaches break existing code using the library due to change in structure, unless the function returns different dict structures per case (singlepage/multipage). What do you think?

To confirm, tesseract supports multiframe images, as such, I've attached a sample osd generated from a 9 frame TIFF.
[test_osd.txt](https://github.com/madmaze/pytesseract/files/6342525/test_osd.txt)

Will start working on a PR tonight after work.

**Comment by AjjuSolanki** [comment]
Hello,
I have given one complete Tif file, for almost all pages img_to_data runs fine and gives ocr, but for few pages data in image_to_data returns blank dictionary.
It has no levels, blocks or any text ....blank output.
What could be the possibile reason..
Any help or hint will be appreciated.

Thanks
