### ISSUE TITLE
Pytesseract throws tesseract isn't in the PATH or it's not installed

### ISSUE THREAD

**Issue by codinghedgehog-python** [madmaze/pytesseract#348]
I'm not 100% sure if it's a bug of some kind but you can always close it if this isn't the right place to post this.

I'm working with Pytesseract in one of my routes in my Flask app. The app is currently
running on Linux VM on Google Cloud Platform. Locally, in development I have no issue but
in production environment when I'm passing image to be processed by Pytesseract I'm
getting `tesseract is not installed or it's not in your PATH. See README file for more information.`

in the VM's terminal I check for tesseract:

```
$ tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

so it is installed. Then I added `export PATH=$PATH:/usr/bin/tesseract` to `.bashrc` file and reloaded.

After reloading the app still getting the same error.

The VM is running vanilla Ubuntu 20.04

**Comment by int3l** [comment]
Hi @codinghedgehog-python 
Thank you for reporting your issue.

Can you try this workaround from the documentation:
```python
# If you don't have tesseract executable in your PATH, include the following:
pytesseract.pytesseract.tesseract_cmd = r'<full_path_to_your_tesseract_executable>'
# Example tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract'
```

This allows you to overwrite the actual path for the tesseract executable.
If this also doesn't work -- then I guess that there might be a problem with `pytesseract`.
But all CI tests pass at the moment, so it must be something on your side.

**Comment by codinghedgehog-python** [comment]
I'm on Linux.

**Comment by codinghedgehog-python** [comment]
@int3l  I was surprised to see that even though I'm on Linux specifying `pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'` worked ! My understanding was that is shouldn't be necessary on Linux.
