### ISSUE TITLE
Arabic OCR left to right issue

### ISSUE THREAD

**Issue by diyajunaid** [madmaze/pytesseract#350]
Using Tesseract when PDF is generated with Arabic OCR, there is know issue mentioned [here](https://github.com/tesseract-ocr/tesseract/issues/238)

While using pytesseract does this same issue happens or is it resolved?

This might not be an issue with ptyesseract, so sorry for adding this issue here. But before diving into using pytesseract i wanted to confirm this.

Please guide.

Regards,
Zia.

**Comment by int3l** [comment]
Hi @diyajunaid -- I am not familiar with the Arabic OCR and the training data for that particular language.
You should try it for your particular use case.
