### ISSUE TITLE
Version string not accessible via `pytesseract.__version__`

### ISSUE THREAD

**Issue by jraman** [madmaze/pytesseract#353]
The package version is not accessible via `pytesseract.__version__`.  More info [here][1] and [here][2].

I'm looking at a freshly pip installed version -- the pytesseract version, according to the pip message, is:
```
Successfully installed pytesseract-0.3.7
```

Error:
```
> pytesseract.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a24e830ce97a> in <module>()
----> 1 pytesseract.__version__

AttributeError: module 'pytesseract' has no attribute '__version__'
```

[1]: https://packaging.python.org/guides/single-sourcing-package-version/
[2]: https://martin-thoma.com/python-package-versions/

**Comment by int3l** [comment]
Hi @jraman 
At the moment, pytesseract provides the version only via the `setup.cfg` and it will require additional implementation to support the `__version__` attribute.

**Comment by int3l** [comment]
Fixed by https://github.com/madmaze/pytesseract/commit/03d97de9b20496855ea7d9fa6328d2d0499968de
