### ISSUE TITLE
pytesseract.image_to_pdf_or_hocr() resizes images

### ISSUE THREAD

**Issue by fantasticle** [madmaze/pytesseract#354]
I have an "img.png" sized 2481x3508px @ 300dpi which should give me a paper size of A4 (210x297mm).
When I open this image via the mentioned function and save the output as "img.pdf" the result is 900x1273mm.

```
pdf = pytesseracct.image_to_pdf_or_hocr('img.png')
with open('img.pdf','wb') as write_file:
    write_file.write(pdf)
```

Is there a way that I can keep my image size throughout the OCR process? Also, the metadata gets modified in a funky way. Can anyone help me out here? :+1: 

![2021-05-26_14-02](https://user-images.githubusercontent.com/84633558/119656614-2cd59c80-be2b-11eb-8d69-0dfb267ce3b4.png)

**Comment by int3l** [comment]
Hi @fantasticle 
Unfortunately, this is `tesseract` specific thing. Pytesseract just passes the result from `tesseract` to the user -- in your case, this is the PDF. Maybe there is some kind of tesseract config that can help in regard to that resizing.

**Comment by fantasticle** [comment]
For all of you out there:

pdf = pytesseracct.image_to_pdf_or_hocr('img.png', **config="--dpi 300"**)
with open('img.pdf','wb') as write_file:
    write_file.write(pdf)

This will do the trick!
