### ISSUE TITLE
timeout_manager does not control tesseract timeout properly

### ISSUE THREAD

**Issue by amenezes** [madmaze/pytesseract#355]
pytesseract not raise the exception `RuntimeError('Tesseract process timeout')` correctly in the `image_to_string` function.

For example, the code listed below should raise `RuntimeError('Tesseract process timeout')`, but it is actually occurring `TesseractError(-15, '')`.

image example: https://www.dropbox.com/s/hj2vs5g949348l0/lei.jpeg?dl=0

```python
import pytesseract
import PIL

IMAGE_PATH = 'lei.jpeg'
text = pytesseract.image_to_string(PIL.Image.open(IMAGE_PATH), lang='por', timeout=0.0001)
```

**environment**:
- pytesseract version: `0.3.7`
- tesseract version:
```
LooseVersion ('4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

Would you like me to provided an PR with the fix?

**Comment by int3l** [comment]
Hi @amenezes and thank you for reporting the issue.
Indeed, this seems like a strange issue, since we have test case for that particular scenario.
Feel free to provide PR.
