### ISSUE TITLE
install pytesseract on android 

### ISSUE THREAD

**Issue by mkeyno** [madmaze/pytesseract#365]
I've trying to install pytesseract  on my mobile via pydroid IDE, however, it dumps much error , also using pytesseract  on windows need to run pytesseract.exe file which can not be used on the mobile app 
is there any pure python wrapper that eliminates using another executive file when using this library

**Comment by int3l** [comment]
I'm not aware of such alternative (and especially for Android, which suggests arm64 architecture).
