### ISSUE TITLE
Error when specifying tessdata dir in config

### ISSUE THREAD

**Issue by mgagvani** [madmaze/pytesseract#366]
Hello, 
I have been trying to get Pytesseract working but have encountered this error.
This is my basic script:

```
import cv2
import numpy as np

import pytesseract
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
tessdata_dir_config = r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata\"
img = cv2.imread("screenshots/pic1.png")

print(pytesseract.image_to_string(img,config=tessdata_dir_config))
```
This is the full traceback:
```
Traceback (most recent call last):
  File "d:\misc\ocrtest.py", line 57, in <module>
    print(pytesseract.image_to_string(img,config=tessdata_dir_config))
  File "C:\users\mgagv\.platformio\penv\lib\site-packages\pytesseract\pytesseract.py", line 409, in image_to_string
    return {
  File "C:\users\mgagv\.platformio\penv\lib\site-packages\pytesseract\pytesseract.py", line 412, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\users\mgagv\.platformio\penv\lib\site-packages\pytesseract\pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\users\mgagv\.platformio\penv\lib\site-packages\pytesseract\pytesseract.py", line 249, in run_tesseract
    cmd_args += shlex.split(config)
  File "C:\Users\mgagv\.platformio\python3\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\mgagv\.platformio\python3\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\mgagv\.platformio\python3\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\mgagv\.platformio\python3\lib\shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

Initially, I didn't have the two lines after `import pytesseract`. When I tried to run the script then it said there was no Tesseract installed. (I have installed and reinstalled it multiple times, and verified it is in the correct path). So, I added `pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'`
Then, Tesseract loaded, but it complained it could not find the `tessdata` directory. It is inside the Tesseract-OCR folder and contains all the files. So, I added the tessdata dir config: 
`tessdata_dir_config = r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata\"
`which resulted in a shlex error. 

I'm not sure if this affects anything, but my script is running off an external flash drive while Tesseract is on my C drive. Thanks in advance.

**Comment by int3l** [comment]
Hi @mgagvani ,
you have missing closing quote at the end of this line:
```python
tessdata_dir_config = r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata\"
```

**Comment by mgagvani** [comment]
Thank you for your reply. It looks like I accidentally deleted the last single quote on that line. That line is actually:
`tessdata_dir_config = r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata\"'`

**Comment by int3l** [comment]
Ok, this seems like a weird one. The real problem here is the last backslash in your tess data path.
Try this one instead:
`tessdata_dir_config = r'--tessdata-dir "C:\Program Files (x86)\Tesseract-OCR\tessdata"'`
Shlex gets confused, because it tries to escape the last quote symbol with the backslash ...
