### ISSUE TITLE
Config for different psm values does not work

### ISSUE THREAD

**Issue by kyle-sorensen** [madmaze/pytesseract#39]
When I run `print pytesseract.image_to_string(image, boxes=False, config="-psm 0")`

I get the processed string of the text in the image. However, psm 0 is supposed to only test the orientation. If you run this via the command line, the output should be like this:

```
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
Orientation: 2
Orientation in degrees: 180
Orientation confidence: 0.28
Script: 2
Script confidence: 0.04
```

The code looks like it should be correct, and you have accounted for this, but I do not get the result. I'm not sure what the problem is, I tried to debug it for a few hours. Still trying.

**Comment by int3l** [comment]
Hi @kyle-sorensen,
Please provide sample code and image, so we can reproduce the same test.
Also, let us know, what should be the expected output.
