### ISSUE TITLE
Persian words are mixed with English

### ISSUE THREAD

**Issue by m0binasadi** [madmaze/pytesseract#401]
**this my code** 
```
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract
from langdetect import detect_langs
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
t = pytesseract.image_to_string(Image.open(r"E:\dd\readphoto\source\123.jpg"),lang="eng+fas")
print(detect_langs(t))
print(t)
```

**my photo:**
![123](https://user-images.githubusercontent.com/76769509/145823935-9047beaf-a2d1-4b7f-8fbd-bfc7de6b4ac5.jpg)

**result:**
**[fa:0.9999978843620659]**
خوشبختانه, هنر پاسخ‌هایی ‎dy‏ ما می‌دهد ‎OS‏ بقیه
نمی‌دهند. این شاید حتی بکی از مشخصه‌های
اصلی ادبیات باشد: چیزی را به ما می‌گوید که جامعه
‎job oy‏ کلی آن قدر محتاط است که ‎Oy‏ سراغش
نمیرود. کتاب‌های مهم ‎sul‏ آن‌هایی باشند که باعث
شوند ‎lo‏ در کمال آرامش 9 رضایت خاطرء متحیر
شویم از اینکه چگونه ممکن است نویسنده
درباره‌ی زندگی ما بداند.
     
از کتاب؛ سیر عشق
اثر؛ آلن دو باتن
‎Rangigzangi.cCom‏ ۰

how can fix that?????

**Comment by int3l** [comment]
Hi @m0binasadi ,
this seems like a Tesseract specific issue and not a pytesseract problem.
It seems that you need a better language file.
