### ISSUE TITLE
Using image_to_osd with PIL Image directly does not return results due to temporary file name clashing

### ISSUE THREAD

**Issue by klavdijS** [madmaze/pytesseract#408]
Hey, firstly thanks for the great wrapper around tesseract, makes the usage much more convenient.

Operating system: macOS Monetery 12.1
Tesseract version: 5.0.1

Upon trying to execute image_to_osd with an opened PIL Image, I always get the same result:
`pytesseract.pytesseract.TesseractError: (1, 'UZN file /var/folders/z7/6mpq4jhn3g96kcp8wd5_fzrm0000gn/T/tess__pdgxjh0 loaded. Estimating resolution as 146 UZN file /var/folders/z7/6mpq4jhn3g96kcp8wd5_fzrm0000gn/T/tess__pdgxjh0 loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.`

OSD is never returned.
A short script for reproduction:
```import pytesseract
from PIL import Image
image_to_test = Image.open("out1.png")
osd = pytesseract.image_to_osd(image_to_test)
print(osd)
```
out1.png is a random document with text on it.

Upon further investigation it looks like tesseract tries to open and execute the temporary file which is meant to be used for saving the process output (as seen from the pasted error message).
Temporary saved files in Finder:
![image](https://user-images.githubusercontent.com/15001788/151970386-4c144442-eb94-4b6f-b3d8-2d8b8c699e69.png)
Problematic is the save context manager which creates the temporary files (starting line 188):
```@contextmanager
def save(image):
    try:
        with NamedTemporaryFile(prefix='tess_', delete=False) as f:
            if isinstance(image, str):
                yield f.name, realpath(normpath(normcase(image)))
                return
            image, extension = prepare(image)
            input_file_name = f.name + extsep + extension
            image.save(input_file_name, format=image.format)
            yield f.name, input_file_name
    finally:
        cleanup(f.name)
```
Currently, I fixed it by changing the input_file_name variable to the following:
`input_file_name = f"{f.name}_input" + extsep + extension`

This is also my proposed solution, I believe it does not break anything.

I can create a pull request if needed.

**Comment by klavdijS** [comment]
Hi @int3l.
Yes, I did check, invoking it with tesseract directly works as expected.
Example of a test image:
![test1](https://user-images.githubusercontent.com/15001788/152309282-ab0a5aeb-6851-415f-833f-76fe020c86b6.png)
Running the following command:
`tesseract test1.png out -l osd --psm 0` (generated cmd from image_to_osd)
Produces expected file:
[out.txt](https://github.com/madmaze/pytesseract/files/7993013/out.txt)
Running it with the script provided in the first example produces the reported error.
Yes, I understand I can do that myself - if I provide the path it works as expected. I was trying to do it directly with PIL images since my case involves working directly with them.
I found out in the end that this approach is slower by 30% because of file manipulation, so it probably will not be feasible for me in the end. However, I believe this is not the expected behavior and that is why I reported this.

**Comment by int3l** [comment]
PIL (Pillow) itself does non-lossless conversions for the most part -- this is why there is no way to perfectly avoid such errors.
If you know a workaround, let us know and/or feel free to create PR.

**Comment by bwakkie** [comment]
I have the same problem and did some digging with the tmp files:

I created a watch on the tmp folder and copy the tmp files to a tess_test folder on arrival:
```
inotifywait -m -e close_write /tmp/ | gawk '{print $1$3; fflush()}' | xargs -I % sh -c 'echo %; cp % tess_test'
Setting up watches.
Watches established.
/tmp/tess_rz4bpdjb.PNG
/tmp/tess_rz4bpdjb.osd
/tmp/tess_rz4bpdjb
cp: cannot stat '/tmp/tess_rz4bpdjb': No such file or directory
```
in my flask app I get the following error:

`pytesseract.pytesseract.TesseractError: (1, 'UZN file /tmp/tess_rz4bpdjb loaded. UZN file /tmp/tess_rz4bpdjb loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')`

As you can see the `/tmp/tess_rz4bpdjb` file is created and removed directly before it can be copied while the `/tmp/tess_rz4bpdjb.PNG` file folds my image and the `/tmp/tess_rz4bpdjb.osd` file is empty.

**Comment by int3l** [comment]
Oh, I was looking into the history of pytesseract and it seems to be a regression from 2019.
The problem here is, that I wanted to use the `NamedTemporaryFile` as name generator for filenames and not to actually create the file.

But also, this seems like a deeper problem.
To me, it looks like that pytesseract doesn't wait until the `tesseract` execution ends.
This is one posibility.

The other one is hinted by the actual message: `UZN file loaded` -- tessract is trying to load files without extension as UZN files  ???
And I guess that changing the base filename disables loading the temp file as UZN file.
Can someone test if it makes a difference to changing the 'tess_' prefix into a suffix? @bwakkie or @klavdijS

**Comment by bwakkie** [comment]
I tried your suggestion but no difference:
`line 192:  with NamedTemporaryFile(suffix='_tess', delete=False) as f:`

```
/tmp/tmp5ltmdm2m_tess.PNG
/tmp/tmp5ltmdm2m_tess.osd
/tmp/tmp5ltmdm2m_tess
cp: cannot stat '/tmp/tmp5ltmdm2m_tess': No such file or directory
```

`pytesseract.pytesseract.TesseractError: (1, 'UZN file /tmp/tmp5ltmdm2m_tess loaded. Estimating resolution as 373 UZN file /tmp/tmp5ltmdm2m_tess loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')`
