### ISSUE TITLE
error for the img_to_osd

### ISSUE THREAD

**Issue by Rohinivv96** [madmaze/pytesseract#428]
I am trying to get the orientation of the image and getting the below error:
TesseractError: (1, 'UZN file C:\\Users\\RohiniV\\AppData\\Local\\Temp\\tess_95l0vcop loaded. Estimating resolution as 304 UZN file C:\\Users\\RohiniV\\AppData\\Local\\Temp\\tess_95l0vcop loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')

**Comment by int3l** [comment]
This is fixed in master.
