### ISSUE TITLE
Tesseact Couldn't extract text of specific font 

### ISSUE THREAD

**Issue by YashMistry349** [madmaze/pytesseract#433]
I have document which has many variation across the state and each state document is printed using specific font.

For majority of case tesseract can extract text from the image. But failed for some case like below mentioned example.

**Original Image**

![original](https://user-images.githubusercontent.com/79560917/171796463-2b7cdfd1-8477-4bd7-a38d-03af9711963a.png)

**Pre-processed Image**

![image](https://user-images.githubusercontent.com/79560917/171796538-6915d23f-33b7-4ebf-a36e-f313beed4835.png)

**Cleaned Image**

![image](https://user-images.githubusercontent.com/79560917/171796565-2e004ea5-753d-4aa2-8fd2-841816d3b772.png)

**Tesseract OCR Configuration**

`-l eng --oem 1 --psm 3 -c tessedit_char_whitelist="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\n" load_system_dawg=false load_freq_dawg=false`

**OCR Output**: VEHICLEIDENTIFIGATIONNUMBER\nSNPEUYEF1EHOL992S\n

If I have to support this kind of font what should I do?

**Tesseract Version**: tesseract 5.1.0-32-gf36c0

**Comment by stefan6419846** [comment]
This seems to be unrelated to *pytesseract*, but a general Tesseract/tessdata issue.

Usually you want to generate a fine-tuned model for your specific use case. This could either be done using your own ground-truth files with real-life data (Makefile-based training) or using `tesstrain.py` to generate artificial training data if you have a corresponding font file to work with. (Judging from the number itself, your original image seems to indicate that the used font is OCR-A which is optimized for OCR, but needs fine-tuning from my experience.)

**Comment by YashMistry349** [comment]
Thanks for providing the answer.

However, this solution is not practicable for my use case because I have no idea how many font kinds will be uncounted. The total number of fonts is undetermined.

Is there any other way to deal with this problem?

**Comment by stefan6419846** [comment]
You could try to use the Makefile-based approach to fine-tune the model using your own ground-truth files, but this will still limit you to fonts you have a sufficient coverage for inside your training files. The Tesseract documentation provides some additional write-up on how to improve the quality as well, although this probably will not help much in your specific case: https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html.

As already mentioned, this is no *pytesseract*-specific issue. You might ask for additional support in the Tesseract discussion forum at https://groups.google.com/g/tesseract-ocr/.

**Comment by int3l** [comment]
Closing this one because it is `tesseract` related issue/question and not specific to pytesseract itself.
Thanks for helping other users @stefan6419846
