### ISSUE TITLE
Help Debugging Tesseract

### ISSUE THREAD

**Issue by ambs** [madmaze/pytesseract#435]
Hi. This is more a support ticket than an issue, I think, but... I have a tool that is processing hundred of documents for the last years. But from time to time, I get a single image that is giving problems.

Currently I can't get an interesting answer from Tesseract or Pytesseract. I get a -8 status error code, with an empty error message.

Is there any way for me to get the output produced by tesseract when using it through pytesseract?
Thank you in advance,
ambs

**Comment by stefan6419846** [comment]
Generally speaking, this probably is the wrong place for such a request, as *pytesseract* is just a simple wrapper around Tesseract CLI, whereas the status code most likely yields from the actual Tesseract CLI call which is just being wrapped in https://github.com/madmaze/pytesseract/blob/ea0989dced3f83fac66e94b140ce453ea7bd9009/pytesseract/pytesseract.py#L262-L264 You should probably try to reproduce this issue with plain Tesseract CLI.

If you want to intercept/analyze what *pytesseract* passes to the CLI, have a look at either `pytesseract.pytesseract.run_and_get_output` or `pytesseract.pytesseract.run_tesseract`.

Further analysis might include checking for obvious differences in the documents which works versus which do not work. If you have been able to reproduce this with the plain Tesseract CLI, you should should rather refer to the official forums at https://groups.google.com/g/tesseract-ocr/ or to the issue tracker of Tesseract itself.

**Comment by ambs** [comment]
Hi. Thanks for the answer. Yeah, I know I will need to look to tesseract itself sooner or later, but was trying to get a way to add log messages to the system, so that next time I have such a document I have an idea of what is going on.

Thanks for your pytesseract API suggestions, will look into them.

Cheers and thanks for pytesseract!

**Comment by ambs** [comment]
By the way, negative codes are linux signals. So, -8 is signal 8, thus:  `When the fatal arithmetic operation is wrong. Not only including floating point operations, but also all other arithmetic errors that overflow and divisor are 0.`
