### ISSUE TITLE
Load tesseract engine only once

### ISSUE THREAD

**Issue by peterwa88** [madmaze/pytesseract#436]
When develop a web API, is it possible to load pytesseract engine (model) into memory for the first recognition, then it does not need to reload the model again for the later requests? therefore improves the efficiency for multiple requests (tasks).  Many Thanks!

**Comment by int3l** [comment]
pytesseract doesn't load engines into memory - it is a CLI wrapper around the `tesseract` tool.
You can ask on StackOverflow for alternatives that have such features.
Closing this one, since it's not a specific issue.
