### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HallowedDust5** [madmaze/pytesseract#439]
Hi, I've used this module a few times and every time I have to relearn what shape the data is returned in the main functions like image_to_data. Is there any good documentation that details specifics about these functions?

**Comment by int3l** [comment]
Unfortunately, there is not much documentation for that - the current README is all we have.
`pytesseract` output depends on tesseract, so it might be better to check the tesseract documentation itself.
Yes, we can duplicate the documentation from tesseract, but once the output format changes, this duplicate information have to be updated and discrepancies might happen at any point.

So my advice is to check what `tesseract` provides itself. `image_to_data` also follows the tesseract output as well.
