### ISSUE TITLE
Pytesseract: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2: character maps to <undefined>

### ISSUE THREAD

**Issue by dickreuter** [madmaze/pytesseract#44]
What can I do about this error message in python 3? It happens from time to time and it should not throw an exception.

Pytesseract.image_to_string(image,None, False, "-psm 6")
Pytesseract: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2: character maps to <undefined>

**Comment by vanjavk** [comment]
happens to me too sometimes

**Comment by dickreuter** [comment]
Yes that error should now have been eliminated. Did you Rebase recently?

**Comment by vanjavk** [comment]
What does rebase means? I just installed pytesseract so I should have latest version, I also tried updating Pillow but it said there's no updates available

**Comment by dickreuter** [comment]
Sorry I confused you with somebody else. Yes the problem is still there. I
just put all calls to pytesseract into try except. Didn't find any better
solution.

**Comment by chicocvenancio** [comment]
It seems to me this is related to #26 and would be solved by PR #33

**Comment by gfgilmour** [comment]
Hi: I'm still getting the UnicodeDecodeError . I'm running on windows 10 with python 3.6 ,reinstalled pytesseract 0.1.6 , but still getting the error consistently . attached is a sample jpg. thanks
![2400336-docc2400336](https://cloud.githubusercontent.com/assets/29029196/26533418/b04a660e-43e6-11e7-9660-ac897dc6a40e.jpg)

**Comment by int3l** [comment]
@gfgilmour please install the [0.1.7 version](https://github.com/madmaze/pytesseract/releases/tag/v0.1.7) from github, since the current pip package is 0.1.6.

**Comment by dickreuter** [comment]
The error still occurs with 0.1.7

**Comment by int3l** [comment]
@dickreuter Please provide us with the following information:
1. OS name and version.
2. python version
3. sample code snippet + sample file that produce the error.

Thanks for reporting the issue.

**Comment by dickreuter** [comment]
In fact the error is not from pytesseract itself but by what it returns. I'm unable to write the output.

**Comment by int3l** [comment]
@dickreuter It is encode/decode related problem.
You may need to use utf-8, because it seems that the tesseract executable uses that as output.
