### ISSUE TITLE
 pytesseract.image_to_string

### ISSUE THREAD

**Issue by Hashininirasha** [madmaze/pytesseract#442]
import pytesseract
print(pytesseract.image_to_string(plate, config="--psm 6"))
This is a code and when im run it, it shows err like this 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-44-cf758bb39569>](https://localhost:8080/#) in <module>()
      1 import pytesseract
----> 2 print(pytesseract.image_to_string(plate, config="--psm 6"))
      3 
      4 

5 frames
[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in save(self, fp, format, **params)
   2121         expand=0,
   2122         center=None,
-> 2123         translate=None,
   2124         fillcolor=None,
   2125     ):

KeyError: 'PNG'

**Comment by int3l** [comment]
Hi @Hashininirasha - thank you for reporting this bug.
Which version of pytesseract do you have?
Also, can you share your OS version and sample image that produce the error?
