### ISSUE TITLE
Handling multi-page tiffs

### ISSUE THREAD

**Issue by therockmandolinist** [madmaze/pytesseract#45]
Was attempting to use this with a multi-page tiff, but because of how `Image.open()` works, only the first page is turned into a string. 

So I tried looping over `n_frames` using the `seek()` method, but was unsuccessful because pytesseract closes the image, so `seek()` throws `ValueError: seek of closed file`. 

Perhaps `pytesseract.py` should check for `n_frames`, and convert the entire file by using the `seek()` method before closing? (Or at least offer that option). 

As an example of what I was trying:

```
img = Image.open('path/to/my/img')
raw = ''
for i in range(img.n_frames):
    img.seek(i)
    raw+=pytesseract.image_to_string(img)
```

**Comment by therockmandolinist** [comment]
I actually don't think I have a very good understanding of what's happening here, because the following code does work, though it seems similar enough to me:

~~~
img=Image.open('path/to/my/img')
for i in range(img.n_frames):
    img.seek(i)
    print(pytesseract.image_to_string(img))
~~~

I can print the string, but not append it to another without `ValueError: seek of closed file`. Weird.

**Comment by therockmandolinist** [comment]
Final comment: this is probably an issue with pillow, not pytesseract. Either way, would be nice to have the option for multipage files. :)

**Comment by kaumaron** [comment]
I know the issue is closed but I wanted to add this for anyone else looking for it. @dieggsy inspired me to try iterating over each frame and just passing a single frame to `pytesseract`:

**Print text:**
```
from PIL import Image, ImageSequence

with Image.open('path/to/image') as img:
    for frame in ImageSequence.Iterator(img):
        print(pytesseract.image_to_string(frame))
```
**Write to File:**
```
from PIL import Image, ImageSequence

with open('txtfile.txt', 'wb') as file:
    # on a Windows system hence 'rb'
    
    with Image.open('path/to/image') as img:
        for frame in ImageSequence.Iterator(img):
            file.write(
                pytesseract.image_to_string(frame).encode('utf-8')
               )
```
