### ISSUE TITLE
CMD windows

### ISSUE THREAD

**Issue by vanjavk** [madmaze/pytesseract#46]
While running this python keeps opening CMD windows http://i.imgur.com/pWI3JDW.png
How to prevent this ?

**Comment by vanjavk** [comment]
i changed from  
    
    proc = subprocess.Popen(command,
            stderr=subprocess.PIPE)
    return (proc.wait(), proc.stderr.read())


to 


    SW_HIDE = 0
    info = subprocess.STARTUPINFO()
    info.dwFlags = subprocess.STARTF_USESHOWWINDOW
    info.wShowWindow = SW_HIDE
    proc = subprocess.Popen(command,
            stderr=subprocess.PIPE, startupinfo=info)

in pytesseract.py and fixed this!

**Comment by int3l** [comment]
Thanks for your feedback @vanjavk, there is a pull request for this behavior.
I will try to merge the two solutions into one generic fix.

**Comment by int3l** [comment]
Will be addressed with pull request #41. You can use the code from it until we release the next version.
Please feel free to reopen if you want.
