### ISSUE TITLE
Subprocess not working on iis server

### ISSUE THREAD

**Issue by karthikchowkula** [madmaze/pytesseract#462]
hello,iam using subprocess,when i sent request through postman using local server ,subprocess is working,but when im sending request using iis server ,subprocess is not working

**Comment by stefan6419846** [comment]
Despite the fact that your description is quite sparse, I do not think that this really is related to the library itself, but due to your setup.

**Comment by karthikchowkula** [comment]
stefan6419846,using subprocess im running another enviroment ,so from local it is working properly,but through iis is working

**Comment by stefan6419846** [comment]
Then please elaborate a bit more on what you are trying to achieve and how and what fails there exactly.

**Comment by karthikchowkula** [comment]
stefan im using two enviroments ,in second enviroment we are trying to access model file all related  packages of model are there in one environment,in first enviroment im using all related things to backend like getting data from frontend.now what im doing here i will get pdf from frontend,i need to send that file path  to second enviroment from first enviroment,im using subprocess to open enviroment and sending path..

but i got this error  Popen: returncode: None args:

**Comment by stefan6419846** [comment]
This still sounds like something which requires a deeper knowledge of your setup and is a general issue instead of a *pytesseract*-specific one.

**Comment by karthikchowkula** [comment]
stefan, i got return code none args

**Comment by stefan6419846** [comment]
I am repeating myself: Without further knowledge of your setup and actual details from you, there is not much we can do here on the *pytesseract* side, so please provide a sufficient amount of details to actually let us understand your issue.

Do you have some reproducing code and some description of what you are doing in some more detail than your short comments? (At the moment, I am not even sure if you get a subprocess error from your own call (which we do not have any influence on) or from *pytesseract* calls for example.)
