### ISSUE TITLE
Numbers only

### ISSUE THREAD

**Issue by IbenBru** [madmaze/pytesseract#465]
So i'm wondering if it's possible to only recognize numbers and ignore letters? I've searched everywhere and all I can find is that it isn't, and when you try to whitelist it trough the config, that it doesn't work. I've tried the last part, but it's completely messed up. What am I missing?

**Comment by IbenBru** [comment]
Input is an image that has been resized, denoised, had a grey filter and was turned in black and white. result: 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/112083967/204825631-e2a54fa3-8926-4377-b462-71ba69084bfa.png">

doing the following gives "6":
data = pytesseract.image_to_string(255 - img, lang='eng',config='-c tessedit_char_whitelist=0123456789 --psm 10 -l osd')
print(data)

Having tried different segmentation modes returns, results, but they don't even remotely look like what i need. psm 6 for example gives "5890097"

**Comment by stefan6419846** [comment]
Your first example does not make much sense, as the OSD model just performs "orientation and script detection" - and no actual character detection.

Regarding the page segmentation modes: I usually prefer to use 8 for multi-digit numbers like this, but this is just based on my experience.

Nevertheless, *pytesseract* will never have any direct influence on this, as it is just a wrapper around the Tesseract cli itself. If Tesseract performs bad, *pytesseract* cannot do much about it. For this reason, your request seems to be out of scope here. You might want to try further examples or some different preprocessing which might perform better (or re-train a Tesseract model yourself).

**Comment by IbenBru** [comment]
Alright, gonna have to dive deeper then. Thanks for the fast responses regardless
