### ISSUE TITLE
image_to_string is ignoring numbers at the beginning of 4th column

### ISSUE THREAD

**Issue by dorisviv** [madmaze/pytesseract#470]
image_to_string works great for the first 3 columns, then ignores leading numbers in the 4th column.

print(pytesseract.image_to_string('inFiles\page80.png'))

Please see attached image file and output.
<img width="1528" alt="page80" src="https://user-images.githubusercontent.com/11757112/214692441-1fc6ae55-401f-4988-bd94-2045ad8fc855.png">
[imgToStringPng.txt](https://github.com/madmaze/pytesseract/files/10503733/imgToStringPng.txt)

Thanks,
Doris

**Comment by stefan6419846** [comment]
Generally speaking, this is no issue with *pytesseract* (being only a thin wrapper around the Tesseract CLI), but with Tesseract itself, as you can verify with `tesseract image.png stdout -l eng`.

To fix this, you might try with different page segmentation modes (`tesseract --help-psm`). Further pre-processing might work as well, although running Tesseract on the last column only (`convert -crop 75%x100% image.png last.png && tesseract last-1.png stdout -l eng`) yields the same results for me, so you might have to come up with a more sophisticated solution.

**Comment by dorisviv** [comment]
Danke Stefan, das mach' ich.
Doris
