### ISSUE TITLE
image_to_data returns comma as unicode chr(8218) 

### ISSUE THREAD

**Issue by kwiechen** [madmaze/pytesseract#471]
image_to_data returns strings with comma (,) characters as unicode decimal 8218 and not decimal 44. 

The decimal 8218 character cannot be removed by str.replace(",", "") or re.sub().

**Comment by stefan6419846** [comment]
It seems like Tesseract has been trained on both types of comma and for this reason predicts either one. As *pytesseract* just is a thin wrapper around the Tesseract CLI, there is not much we can do here. Replacing similar character codes with the most common one and thereby altering the output does not seem to be a valid approach either, as for some use cases there might be the need to distinguish them.

For this reason, you are basically left with improving your post-processing to include such similar characters as well if you consider them equal. Additionally, you might want to try if an explicit list of allowed characters is suitable in your case and makes Tesseract CLI return the exact characters only (option `config=r'-c tessedit_char_whitelist="0123456789,"'`, where the actual configuration value might have to be adapted for your use case). As you do not want the comma character to appear in your output, specifying the list of allowed characters which does not include the comma itself would work as well.
