### ISSUE TITLE
Adding tessedit_write_images=1 to option doesn't generate 

### ISSUE THREAD

**Issue by teisseire117** [madmaze/pytesseract#472]
Hi,

I'm reading this : https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html and it says : 
```
You can see how Tesseract has processed the image by using the [configuration variable](https://tesseract-ocr.github.io/tessdoc/ControlParams) tessedit_write_images to true
```

So I write in my python script the following :
```
text = pytesseract.image_to_string(image, config='--psm 6 tessedit_write_images=1 ')
```
But I don't see the resulting tessinput.tif file being generated. It doesn't generate an error either

**Comment by stefan6419846** [comment]
You are missing the `-c` parameter definition at the moment. It should read

```python3
text = pytesseract.image_to_string(image, config='--psm 6 -c tessedit_write_images=1 ')
```

instead. The `tessinput.tif` file will be generated in the current working directory in this case.

**Comment by teisseire117** [comment]
> You are missing the `-c` parameter definition at the moment. It should read
> 
> ```python
> text = pytesseract.image_to_string(image, config='--psm 6 -c tessedit_write_images=1 ')
> ```
> 
> instead. The `tessinput.tif` file will be generated in the current working directory in this case.

Mmh, I added the -c but it doesn't generate anything either

**Comment by stefan6419846** [comment]
Are you looking into the right directory, id est into `os.getcwd()`?

**Comment by teisseire117** [comment]
> Are you looking into the right directory, id est into `os.getcwd()`?

Positive, 100%

**Comment by stefan6419846** [comment]
Does running plain Tesseract with `tesseract --psm 6 -c tessedit_write_images=1 image.png stdout` generate the file?
