### ISSUE TITLE
TypeError expected str, bytes or os.PathLike object, not tuple

### ISSUE THREAD

**Issue by kennyhml** [madmaze/pytesseract#475]
Hello. I have been using my program for months and it has been totally fine, then today all of sudden, everywhere I use tesseract I get this error, its an internal error, not one caused by my arguments. Here is the full traceback

```py
image = Image.fromarray(prepared)
image.save("test.png")

raw_result = tes.image_to_string("test.png", config="--psm 6 -l eng")
```
causes (alongside any other attempt to use the function)

```
proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1380, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\shock\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 563, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\os.py", line 823, in fsdecode
    filename = fspath(filename)  # Does type-checking of filename.
```

**Comment by stefan6419846** [comment]
Are you sure this is the complete stacktrace? We should at least have some *pytesseract* code here.

**Comment by kennyhml** [comment]
> Are you sure this is the complete stacktrace? We should at least have some _pytesseract_ code here.

For some reason i didnt copy paste the entire thing, but I just resolved it anyways, I was using "replace all" and somehow `tesseract_cmd = config.tess_path` became `= config, config.tess_path` so entirely my fault. Took me 2 hours to finally spot though, would have loved a more concrete error or just type hinting the `tesseract_cmd` so a linter could have spotted it would be amazing. Sorry for the dumb issue
