### ISSUE TITLE
Find the probability of correctness and top 10 most probable characters.

### ISSUE THREAD

**Issue by isaackatayev** [madmaze/pytesseract#478]
Hi,

I am using Pytesseract to find the top 10 most probable results for a Chinese image to text OCR.
This issue has been solved for Tesseract [here](https://stackoverflow.com/questions/68275031/is-there-a-way-to-get-possible-characters-for-a-image-containing-single-charact) but I can't figure out how to get this working in Pytesseract. 

[Another useful link](https://github.com/tesseract-ocr/tessdoc/blob/main/APIExample.md#example-of-iterator-over-the-classifier-choices-for-a-single-symbol)

Thanks for your help

**Comment by stefan6419846** [comment]
As mentioned inside the above Stackoverflow link, Tesseract does not seem to provide this functionality in its CLI. As *pytesseract* uses the CLI only, there is nothing we can do here.

You might try to use `tesserocr` instead, which provides direct C++-level bindings for the Tesseract API to Python.

**Comment by isaackatayev** [comment]
> You might try to use `tesserocr` instead, which provides direct C++-level bindings for the Tesseract API to Python.
Thank you, this helped.
