### ISSUE TITLE
How to improve pytesseract accuracy

### ISSUE THREAD

**Issue by similang** [madmaze/pytesseract#479]
I have seen cases where I could see the words clearly in the image by no word detected. What's the issue? What would be recommended image processing methods except those listed in the official site (I have tried them all). Thanks.

**Comment by stefan6419846** [comment]
This is the wrong place to ask such questions and better suited for Stackoverflow or the Tesseract Users Google Group, as *pytesseract* basically is a thin wrapper around the Tesseract CLI itself.

Nevertheless, there is no general solution for improving the quality, as this highly depends on the use-case and inputs. Maybe the bad examples share some common pattern. Maybe the pre-processing can be improved. Maybe the quality can be improved by fiddling with the parameters (like the page segmentation mode, maybe combined with additional pre-processing, or the list of expected characters). Maybe re-training the model for a specific font helps. You will always have to take your specific domain into account.

**Comment by similang** [comment]
I see. Thanks for the advice anyways.
