### ISSUE TITLE
output_type=pytesseract.Output.STRING still provides bytes object

### ISSUE THREAD

**Issue by aarav2you** [madmaze/pytesseract#485]
Changing the `output_type` parameter for the `image_to_string` still provides bytes object, even though `pytesseract.Output.STRING ` is the default

**Comment by stefan6419846** [comment]
Please provide some more details for us to be able to reproduce this, as I cannot see any issue here:

```python3
>>> pytesseract.image_to_string(image)
'This is my text.\n\x0c'
>>> pytesseract.image_to_string(image, output_type=pytesseract.Output.STRING)
'This is my text.\n\x0c'
>>> pytesseract.image_to_string(image, output_type=pytesseract.Output.BYTES)
b'This is my text.\n\x0c'
>>> 
```

**Comment by aarav2you** [comment]
Somehow it was a problem with my IDE? I updated it and it got rid of the problem
