### ISSUE TITLE
Boxes of images (within text)

### ISSUE THREAD

**Issue by ksbbf** [madmaze/pytesseract#489]
dear all, 

sry, if my question is probably offtopic: I'm looking for a method to get from tesseract (or its components) informations about recognized non-textual regions. e.g. images. As far as I understand it right, pytesseract's methods return text informations only, right?

Could anyone give me a hint to that?

btw: The recognition of text works perfectly for. Thanks for your efforts!

**Comment by stefan6419846** [comment]
As *pytesseract* just calls the Tesseract CLI, there is not much we can do here unless Tesseract provides access to such data (which I am not aware of). I think the general Tesseract discussion group at https://groups.google.com/g/tesseract-ocr is much more suitable here.

**Comment by ksbbf** [comment]
ok! Thanks for your answer
