### ISSUE TITLE
Spaces and Dots

### ISSUE THREAD

**Issue by Fivalt126** [madmaze/pytesseract#492]
The only problem that I still have to solve is that it does not recognize some spaces and dots, I tried with post processing, but it greatly increases the execution time of the program, I would like to know if there is any way to modify the parameters that make it recognize when it is a space and when not, the same for dots.

Felipe.

**Comment by stefan6419846** [comment]
This greatly depends on what you are actually trying to achieve, but nevertheless this is out of scope for *pytesseract* and should be asked on the general Tesseract mailing list. You might want to try the character whitelist configuration, but this only works if you are only interested in a (small) subset of the full character set.
