### ISSUE TITLE
Python 3.11.4 changes the output of image_to_data

### ISSUE THREAD

**Issue by aaloginov** [madmaze/pytesseract#500]
Noticed that with Python 3.11.4 the output from `image_to_data()` is different from the one with Python 3.11.1-3.11.3.
Confidence becomes float and bbox coordinates are different.

Example (run on the same file in docker with 3.11.3-slim and 3.11.4-slim):
`['1009', '2104', '86', '28', '96.295052', '50.00']` -3.11.4
`['1009', '2099', '86', '44', '96', '50.00']` - 3.11.3

**Comment by stefan6419846** [comment]
Could you please check whether in both cases the same Tesseract build is being used? In general, as Tesseract uses machine learning, you might even get different results for each run.

**Comment by aaloginov** [comment]
Hi,
Thank you for the fast response!
I think that Tesseract build is the same, the only thing I change is minor Python version in dockerfile (`FROM python:3.11.4-slim` and `FROM python:3.11.3-slim`). 
The confidence output was int all the time before (with 3.11.1, .2, .3) and it became float right after switching to 3.11.4.

**Comment by stefan6419846** [comment]
Could you please check the plain Tesseract output without post-processing in both cases?

**Comment by aaloginov** [comment]
So you were actually right with the initial guess about Tesseract builds. Seems like `apt update && apt install -y tesseract-ocr` was grabbing different Tesseract versions with different python-slim base images (tesseract 4.1.1 with 3.11.3 and tesseract 5.3.0 with 3.11.4).
Thank you for your help and attention and my apologise for the mess!
