### ISSUE TITLE
Update PyPI package to pytesseract v0.3.13

### ISSUE THREAD

**Issue by bozhodimitrov** [madmaze/pytesseract#507]
Hi @madmaze
Please update whenever you have time. Thanks in advance!

**Comment by mgorny** [comment]
Ping.

**Comment by miketrimmel** [comment]
ping

**Comment by tiborrr** [comment]
You can use `pip install git` as temporary work around.

Either run 
`pip install git+https://github.com/madmaze/pytesseract.git@v0.3.13`

Or add 
`git+https://github.com/madmaze/pytesseract.git@v0.3.13`

to your `requirements.txt`

**Comment by a2800276** [comment]
Hi @madmaze, it would be great if we could get an update, or at least let us know if you lost interest in the project. Thank you!

**Comment by madmaze** [comment]
Thanks for everyone's patience, I've just pushed out v0.3.13 :tada:
