### ISSUE TITLE
Doesn't fully recognize my image

### ISSUE THREAD

**Issue by snapsnapsnapsnap** [madmaze/pytesseract#51]
![image](https://cloud.githubusercontent.com/assets/24880308/21753070/fdbf7cc0-d5ec-11e6-986d-41f588d7c2ad.png)

Hey guys! I am pretty new at programming Python so take it easy with me please! I have an image provided above and if I use:

    print pytesseract.image_to_string(img)

it returns:
 
    Rggimantasih

Which is pretty close but as you can guess not fully accurate. 

I tried converting image to black and white/grayscale but that did not help. Image and letters seem pretty clear maybe you can help me out here? Thanks in advance!!

**Comment by int3l** [comment]
@snapsnapsnapsnap this is a problem with the Google's Tesseract OCR Engine itself.
Pytesseract doesn't alter the actual result from the engine, so you should address your problem to the Tesseract Engine project.
