### ISSUE TITLE
image_to_data default output type is string

### ISSUE THREAD

**Issue by karladler** [madmaze/pytesseract#510]
Not sure if this can be updated without breaking backwards compatibility, but I got really confused, that the output type for `image_to_data()` function is actually string. Regarding to the function name IMHO it should be `data.frame`.

**Comment by stefan6419846** [comment]
This is documented explicitly: https://github.com/madmaze/pytesseract/blob/8ae8f2b80c78354ea86dd94ebb8bcd8072d2857c/pytesseract/pytesseract.py#L526-L529

You still can choose between the different representations. I assume that `data.frame` is not the default as *pandas* is an optional dependency, thus this might fail.

**Comment by int3l** [comment]
Are you talking about the image_to_data and the has specific parameter for that one. Please check the docs about the [pytesseract.Output](https://github.com/madmaze/pytesseract/blob/b35f0611a9d21564a0f8a0138096d8c7053360c3/pytesseract/pytesseract.py#L72) class
