### ISSUE TITLE
Deprecation warning raised in python 3.12

### ISSUE THREAD

**Issue by plokmijnuhby** [madmaze/pytesseract#519]
Importing the module calls pkgutil.find_loader, which as of python 3.12 is deprecated.

It appears this function is called purely to determine whether certain modules are available. This can be achieved in python 3.12 by instead attempting to import the module, and catching ModuleNotFoundError exceptions.

**Comment by stefan6419846** [comment]
Do you want to submit a corresponding PR to test against Python 3.12 as well and add the mentioned fix?
