### ISSUE TITLE
PyTesseract cannot read my number

### ISSUE THREAD

**Issue by matheustecchio** [madmaze/pytesseract#538]
![PROCESSED-2024-02-27](https://github.com/madmaze/pytesseract/assets/52295230/4f5a2b73-d82e-44f5-9e2d-cddb58b7a84b)

I'm trying to read this number with pyTesseract, but it can't read the number 1 in 351.

How can I fix it? All the value that I want are numbers.

**Comment by stefan6419846** [comment]
Please provide the corresponding *pytesseract* code you are using. You might want to play with `tessedit_char_whitelist` and the PSMs (page segmentation modes).

Nevertheless, *pytesseract* will never have any direct influence on this, as it is just a wrapper around the Tesseract CLI itself. If Tesseract performs bad, *pytesseract* cannot do much about it. For this reason, your request seems to be out of scope here. You might want to try further examples or some different preprocessing which might perform better (or re-train a Tesseract model yourself).

**Comment by matheustecchio** [comment]
Hi Stefan, alright, thank you for your reply.
I find out that I probably will need to re-train my Tesseract model as the problem is the model itself.
I'm closing this issue as is out of scope.
