### ISSUE TITLE
NPM can't find Tesseract OCR even though it's installed and I can't update git

### ISSUE THREAD

**Issue by HarryDaWin** [madmaze/pytesseract#544]
$ npx react-native init testing123
npm ERR! code ENOENT
npm ERR! syscall spawn C:\Program Files\Tesseract-OCR;
npm ERR! path C:\Users\harri
npm ERR! errno -4058
npm ERR! enoent spawn C:\Program Files\Tesseract-OCR; ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

git update
Warning! `git update` has been deprecated;
Please use `git update-git-for-windows` instead.
Git for Windows 2.37.1.windows.1 (64-bit)
Update 2.45.0.windows.1 is available
Download and install Git for Windows v2.45.0.windows.1 (killing one Git Bash) [N/y]? y
################################################################################################################ 100.0%
/usr/bin/start: line 8: C:\Program Files\Tesseract-OCR;: No such file or directory

**Comment by stefan6419846** [comment]
*pytesseract* is the Python package and not related to NPM/Javascript.
