### ISSUE TITLE
pytesseract.image_to_osd() error

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [madmaze/pytesseract#549]
Config - python3.10
Ubuntu - 22.04
pytesseract - 0.3.10
opencv - 4.5.4.60
tesseract-ocr engine - 4.1.1

Those are my configurations, I have correct orientation image, there is not rotation needed for that image. In my local machine its working fine. 

Same, configuration other machine have issue, the image is rotated 180 degree

why?

**Comment by stefan6419846** [comment]
Please ensure that both Tesseract and tessdata versions are identical. Additionally, please verify whether a direct Tesseract call already shows this behavior. As long as plain Tesseract shows this behavior as well, this is not related to *pytesseract* and should be discussed in the Tesseract user forums.

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
Thanks a lot for the reply stefan sir.

But, still i am facing error.

python:
tessdata - 1.0.0
pytesseract - 0.3.10

bash:
tesseract version:

tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8

**Comment by stefan6419846** [comment]
What do direct Tesseract calls without *pytesseract* yield on both devices? If the results differ there already, there is nothing to be done with *pytesseract* as already mentioned in my previous comment.
