### ISSUE TITLE
get_languages() does not return languages that have numbers in the name.

### ISSUE THREAD

**Issue by KaipaUday** [madmaze/pytesseract#552]
Hi, 
There is strange issue, when use the get_languages(), it only returns some languages.
```

>>> from pytesseract.pytesseract import *
>>> get_languages()                         
['bhu', 'eng', 'lets']
```

when i try in cmd or powershell.
```
PS C:\Users\xxxxT\Desktop\XXXX> tesseract --list-langs
List of available languages in "C:\Users\xxxxT\AppData\Local\Programs\Tesseract-OCR/tessdata/" (6):
7seg
bhu
bhu32_7seg
bhu32_eng
eng
lets
```

**Comment by stefan6419846** [comment]
These are currently being filtered, introduced in #312: https://github.com/madmaze/pytesseract/blob/c8359454aabb47eeb0360f7017ba58a786366a4e/pytesseract/pytesseract.py#L51
