### ISSUE TITLE
Tesseract image_to_osd error

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [madmaze/pytesseract#560]
The OSD functionality is not working properly

If the image need 90 degree rotation, But the OSD returns 0.0.
How to fix this error.

versions:
Name: pytesseract
Version: 0.3.13
Summary: Python-tesseract is a python wrapper for Google's Tesseract-OCR
Home-page: https://github.com/madmaze/pytesseract
Author: Samuel Hoffstaetter
Author-email: samuel@hoffstaetter.com
License: Apache License 2.0
Location: /home/bolt1/adk_workspace/quant_env/lib/python3.10/site-packages
Requires: packaging, Pillow

tesseract --version
tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8

Actually, this image has a correct possition, but the tesseract ocr rotates 180*

![Screenshot from 2024-11-26 08-38-07](https://github.com/user-attachments/assets/e57e7ec6-5186-4f30-8873-e7997c7f8bbc)

**Comment by bozhodimitrov** [comment]
This question is more appropriate for a [StackOverflow](https://stackoverflow.com/) question and community. Please use the issue tracker for problems related to the python package itself.
