### ISSUE TITLE
Failure on MacOS with supervisord

### ISSUE THREAD

**Issue by oditorium** [madmaze/pytesseract#562]
On MacOS 15.1.1 with the latest installs with homebrew and supervisor, pytesseract fails with an error about not being able to read an input file. The error message is like this

```
OCR failed [(1, 'Error in fopenReadStream: failed to open locally with tail
 tess_pqyhbx6k_input.JPEG for filename /tmp/tess_pqyhbx6k_input.JPEG 
Leptonica Error in findFileFormat: image file not found: /tmp/tess_pqyhbx6k_input.JPEG 
Error in fopenReadStream: failed to open locally with tail ���� for 
filename ���� Leptonica Error in pixRead: image file not found: ���� 
Image file ���� cannot be read! Error during processing.')]
```

(actually due to #561 the error message is about some unicode errors, you get this once you apply the patch in #561).

The issue seems to be that `/tmp` under the latest MacOS is not a valid temp directory. Eg in a shell you would find the following

```
% echo $TMPDIR
/var/folders/v7/hw7l3ry540b....
```

However, `supervisord` does not have this variable (it is apparently set by `launchd` and supervisor starting as `root` and then switching users does not get it set properly.

The workaround here to use
```
export TMPDIR=/path/to/valid/temp
```
somewhere before the service is launched. However -- maybe there is something smarter that can be done when choosing the temp directory and making sure it is indeed valid.

I cannot find the code anymore but essentially `/tmp` is one of the default directories that is added when no environment variables are set. Either those tests need to be better, or current directory may be a better default.

**Comment by stefan6419846** [comment]
*pytesseract* uses the `tempfile` module of the Python stdlib, thus its your task as the application developer (or the task of the runner) to set the appropriate environment variable. The upstream documentation is available at https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir
