### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by yeguixin** [madmaze/pytesseract#58]
I installed pytesseract by pip. But when importing pytesseract, it occurs the errors "ValueError: Attempted relative import in non-package". I correctly installed tesseract. The python version is 2.7, tesseract 3.04.01. I don't konw how to do.

**Comment by int3l** [comment]
What is the operating system that you use?
And please provide sample snippet with the code that raises the error.

**Comment by yeguixin** [comment]
The OS is Ubuntu, runing on the VM.  When I just import pytesseract, the error coours. But when I do the same operations in another Ubuntu, VM. The error disappears. I don't know why?

**Comment by int3l** [comment]
Can you please post the output of the following terminal command on the both machines:
`$ pip freeze`

**Comment by int3l** [comment]
Closing this one, since it could be a configuration issue or missing dependency.

**Comment by dsouzaankit** [comment]
I resolved this error by deleting/commenting 'try: import Image except...' in pytesseract.py
