### ISSUE TITLE
question about text recognise with digits and letters

### ISSUE THREAD

**Issue by shouwei** [madmaze/pytesseract#61]
hi there,

I have a feature request to recognize a bunch of verification codes with Tesseract-ocr, and I used  pytesseract.

It works perfectly for an image with only letters. However, if the image consists of both digits and letters, the output always wrong. Is there any solution to increase quality for this scenario? Or can is that possible to involve some supervised process to improve accuracy. 

Attachment is a false example for recognization and the output is "N 3U’7V".

Here is the code:

    import sys
    from pytesseract import image_to_string
    from PIL import Image
    im = Image.open(sys.argv[1])
    im = im.convert('L')

    def initTable(threshold=140):
    table = []
        for i in range(256):
        if i < threshold:
            table.append(0)
        else:
            table.append(1)

    return table

    binaryImage = im.point(initTable(), '1')
    binaryImage.show()

    print(image_to_string(binaryImage, config='-psm 7'))
![n3u7v](https://user-images.githubusercontent.com/4194670/27746350-2acd4fc8-5dc7-11e7-8f0c-324604b7227d.png)

**Comment by int3l** [comment]
In order to have better recognition, you will need to train the tesseract for your specific case of captcha images. For more details check [Training Tesseract](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract) Wiki
