### ISSUE TITLE
how can I use the preserve_interword_spaces

### ISSUE THREAD

**Issue by guslep** [madmaze/pytesseract#68]
I am trying to use the preserve_interword_spaces options but it doesn't seems to work
I tried 
pytesseract.image_to_string(wandImg, lang='fra', config="-preserve_interword_spaces 1 -psm 5")
is there something I am missing?

**Comment by int3l** [comment]
Hello, you should follow the tesseract documentation.
As far as I can tell, there is no direct option/argument called **preserve_interword_spaces**.
preserve_interword_spaces is a config variable and you can setup its value with the **-c** command line flag.

Maybe you can try the following config:
`config="-c preserve_interword_spaces=1 -psm 5"`

**Note:** It might not work with tesseract version 4.00+ (this version is still in alpha).
