### ISSUE TITLE
Error encoding characters 

### ISSUE THREAD

**Issue by juliandavidmr** [madmaze/pytesseract#70]
I testing pytesseract, some images are recognized but not others.
The images not recognized are photos with text, the error is:

```
Encoding is cp437
Running...
Traceback (most recent call last):
  File "encuesta.py", line 13, in <module>
    print(pytesseract.image_to_string(Image.open('enc1.tiff'), boxes=False))
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1010-1011: character maps to <undefined>
```

I tested some commands of `chcp`, i.e:
```bash
chcp 437
chcp 16001
# and others
```
My actual code is:

```py
import sys
print "Encoding is", sys.stdin.encoding

try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract

pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract'
print "Running..."
print(pytesseract.image_to_string(Image.open('enc1.tiff'), boxes=False))
```

**Is there any way for pytesseract to continue with recognition regardless of errors?**

**Comment by int3l** [comment]
This error is not directly related to pytesseract.
As you can see, the error is a generic python encoding problem.
Here is one example from SO: [UnicodeEncodeError: 'charmap' codec can't encode - character maps to <undefined>, print function [duplicate]](https://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined).

Feel free to reopen the issue if you have any other questions.
