### ISSUE TITLE
No output result

### ISSUE THREAD

**Issue by coderchaser** [madmaze/pytesseract#71]
```python
	image=Image.open('C:\\Users\\Bobliao\\Desktop\\GetValidateCode.jpg')
	tessdata_dir_config = '--tessdata-dir "E:\\Program Files (x86)\\Tesseract-OCR\\tessdata"'
	b=pytesseract.image_to_string(image,config=tessdata_dir_config)
```
str `b` is empty and no errors happen.

below is my sample JPG

**Comment by coderchaser** [comment]
![getvalidatecode](https://user-images.githubusercontent.com/20502148/31042507-80b192ca-a5dc-11e7-8357-dc5a6b9ee4e2.jpg)
the str `b` shall be `bxUJ`,not empty.

**Comment by coderchaser** [comment]
OS:Win10 10.0.15063

**Comment by coderchaser** [comment]
It seems that this JPG file can't be analyzed.

**Comment by int3l** [comment]
This is a tesseract related issue, you need specific trained tessdata for such kind of images.
Please refer to the [Tesseract Training Documentation](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00) for more information how you can improve the recognition process for the Tesseract Engine.

Feel free to ask and reopen the issue if you have any other problems with the pytesseract wrapper.

**Comment by coderchaser** [comment]
ok,thank you.
