### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character u'\ufb01' in position 173 : illegal multibyte sequence

### ISSUE THREAD

**Issue by xiaoyanguoke** [madmaze/pytesseract#72]
![image](https://user-images.githubusercontent.com/15224735/31756440-afd400b6-b4d6-11e7-88f7-8b319fcef60c.png)

![image](https://user-images.githubusercontent.com/15224735/31756434-a3eef9c2-b4d6-11e7-96e6-499e0c985ef0.png)

how to solve?

**Comment by int3l** [comment]
@xiaoyanguoke you can try to use cygwin terminal platform under windows, since you have a mix of locales. The tesseract executable itself uses utf8 as output.
So you should either switch to it, in order to have proper output in cmd or you should switch the cmd prompt itself.

**Comment by xiaoyanguoke** [comment]
@int3l I still can not solve

**Comment by int3l** [comment]
Please provide us with the following information:

- OS name and version.
- python version
- sample code snippet + sample image file that produce the error.

I can't help much without reproducing the exact error.
Thanks for reporting the issue.
