### ISSUE TITLE
where to download the tesseract executable, please?

### ISSUE THREAD

**Issue by tzm1003306213** [madmaze/pytesseract#73]
pytesseract.pytesseract.tesseract_cmd = '<full_path_to_your_tesseract_executable>'
# Include the above line, if you don't have tesseract executable in your PATH
# Example tesseract_cmd: 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract'

Where should I to download the executable, please? I am working on ubuntu and mac OS

**Comment by int3l** [comment]
[Tesseract OCR](https://github.com/tesseract-ocr/tesseract) is a separate project started by Google.
You can check the official [Tesseract OCR documentation](https://github.com/tesseract-ocr/tesseract/wiki) of the project for more details.
The installation path is different for every OS.
There is a lot of information about how to install it - for example:
- [Using Tesseract on Ubuntu](https://www.linux.com/blog/using-tesseract-ubuntu)
- [Tesseract OCR: Installation and Usage on Ubuntu 16.04](https://www.howtoforge.com/tutorial/tesseract-ocr-installation-and-usage-on-ubuntu-16-04/)
- [Installing Tesseract 3.04+ in Ubuntu 14.04](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32)
