### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by 757470062** [madmaze/pytesseract#77]
code:

try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract
tessdata_dir_config = '--tessdata-dir "<replace_with_your_tessdata_dir_path>"'
print(pytesseract.image_to_string(Image.open('1.png'), lang='chi_sim', config=tessdata_dir_config))

err:

Traceback (most recent call last):
  File "/Users/huangangui/PycharmProjects/test/helloword.py", line 7, in <module>
    print(pytesseract.image_to_string(Image.open('1.png'), lang='chi_sim', config=tessdata_dir_config))
  File "/Library/Python/2.7/site-packages/pytesseract/pytesseract.py", line 125, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file <replace_with_your_tessdata_dir_path>/tessdata/chi_sim.traineddata')

**Comment by int3l** [comment]
Hello @757470062, please read the **[Usage](https://github.com/madmaze/pytesseract#usage)** section carefully.

You need to replace the base directory path, so tesseract can access the tessdata files for your chi_smi.
If you have any other question, please reopen the issue.
