### ISSUE TITLE
Using Custom Dictionary in Pytesseract

### ISSUE THREAD

**Issue by sanudatta11** [madmaze/pytesseract#78]
I have created a seperate custom dictionary and a custom function which works perfect with normal command line tesseract but I want to know how to use the same in the pytesseract package. Because in pytesseract it is not using that function, neither am having any clue of how to provide the function name .

In normal I use:
tesseract test.png myfunc #myfunc being the custom function

How to do the same in pytesseract

**Comment by jsreid13** [comment]
Can you provide any additional information on what your function does and what your dictionary contains?

**Comment by int3l** [comment]
@sanudatta11 you should append the name of the custom function to the string parameter - **config** for the **image_to_string** function.

Also if you want to use custom dictionary (trained data), you will need to either copy the trained file to the Tesseract default directory for trained files, or to pass the custom directory path to the dictionary (trained data) via the **config** string argument.

Please check the README file of the project for code examples.
