### ISSUE TITLE
WinError 6

### ISSUE THREAD

**Issue by fym0121** [madmaze/pytesseract#79]
WIN7 32bit 
I have add tesseract.exe to PATH
when I call pytesseract.image_to_string, I get the Exception:
2017-12-04 17:21:09,545 Thread-3: [WinError 6] 句柄无效。
Traceback (most recent call last):
  File "ui.py", line 136, in do_guoshui
    row['nsrmc'] = g.login()
  File "guoshui.py", line 164, in login
    "checkCode": self.checkCode()
  File "guoshui.py", line 153, in checkCode
    cc = self.shibie_tesseract(image_file)
  File "guoshui.py", line 114, in shibie_tesseract
    num = self.image_to_string(img)
  File "guoshui.py", line 87, in image_to_string
    subprocess.call(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "subprocess.py", line 267, in call
  File "subprocess.py", line 665, in __init__
  File "subprocess.py", line 883, in _get_handles
OSError: [WinError 6] 句柄无效。

so I google, and find the solution。
    # proc = subprocess.Popen(command, stderr=subprocess.PIPE)
    proc = subprocess.Popen(command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            shell=True)

**Comment by int3l** [comment]
Thank you very much for the report!
I will add the missing arguments, but shell=True is not needed.
The error is related to the file handles for the tesseract subprocess.

There is no need to enable the shell option.
If you can. please try to run the script with shell=False and let me know if it work without problems.

**Comment by fym0121** [comment]
I forgot to say that running.Py files directly is no problem, but when you use pyinstaller to compile and generate.Exe files, there will be a [WinERROR 6] problem. So I don't know whether this is a question of pytesseract or a problem with pyinstaller. It does work with this method, but there is a small problem, always playing the doc window.
Shell=False, you can work.

**Comment by int3l** [comment]
I see, ok then thanks for the information!
I will close the issue, since you already post workaround/solution.
