### ISSUE TITLE
For cropped portion of image from frames shows Error "object has no attribute 'split'"

### ISSUE THREAD

**Issue by muntahi398** [madmaze/pytesseract#82]
Works fine with images loaded from a directory, but when I try to apply this on camera frame shows following error:
`Traceback (most recent call last):
  File "Traffic_Sign_Detector.py", line 30, in <module>
    text=pytesseract.image_to_string(roi_gray, lang = 'eng')
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 104, in image_to_string
    if len(image.split()) == 4:
AttributeError: 'numpy.ndarray' object has no attribute 'split'`

**Comment by int3l** [comment]
@muntahi398 Thanks for reporting the issue.
Can you try to install the latest version of pytesseract from github.
You can get the installation commands from the documentation README.

Let me know if the latest version fixes your issue or not.
It is possible that the camera frames are not support images by the python wrapper logic.
If it still doesn't work, please upload and provide link to sample camera frame file, so we can test with it.

**Comment by muntahi398** [comment]
I kind of solved my issue by converting opencv image to pillow image, then
it worked fine. But as OpenCV is widely used, it should be supported also
for camera frames, right?



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by int3l** [comment]
Yes, that's true - I will add feature request for OpenCV support.

**Comment by princebhatia09** [comment]
Hi i tried the same ,converted my opencv images to PIL but i received another error

AttributeError: 'Image' object has no attribute 'shape'  how did you fixed that error?
