### ISSUE TITLE
Use pytesseract on other lang issue

### ISSUE THREAD

**Issue by moonlovestar** [madmaze/pytesseract#92]
Hello,

    I want to use pytesseract to do ocr on jpn image, which can successfully get string by using:

    `**tesseract src.png output.log -l jpn --tessdata-dir "<My Windows tessetact path>"** `

    However, I cannot get string by using pytesseract. I tried to print the command send into tessetact in the pytesseract.py in my python site-packages dir:

    In run_tesseract function:
    `
    **+print(command)
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
    status = proc.wait()`

    In image_to_string function:
    `
    +print('Image to String. lang = {0}'.format(lang))
    status, error_string = run_tesseract(input_file_name,
                                             output_file_name_base,
                                             lang=lang,
                                             boxes=boxes,
                                             config=config)**
    `
    The output are:

    `**Image to String. lang = jpn
    ['tesseract', 'C:\\Users\\<My username>\\AppData\\Local\\Temp\\tess_dgb290mi.bmp', 'C
    :\\Users\\<My username>\\AppData\\Local\\Temp\\tess_m4crx5fn', '-l', 'jpn', '--tessdata-dir', '<My Windows tessetact path>']**`

    Both them seems correctly.
    Do you have any suggestion how to address the problem?

    Test jpn image is using the img in  this website:
    http://teru0rc4.hatenablog.com/entry/2017/08/09/230046

Regards,
Moonlove

**Comment by int3l** [comment]
Hi @moonlovestar , thanks for reporting the issue.
Can you post what version of pytesseract is used?
Also if possible - the version of python interpreter.

**Comment by int3l** [comment]
@moonlovestar - I managed to reproduce your problem.
The current method of discarding the alpha channel with image conversion, doesn't work very well.
I changed the way how pytesseract handles such images - please test the latest pytesseract version from master and let me know if there are any other problems.

**Comment by moonlovestar** [comment]
Version 0.1.8 Pytesseract cannot solve the issue but I can see some clue, let's use another thread to talk.
