### ISSUE TITLE
Issue with `status` not being defined in `run_tesseract`

### ISSUE THREAD

**Issue by dmitrijsc** [madmaze/pytesseract#93]
Hello,

I've been debugging the package and found that `status` variable is not defined in `run_tesseract` and should be replaced with `status_code`.  Line Nr. 107

Sorry for not creating PR for this issue.

**Comment by int3l** [comment]
Hi @dmitrijsc can you report the pytesseract version?

**Comment by dmitrijsc** [comment]
Latest master. Users will never see the issue because this code is covered by `try` block in `run_and_get_output`. 

```
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
    status_code, error_string = proc.wait(), proc.stderr.read()
    proc.stderr.close()

    if status_code:
        raise TesseractError(status, get_errors(error_string))

    return True
```

**Comment by int3l** [comment]
Fixed with latest commit.
Feel free to reopen if you have any additional comments.
