### ISSUE TITLE
ubuntu12.04 Unsupported image object

### ISSUE THREAD

**Issue by Rockyzsu** [madmaze/pytesseract#95]
File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 116, in image_to_string
    image = prepare(image)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 95, in prepare
    raise TypeError('Unsupported image object')
TypeError: Unsupported image object

I have setup env path and install tesseract-ocr and data file, this image is jpeg format and can open with my photo viewer.

how to fix it ? thank!

**Comment by Rockyzsu** [comment]
In [5]: im
Out[5]: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=275x149 at 0x29F3F50>

In [6]: pytesseract.image_to_string(im)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-48e61b05dc24> in <module>()
----> 1 pytesseract.image_to_string(im)

/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.pyc in image_to_string(image, lang, boxes, config, nice)
    114     '''
    115 
--> 116     image = prepare(image)
    117     if len(image.getbands()) == 4:
    118         # In case we have 4 channels, lets discard the Alpha.

/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.pyc in prepare(image)
     93         return Image.fromarray(image)
     94 
---> 95     raise TypeError('Unsupported image object')
     96 
     97 

TypeError: Unsupported image object

In [7]:

**Comment by int3l** [comment]
Hi @Rockyzsu thank you for reporting the issue.

Can you provide sample (test) image if possible?
It seems that the image object is different then the supported one.

**Comment by int3l** [comment]
Check/install the latest available version from github and test.
Closing the issue since there is no additional information about the problem.
Feel free to reopen if you have any additional comments.

**Comment by TheDevKiller** [comment]
Hi, I have the same issue
