### ISSUE TITLE
Mismatch in output

### ISSUE THREAD

**Issue by MehulBhardwaj91** [madmaze/pytesseract#96]
![test](https://user-images.githubusercontent.com/23649424/35470730-cecca99a-0374-11e8-8862-5590248a6813.png)
Hi, I am using Tesseract 4.0 on Ubuntu 16.04.

I used the pytesseract package inside my program as follows.
```
from PIL import Image
import glob
import pytesseract


def image2text(images):
    im = Image.open(images)
    text = pytesseract.image_to_string(im)
    print(text)

for images in glob.iglob('/home/mehul/test/*.png'):
    image2text(images)
```
The output was 
```
a_ nhhng;
bmb 03000.9.
cccc-cc pHJMfE
ddflgl—ﬂ ‘qW
EereeeeJ erVXY
.fW 519’???
951338an tOFJLoLJ'i
h AMTA" u mung):
iTTTT—F vvvuvu
jTTj‘J‘j‘ wlgwww
kkkkT—k— XTTMLK
1mg. ywvw
m_mmmem 22-1242?
```
When I use tesseract from command line on the same image, the output is
```
aaoooa nhhhﬂh
bbbbbb OOOOoo
CCcc-CC pf’ﬁﬁi’ﬁ
ddclololol lquw
Qeeeee rvaxr
tying; 53933.3
96388:} toLatan
hAAMA .uuwuuu
iii/Ir vvvuvw
jij'jid Wwwwww
kkkkkk XXJLMLK
lilﬂfli ywvw
mmmmmm zzzzzz
```
I have attached my image for reference. Output of printed text is same for both the methods and therefore i have excluded that from both the outputs.

What could be the reason for this?

**Comment by int3l** [comment]
Hi @MehulBhardwaj91 ,
I have an idea, where the problem is, but can you report your version of pytesseract and the exact tesseract cli command that you are using, so I can test and confirm my theory.

Thank you for reporting the issue.

**Comment by int3l** [comment]
@MehulBhardwaj91 you can test the latest master snapshot of the pytesseract from github.
I just committed additional logic that preserves the source image format, which could fix your issue.
