### ISSUE TITLE
Running image_to_boxes() deletes all my files

### ISSUE THREAD

**Issue by lham** [madmaze/pytesseract#97]
If I run this script (rev.py)

```
import pytesseract as tess
from skimage import io, color
 
image_rgb  = io.imread('map2.png')                                                                                                                                                                       
image_gray = color.rgb2gray(image_rgb)
print(tess.image_to_boxes(image_gray))
```
all of my files in folder gets deleted. Both the python script rev.py and the image map2.png as well as any other non-folder files.

The error and stack presented is
```
Traceback (most recent call last):
  File "rev.py", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 210, in image_to_boxes
    return run_and_get_output(image, 'box', lang, config, nice)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 126, in run_and_get_output
    temp_name, img_extention = save_image(image)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 82, in save_image
    image.save(input_file_name, format=img_extention, **image.info)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/dist-packages/PIL/PngImagePlugin.py", line 726, in _save
    raise IOError("cannot write mode %s as PNG" % mode)
IOError: cannot write mode F as PNG
```

I'm running
```
pytesseract (0.1.9)
scikit-image (0.14dev)
Pillow (5.0.0)
Python 2.7.6
tesseract 3.03
```

**Comment by int3l** [comment]
Hi @lham, thank you for reporting the issue.
This is really stupid mistake of mine ...

**Comment by int3l** [comment]
By the way, is it possible to provide the test image, that triggers the Exception itself.
It's not directly related to the files removing bug, but it's not good that it can't save the image properly.

**Comment by int3l** [comment]
Please test the new release v0.2.0 and let us know if it fixes your issues.
Feel free to close the issue if that's the case.

Once again, thank for reporting the problem.

**Comment by lham** [comment]
It fixed the problem. Thanks for the fast response!

I'm attaching the image which caused the problem. It didn't yield any results when using the grayscale image (however the rgb one did), so I suspect it is in some invalid representation from scikit-image.

![map2](https://user-images.githubusercontent.com/3420315/35647094-c24d7e00-06d1-11e8-95a0-68daaf6f28c1.png)
.
