### ISSUE TITLE
image_to_data: Problem in temporary file

### ISSUE THREAD

**Issue by MehulBhardwaj91** [madmaze/pytesseract#98]
Hi, I am using pytesseract 0.2.0, the version with the latest commit.

I am getting the following error when using pytesseract.image_to_data

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    image2text(images)
  File "test.py", line 9, in image2text
    data = pytesseract.image_to_data(image, lang=None, config='', nice=0, output_type=pytesseract.Output.DICT)
  File "/home/mehul/.virtualenvs/cv/local/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 228, in image_to_data
    run_and_get_output(image, 'tsv', lang, config, nice), '\t', -1)
  File "/home/mehul/.virtualenvs/cv/local/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 142, in run_and_get_output
    with open(filename, 'rb') as output_file:
IOError: [Errno 2] No such file or directory: '/tmp/tess_OAlhmD_out.tsv'

Either the temp file is not created or program is searching for wrong temp file.

**Comment by int3l** [comment]
Hi @MehulBhardwaj91 ,
can you share an example image that triggers the IOError and the tesseract version itself?
Maybe tesseract fails to extract anything from the image.

**Comment by MehulBhardwaj91** [comment]
![upload](https://user-images.githubusercontent.com/23649424/35624283-918de600-06b4-11e8-9fee-9c98163c9ecb.png)
Hi, 

Tesseract and associated libraries version
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
 Found AVX
 Found SSE
I have also attached an example image. FYI I do get an output when I used pytesseract.image_to_string with output type as DICT. Also when I use tesseract from terminal I do get an output for that particular image. So I have a feeling that nothing is wrong with the image.
Best Regards

**Comment by int3l** [comment]
It's a bit odd, I can't reproduce the problem with your image. It manages to return the image_to_data dict output.

What are the versions of your python and OS. I guess that it is some kind of Linux distro.

**Comment by int3l** [comment]
Successfully tested under Linux (Ubuntu/Fedora) and Windows 7 with python 2.7.14 and python 3.6.4.

**Comment by MehulBhardwaj91** [comment]
Python is 2.7 and OS is Ubuntu 16.04. I am running it in a virtual environment. I can't think of anything because of which the execution might be interested. I tried looking at your code but frankly I couldn't figure out what might be causing the error. Anyway I am using the other function as of know and it is working for me. Let's see if anyone else reports something similar.
Thanks for your reply and for pytesseract.

**Comment by MehulBhardwaj91** [comment]
The error message was this
IOError: [Errno 2] No such file or directory: '/tmp/tess_OAlhmD_out.tsv'

In this where is the 'tmp' directory located. there is no 'tmp' directory in the pytesseract package directory.

**Comment by int3l** [comment]
``/tmp`` is the default system temporary folder for the Linux operating systems.
By the way, is there any chance that you are using your own trained data files?

**Comment by neouyghur** [comment]
It is also happening to me, how I can I fix it? Thanks.

**Comment by int3l** [comment]
@MehulBhardwaj91 , @neouyghur please try to use the new methods available in the newest versions of pytesseract. For tsv files, the method is **image_to_data**.

**Comment by rwk506** [comment]
I am also having this error when converting a PDF or .tiff image on Ubuntu 16.04 and Python 3.5.2. I am using the newer image_to_data() function:
```pytesseract.image_to_data(Image.open(imagepath))```

And pytesseract throws the same file not found error for the /tmp/ folder discussed previously in this thread:
```FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_2us0fh45_out.tsv'```

It works fine when I call tesseract via command line (even via subprocess in python).

**Comment by neouyghur** [comment]
I solved the problem by updating the tesseract version to the latest version on github.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rwk506** [comment]
I've installed v0.2.1 but still get the same results.

**Comment by int3l** [comment]
@rwk506 is it possible for you to provide a sample image/pdf that I can use for testing.
I want to test whether it is a problem with the image conversion login in pytesseract or the invocation command/method is wrong.

Also can you report your tesseract version, so I can test with the same binaries.
Thanks in advance!

**Comment by rwk506** [comment]
Sure! Here is my version info:
tesseract 3.05.01
 leptonica-1.74.4
  libjpeg 9c : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.8


image_to_string seems to be fine, it's image_to_data that seems to cause trouble. I've tried on several different files - primarily pdfs and tif images.

[Untitled.pdf](https://github.com/madmaze/pytesseract/files/1827934/Untitled.pdf)

I appreciate your help!!

**Comment by Jaiksah** [comment]
even i m facing similar error in windows 10 with python 3.6
when using Tesseract 

**import pytesseract
import subprocess
from PIL import Image
from pytesseract import image_to_string,image_to_data

img = Image.open(r"C:\Zerodha\Pi\images\test.jpeg")
text = image_to_data(img)**

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JAIKUM~1.ORA\\AppData\\Local\\Temp\\tess_esjvyiir_out.tsv'

**Comment by int3l** [comment]
@rwk506 I still can't reproduce your problem with the same version of python, pytesseract and tesseract.
What is your way of converting the pdf file to image?

I'm using Adobe Acrobat DC for the image conversion and pytesseract manages to extract the text from the resulting jpg image.

**Comment by Jaiksah** [comment]
I am trying to extract text from a image jpeg file.

**Comment by rwk506** [comment]
@int3l, I've tried converting with pdf2image and also with io.BytesIO in conjunction base64.b64decode.

Thanks again for helping out.

**Comment by Jaiksah** [comment]
which packages should i have to extract text from image ..i have PIL and pytesseract .Do i need more packages to do this conversion form image to text.

**Comment by int3l** [comment]
@Jaiksah please check the documentation - you can use the **image_to_string** function if you just want the text to be extracted.

**Comment by int3l** [comment]
@rwk506 I successfully managed to convert the sample image to string using both methods: converting with pdf2image and directly downloading your already converted sample image.

![pdf-jpg-example](https://user-images.githubusercontent.com/1278836/38001720-042ded06-3237-11e8-9dc4-aa02bfa91b2d.png)

There must be something else that prevents pytesseract from doing it's job.

**Comment by rwk506** [comment]
@int3l Oh no!! I'm so sorry - my mistake. It's supposed to be image_to_data, not image_to_string... image_to_string works fine, it's image_to_data that is giving me issues.

**Comment by int3l** [comment]
I know that :) This is why my test script executes the both methods.
Unfortunately I will need to test more, in order to find your specific problem, which is missing temp file for some odd reason.

**Comment by nivangio** [comment]
I am having the same issue. 

I ran tesseract with tsv mode and had the following error:

`read_params_file:  Can't open tsv`

After that, I ran my script on debugger mode and found out that run_tesseract receives the same error message when it runs tesseract but receives a 0 in status_code, so it doesn't throw an error at that point.

However, as no file was generated, when run_and_get_output tries to find the tsv file and it cannot do it of course.

**Comment by int3l** [comment]
@nivangio what is your version of tesseract? It seems that your tesseract doesn't support tsv.

**Comment by Xinark** [comment]
I'm having a related issue. Image_to_string works fine, but Image_to_data results only provide partial results. Using tesseract directly with tsv provides results as expected. Any fix?

![cropped](https://user-images.githubusercontent.com/19741877/39884151-d8703f60-5456-11e8-8ba3-211cce8e882d.PNG)

**Comment by rwk506** [comment]
I realize this is a little late, but my problem with temporary file write/read access was resolved when changing to ubuntu 18.04. There was some version issue conflict causing the previous version of ubuntu and pytesseract to not work together.
